// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD01_001 from "./SD01-001";
import c_SD01_002 from "./SD01-002";
import c_SD01_003 from "./SD01-003";
import c_SD01_004 from "./SD01-004";
import c_SD01_005 from "./SD01-005";
import c_SD01_006 from "./SD01-006";
import c_SD01_009 from "./SD01-009";
import c_SD01_011 from "./SD01-011";
import c_SD01_012 from "./SD01-012";
import c_SD01_013 from "./SD01-013";
import c_SD01_016 from "./SD01-016";

/**
 * Card scripts of SD01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD01_SCRIPTS: ScriptRegistry = {
  "SD01-001": c_SD01_001,
  "SD01-002": c_SD01_002,
  "SD01-003": c_SD01_003,
  "SD01-004": c_SD01_004,
  "SD01-005": c_SD01_005,
  "SD01-006": c_SD01_006,
  "SD01-009": c_SD01_009,
  "SD01-011": c_SD01_011,
  "SD01-012": c_SD01_012,
  "SD01-013": c_SD01_013,
  "SD01-016": c_SD01_016,
};
