// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD05_001 from "./SD05-001";
import c_SD05_002 from "./SD05-002";
import c_SD05_003 from "./SD05-003";
import c_SD05_004 from "./SD05-004";
import c_SD05_005 from "./SD05-005";
import c_SD05_006 from "./SD05-006";
import c_SD05_010 from "./SD05-010";
import c_SD05_011 from "./SD05-011";
import c_SD05_012 from "./SD05-012";
import c_SD05_013 from "./SD05-013";
import c_SD05_015 from "./SD05-015";
import c_SD05_016 from "./SD05-016";

/**
 * Card scripts of SD05, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD05_SCRIPTS: ScriptRegistry = {
  "SD05-001": c_SD05_001,
  "SD05-002": c_SD05_002,
  "SD05-003": c_SD05_003,
  "SD05-004": c_SD05_004,
  "SD05-005": c_SD05_005,
  "SD05-006": c_SD05_006,
  "SD05-010": c_SD05_010,
  "SD05-011": c_SD05_011,
  "SD05-012": c_SD05_012,
  "SD05-013": c_SD05_013,
  "SD05-015": c_SD05_015,
  "SD05-016": c_SD05_016,
};
