// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_ECP02_001 from "./ECP02-001";
import c_ECP02_002 from "./ECP02-002";
import c_ECP02_003 from "./ECP02-003";
import c_ECP02_004 from "./ECP02-004";
import c_ECP02_005 from "./ECP02-005";
import c_ECP02_006 from "./ECP02-006";
import c_ECP02_007 from "./ECP02-007";
import c_ECP02_008 from "./ECP02-008";
import c_ECP02_009 from "./ECP02-009";
import c_ECP02_010 from "./ECP02-010";
import c_ECP02_011 from "./ECP02-011";
import c_ECP02_012 from "./ECP02-012";
import c_ECP02_013 from "./ECP02-013";
import c_ECP02_014 from "./ECP02-014";
import c_ECP02_015 from "./ECP02-015";
import c_ECP02_016 from "./ECP02-016";
import c_ECP02_017 from "./ECP02-017";
import c_ECP02_018 from "./ECP02-018";
import c_ECP02_019 from "./ECP02-019";
import c_ECP02_020 from "./ECP02-020";
import c_ECP02_021 from "./ECP02-021";
import c_ECP02_022 from "./ECP02-022";
import c_ECP02_023 from "./ECP02-023";
import c_ECP02_024 from "./ECP02-024";
import c_ECP02_025 from "./ECP02-025";
import c_ECP02_026 from "./ECP02-026";
import c_ECP02_027 from "./ECP02-027";
import c_ECP02_028 from "./ECP02-028";
import c_ECP02_029 from "./ECP02-029";
import c_ECP02_030 from "./ECP02-030";
import c_ECP02_031 from "./ECP02-031";
import c_ECP02_032 from "./ECP02-032";
import c_ECP02_033 from "./ECP02-033";
import c_ECP02_034 from "./ECP02-034";
import c_ECP02_035 from "./ECP02-035";
import c_ECP02_036 from "./ECP02-036";
import c_ECP02_037 from "./ECP02-037";
import c_ECP02_038 from "./ECP02-038";
import c_ECP02_039 from "./ECP02-039";
import c_ECP02_040 from "./ECP02-040";
import c_ECP02_041 from "./ECP02-041";
import c_ECP02_042 from "./ECP02-042";
import c_ECP02_043 from "./ECP02-043";
import c_ECP02_044 from "./ECP02-044";
import c_ECP02_045 from "./ECP02-045";
import c_ECP02_046 from "./ECP02-046";
import c_ECP02_047 from "./ECP02-047";
import c_ECP02_048 from "./ECP02-048";
import c_ECP02_049 from "./ECP02-049";
import c_ECP02_050 from "./ECP02-050";
import c_ECP02_051 from "./ECP02-051";
import c_ECP02_052 from "./ECP02-052";
import c_ECP02_053 from "./ECP02-053";
import c_ECP02_054 from "./ECP02-054";
import c_ECP02_055 from "./ECP02-055";
import c_ECP02_056 from "./ECP02-056";
import c_ECP02_057 from "./ECP02-057";
import c_ECP02_058 from "./ECP02-058";
import c_ECP02_059 from "./ECP02-059";
import c_ECP02_060 from "./ECP02-060";
import c_ECP02_061 from "./ECP02-061";
import c_ECP02_062 from "./ECP02-062";
import c_ECP02_063 from "./ECP02-063";
import c_ECP02_064 from "./ECP02-064";
import c_ECP02_065 from "./ECP02-065";
import c_ECP02_066 from "./ECP02-066";
import c_ECP02_067 from "./ECP02-067";
import c_ECP02_068 from "./ECP02-068";
import c_ECP02_069 from "./ECP02-069";
import c_ECP02_070 from "./ECP02-070";
import c_ECP02_071 from "./ECP02-071";
import c_ECP02_072 from "./ECP02-072";

/**
 * Card scripts of ECP02, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const ECP02_SCRIPTS: ScriptRegistry = {
  "ECP02-001": c_ECP02_001,
  "ECP02-002": c_ECP02_002,
  "ECP02-003": c_ECP02_003,
  "ECP02-004": c_ECP02_004,
  "ECP02-005": c_ECP02_005,
  "ECP02-006": c_ECP02_006,
  "ECP02-007": c_ECP02_007,
  "ECP02-008": c_ECP02_008,
  "ECP02-009": c_ECP02_009,
  "ECP02-010": c_ECP02_010,
  "ECP02-011": c_ECP02_011,
  "ECP02-012": c_ECP02_012,
  "ECP02-013": c_ECP02_013,
  "ECP02-014": c_ECP02_014,
  "ECP02-015": c_ECP02_015,
  "ECP02-016": c_ECP02_016,
  "ECP02-017": c_ECP02_017,
  "ECP02-018": c_ECP02_018,
  "ECP02-019": c_ECP02_019,
  "ECP02-020": c_ECP02_020,
  "ECP02-021": c_ECP02_021,
  "ECP02-022": c_ECP02_022,
  "ECP02-023": c_ECP02_023,
  "ECP02-024": c_ECP02_024,
  "ECP02-025": c_ECP02_025,
  "ECP02-026": c_ECP02_026,
  "ECP02-027": c_ECP02_027,
  "ECP02-028": c_ECP02_028,
  "ECP02-029": c_ECP02_029,
  "ECP02-030": c_ECP02_030,
  "ECP02-031": c_ECP02_031,
  "ECP02-032": c_ECP02_032,
  "ECP02-033": c_ECP02_033,
  "ECP02-034": c_ECP02_034,
  "ECP02-035": c_ECP02_035,
  "ECP02-036": c_ECP02_036,
  "ECP02-037": c_ECP02_037,
  "ECP02-038": c_ECP02_038,
  "ECP02-039": c_ECP02_039,
  "ECP02-040": c_ECP02_040,
  "ECP02-041": c_ECP02_041,
  "ECP02-042": c_ECP02_042,
  "ECP02-043": c_ECP02_043,
  "ECP02-044": c_ECP02_044,
  "ECP02-045": c_ECP02_045,
  "ECP02-046": c_ECP02_046,
  "ECP02-047": c_ECP02_047,
  "ECP02-048": c_ECP02_048,
  "ECP02-049": c_ECP02_049,
  "ECP02-050": c_ECP02_050,
  "ECP02-051": c_ECP02_051,
  "ECP02-052": c_ECP02_052,
  "ECP02-053": c_ECP02_053,
  "ECP02-054": c_ECP02_054,
  "ECP02-055": c_ECP02_055,
  "ECP02-056": c_ECP02_056,
  "ECP02-057": c_ECP02_057,
  "ECP02-058": c_ECP02_058,
  "ECP02-059": c_ECP02_059,
  "ECP02-060": c_ECP02_060,
  "ECP02-061": c_ECP02_061,
  "ECP02-062": c_ECP02_062,
  "ECP02-063": c_ECP02_063,
  "ECP02-064": c_ECP02_064,
  "ECP02-065": c_ECP02_065,
  "ECP02-066": c_ECP02_066,
  "ECP02-067": c_ECP02_067,
  "ECP02-068": c_ECP02_068,
  "ECP02-069": c_ECP02_069,
  "ECP02-070": c_ECP02_070,
  "ECP02-071": c_ECP02_071,
  "ECP02-072": c_ECP02_072,
};
