// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP21_001 from "./BP21-001";
import c_BP21_002 from "./BP21-002";
import c_BP21_003 from "./BP21-003";
import c_BP21_004 from "./BP21-004";
import c_BP21_005 from "./BP21-005";
import c_BP21_006 from "./BP21-006";
import c_BP21_007 from "./BP21-007";
import c_BP21_008 from "./BP21-008";
import c_BP21_009 from "./BP21-009";
import c_BP21_010 from "./BP21-010";
import c_BP21_011 from "./BP21-011";
import c_BP21_012 from "./BP21-012";
import c_BP21_013 from "./BP21-013";
import c_BP21_015 from "./BP21-015";
import c_BP21_016 from "./BP21-016";
import c_BP21_017 from "./BP21-017";
import c_BP21_018 from "./BP21-018";
import c_BP21_019 from "./BP21-019";
import c_BP21_020 from "./BP21-020";
import c_BP21_021 from "./BP21-021";
import c_BP21_022 from "./BP21-022";
import c_BP21_023 from "./BP21-023";
import c_BP21_024 from "./BP21-024";
import c_BP21_025 from "./BP21-025";
import c_BP21_026 from "./BP21-026";
import c_BP21_027 from "./BP21-027";
import c_BP21_028 from "./BP21-028";
import c_BP21_029 from "./BP21-029";
import c_BP21_030 from "./BP21-030";
import c_BP21_031 from "./BP21-031";
import c_BP21_032 from "./BP21-032";
import c_BP21_033 from "./BP21-033";
import c_BP21_034 from "./BP21-034";
import c_BP21_035 from "./BP21-035";
import c_BP21_036 from "./BP21-036";
import c_BP21_037 from "./BP21-037";
import c_BP21_038 from "./BP21-038";
import c_BP21_039 from "./BP21-039";
import c_BP21_040 from "./BP21-040";
import c_BP21_041 from "./BP21-041";
import c_BP21_042 from "./BP21-042";
import c_BP21_043 from "./BP21-043";
import c_BP21_044 from "./BP21-044";
import c_BP21_045 from "./BP21-045";
import c_BP21_046 from "./BP21-046";
import c_BP21_047 from "./BP21-047";
import c_BP21_048 from "./BP21-048";
import c_BP21_049 from "./BP21-049";
import c_BP21_050 from "./BP21-050";
import c_BP21_051 from "./BP21-051";
import c_BP21_052 from "./BP21-052";
import c_BP21_053 from "./BP21-053";
import c_BP21_054 from "./BP21-054";
import c_BP21_055 from "./BP21-055";
import c_BP21_056 from "./BP21-056";
import c_BP21_057 from "./BP21-057";
import c_BP21_058 from "./BP21-058";
import c_BP21_059 from "./BP21-059";
import c_BP21_060 from "./BP21-060";
import c_BP21_061 from "./BP21-061";
import c_BP21_062 from "./BP21-062";
import c_BP21_063 from "./BP21-063";
import c_BP21_064 from "./BP21-064";
import c_BP21_065 from "./BP21-065";
import c_BP21_066 from "./BP21-066";
import c_BP21_067 from "./BP21-067";
import c_BP21_068 from "./BP21-068";
import c_BP21_069 from "./BP21-069";
import c_BP21_070 from "./BP21-070";
import c_BP21_071 from "./BP21-071";
import c_BP21_072 from "./BP21-072";
import c_BP21_073 from "./BP21-073";
import c_BP21_074 from "./BP21-074";
import c_BP21_075 from "./BP21-075";
import c_BP21_076 from "./BP21-076";
import c_BP21_077 from "./BP21-077";
import c_BP21_078 from "./BP21-078";
import c_BP21_079 from "./BP21-079";
import c_BP21_080 from "./BP21-080";
import c_BP21_081 from "./BP21-081";
import c_BP21_082 from "./BP21-082";
import c_BP21_083 from "./BP21-083";
import c_BP21_084 from "./BP21-084";
import c_BP21_085 from "./BP21-085";
import c_BP21_086 from "./BP21-086";
import c_BP21_087 from "./BP21-087";
import c_BP21_088 from "./BP21-088";
import c_BP21_089 from "./BP21-089";
import c_BP21_090 from "./BP21-090";
import c_BP21_091 from "./BP21-091";
import c_BP21_092 from "./BP21-092";
import c_BP21_093 from "./BP21-093";
import c_BP21_094 from "./BP21-094";
import c_BP21_095 from "./BP21-095";
import c_BP21_096 from "./BP21-096";
import c_BP21_097 from "./BP21-097";
import c_BP21_098 from "./BP21-098";
import c_BP21_099 from "./BP21-099";
import c_BP21_100 from "./BP21-100";
import c_BP21_101 from "./BP21-101";
import c_BP21_102 from "./BP21-102";
import c_BP21_103 from "./BP21-103";
import c_BP21_104 from "./BP21-104";
import c_BP21_105 from "./BP21-105";
import c_BP21_106 from "./BP21-106";
import c_BP21_107 from "./BP21-107";
import c_BP21_108 from "./BP21-108";
import c_BP21_109 from "./BP21-109";
import c_BP21_110 from "./BP21-110";
import c_BP21_111 from "./BP21-111";
import c_BP21_112 from "./BP21-112";
import c_BP21_113 from "./BP21-113";
import c_BP21_114 from "./BP21-114";
import c_BP21_115 from "./BP21-115";
import c_BP21_116 from "./BP21-116";
import c_BP21_PR10 from "./BP21-PR10";
import c_BP21_T01 from "./BP21-T01";
import c_BP21_T02 from "./BP21-T02";
import c_BP21_T03 from "./BP21-T03";
import c_BP21_T04 from "./BP21-T04";
import c_BP21_T05 from "./BP21-T05";
import c_BP21_T06 from "./BP21-T06";
import c_BP21_T07 from "./BP21-T07";
import c_BP21_T08 from "./BP21-T08";
import c_BP21_T09 from "./BP21-T09";
import c_BP21_T10 from "./BP21-T10";

/**
 * Card scripts of BP21, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP21_SCRIPTS: ScriptRegistry = {
  "BP21-001": c_BP21_001,
  "BP21-002": c_BP21_002,
  "BP21-003": c_BP21_003,
  "BP21-004": c_BP21_004,
  "BP21-005": c_BP21_005,
  "BP21-006": c_BP21_006,
  "BP21-007": c_BP21_007,
  "BP21-008": c_BP21_008,
  "BP21-009": c_BP21_009,
  "BP21-010": c_BP21_010,
  "BP21-011": c_BP21_011,
  "BP21-012": c_BP21_012,
  "BP21-013": c_BP21_013,
  "BP21-015": c_BP21_015,
  "BP21-016": c_BP21_016,
  "BP21-017": c_BP21_017,
  "BP21-018": c_BP21_018,
  "BP21-019": c_BP21_019,
  "BP21-020": c_BP21_020,
  "BP21-021": c_BP21_021,
  "BP21-022": c_BP21_022,
  "BP21-023": c_BP21_023,
  "BP21-024": c_BP21_024,
  "BP21-025": c_BP21_025,
  "BP21-026": c_BP21_026,
  "BP21-027": c_BP21_027,
  "BP21-028": c_BP21_028,
  "BP21-029": c_BP21_029,
  "BP21-030": c_BP21_030,
  "BP21-031": c_BP21_031,
  "BP21-032": c_BP21_032,
  "BP21-033": c_BP21_033,
  "BP21-034": c_BP21_034,
  "BP21-035": c_BP21_035,
  "BP21-036": c_BP21_036,
  "BP21-037": c_BP21_037,
  "BP21-038": c_BP21_038,
  "BP21-039": c_BP21_039,
  "BP21-040": c_BP21_040,
  "BP21-041": c_BP21_041,
  "BP21-042": c_BP21_042,
  "BP21-043": c_BP21_043,
  "BP21-044": c_BP21_044,
  "BP21-045": c_BP21_045,
  "BP21-046": c_BP21_046,
  "BP21-047": c_BP21_047,
  "BP21-048": c_BP21_048,
  "BP21-049": c_BP21_049,
  "BP21-050": c_BP21_050,
  "BP21-051": c_BP21_051,
  "BP21-052": c_BP21_052,
  "BP21-053": c_BP21_053,
  "BP21-054": c_BP21_054,
  "BP21-055": c_BP21_055,
  "BP21-056": c_BP21_056,
  "BP21-057": c_BP21_057,
  "BP21-058": c_BP21_058,
  "BP21-059": c_BP21_059,
  "BP21-060": c_BP21_060,
  "BP21-061": c_BP21_061,
  "BP21-062": c_BP21_062,
  "BP21-063": c_BP21_063,
  "BP21-064": c_BP21_064,
  "BP21-065": c_BP21_065,
  "BP21-066": c_BP21_066,
  "BP21-067": c_BP21_067,
  "BP21-068": c_BP21_068,
  "BP21-069": c_BP21_069,
  "BP21-070": c_BP21_070,
  "BP21-071": c_BP21_071,
  "BP21-072": c_BP21_072,
  "BP21-073": c_BP21_073,
  "BP21-074": c_BP21_074,
  "BP21-075": c_BP21_075,
  "BP21-076": c_BP21_076,
  "BP21-077": c_BP21_077,
  "BP21-078": c_BP21_078,
  "BP21-079": c_BP21_079,
  "BP21-080": c_BP21_080,
  "BP21-081": c_BP21_081,
  "BP21-082": c_BP21_082,
  "BP21-083": c_BP21_083,
  "BP21-084": c_BP21_084,
  "BP21-085": c_BP21_085,
  "BP21-086": c_BP21_086,
  "BP21-087": c_BP21_087,
  "BP21-088": c_BP21_088,
  "BP21-089": c_BP21_089,
  "BP21-090": c_BP21_090,
  "BP21-091": c_BP21_091,
  "BP21-092": c_BP21_092,
  "BP21-093": c_BP21_093,
  "BP21-094": c_BP21_094,
  "BP21-095": c_BP21_095,
  "BP21-096": c_BP21_096,
  "BP21-097": c_BP21_097,
  "BP21-098": c_BP21_098,
  "BP21-099": c_BP21_099,
  "BP21-100": c_BP21_100,
  "BP21-101": c_BP21_101,
  "BP21-102": c_BP21_102,
  "BP21-103": c_BP21_103,
  "BP21-104": c_BP21_104,
  "BP21-105": c_BP21_105,
  "BP21-106": c_BP21_106,
  "BP21-107": c_BP21_107,
  "BP21-108": c_BP21_108,
  "BP21-109": c_BP21_109,
  "BP21-110": c_BP21_110,
  "BP21-111": c_BP21_111,
  "BP21-112": c_BP21_112,
  "BP21-113": c_BP21_113,
  "BP21-114": c_BP21_114,
  "BP21-115": c_BP21_115,
  "BP21-116": c_BP21_116,
  "BP21-PR10": c_BP21_PR10,
  "BP21-T01": c_BP21_T01,
  "BP21-T02": c_BP21_T02,
  "BP21-T03": c_BP21_T03,
  "BP21-T04": c_BP21_T04,
  "BP21-T05": c_BP21_T05,
  "BP21-T06": c_BP21_T06,
  "BP21-T07": c_BP21_T07,
  "BP21-T08": c_BP21_T08,
  "BP21-T09": c_BP21_T09,
  "BP21-T10": c_BP21_T10,
};
