// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CSD02b_001 from "./CSD02b-001";
import c_CSD02b_002 from "./CSD02b-002";
import c_CSD02b_003 from "./CSD02b-003";
import c_CSD02b_004 from "./CSD02b-004";
import c_CSD02b_005 from "./CSD02b-005";
import c_CSD02b_006 from "./CSD02b-006";
import c_CSD02b_007 from "./CSD02b-007";
import c_CSD02b_008 from "./CSD02b-008";
import c_CSD02b_009 from "./CSD02b-009";
import c_CSD02b_010 from "./CSD02b-010";
import c_CSD02b_011 from "./CSD02b-011";

/**
 * Card scripts of CSD02b, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CSD02b_SCRIPTS: ScriptRegistry = {
  "CSD02b-001": c_CSD02b_001,
  "CSD02b-002": c_CSD02b_002,
  "CSD02b-003": c_CSD02b_003,
  "CSD02b-004": c_CSD02b_004,
  "CSD02b-005": c_CSD02b_005,
  "CSD02b-006": c_CSD02b_006,
  "CSD02b-007": c_CSD02b_007,
  "CSD02b-008": c_CSD02b_008,
  "CSD02b-009": c_CSD02b_009,
  "CSD02b-010": c_CSD02b_010,
  "CSD02b-011": c_CSD02b_011,
};
