// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CSD02a_001 from "./CSD02a-001";
import c_CSD02a_002 from "./CSD02a-002";
import c_CSD02a_003 from "./CSD02a-003";
import c_CSD02a_004 from "./CSD02a-004";
import c_CSD02a_005 from "./CSD02a-005";
import c_CSD02a_006 from "./CSD02a-006";
import c_CSD02a_007 from "./CSD02a-007";
import c_CSD02a_008 from "./CSD02a-008";
import c_CSD02a_009 from "./CSD02a-009";
import c_CSD02a_010 from "./CSD02a-010";
import c_CSD02a_011 from "./CSD02a-011";

/**
 * Card scripts of CSD02a, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CSD02a_SCRIPTS: ScriptRegistry = {
  "CSD02a-001": c_CSD02a_001,
  "CSD02a-002": c_CSD02a_002,
  "CSD02a-003": c_CSD02a_003,
  "CSD02a-004": c_CSD02a_004,
  "CSD02a-005": c_CSD02a_005,
  "CSD02a-006": c_CSD02a_006,
  "CSD02a-007": c_CSD02a_007,
  "CSD02a-008": c_CSD02a_008,
  "CSD02a-009": c_CSD02a_009,
  "CSD02a-010": c_CSD02a_010,
  "CSD02a-011": c_CSD02a_011,
};
