// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP18_001 from "./BP18-001";
import c_BP18_002 from "./BP18-002";
import c_BP18_003 from "./BP18-003";
import c_BP18_004 from "./BP18-004";
import c_BP18_005 from "./BP18-005";
import c_BP18_006 from "./BP18-006";
import c_BP18_007 from "./BP18-007";
import c_BP18_008 from "./BP18-008";
import c_BP18_009 from "./BP18-009";
import c_BP18_010 from "./BP18-010";
import c_BP18_011 from "./BP18-011";
import c_BP18_012 from "./BP18-012";
import c_BP18_013 from "./BP18-013";
import c_BP18_014 from "./BP18-014";
import c_BP18_015 from "./BP18-015";
import c_BP18_016 from "./BP18-016";
import c_BP18_017 from "./BP18-017";
import c_BP18_018 from "./BP18-018";
import c_BP18_019 from "./BP18-019";
import c_BP18_020 from "./BP18-020";
import c_BP18_021 from "./BP18-021";
import c_BP18_022 from "./BP18-022";
import c_BP18_023 from "./BP18-023";
import c_BP18_024 from "./BP18-024";
import c_BP18_025 from "./BP18-025";
import c_BP18_026 from "./BP18-026";
import c_BP18_027 from "./BP18-027";
import c_BP18_028 from "./BP18-028";
import c_BP18_029 from "./BP18-029";
import c_BP18_030 from "./BP18-030";
import c_BP18_031 from "./BP18-031";
import c_BP18_032 from "./BP18-032";
import c_BP18_033 from "./BP18-033";
import c_BP18_034 from "./BP18-034";
import c_BP18_035 from "./BP18-035";
import c_BP18_036 from "./BP18-036";
import c_BP18_037 from "./BP18-037";
import c_BP18_038 from "./BP18-038";
import c_BP18_039 from "./BP18-039";
import c_BP18_040 from "./BP18-040";
import c_BP18_041 from "./BP18-041";
import c_BP18_042 from "./BP18-042";
import c_BP18_043 from "./BP18-043";
import c_BP18_044 from "./BP18-044";
import c_BP18_045 from "./BP18-045";
import c_BP18_046 from "./BP18-046";
import c_BP18_047 from "./BP18-047";
import c_BP18_048 from "./BP18-048";
import c_BP18_049 from "./BP18-049";
import c_BP18_050 from "./BP18-050";
import c_BP18_051 from "./BP18-051";
import c_BP18_052 from "./BP18-052";
import c_BP18_053 from "./BP18-053";
import c_BP18_054 from "./BP18-054";
import c_BP18_055 from "./BP18-055";
import c_BP18_056 from "./BP18-056";
import c_BP18_057 from "./BP18-057";
import c_BP18_058 from "./BP18-058";
import c_BP18_059 from "./BP18-059";
import c_BP18_060 from "./BP18-060";
import c_BP18_061 from "./BP18-061";
import c_BP18_062 from "./BP18-062";
import c_BP18_063 from "./BP18-063";
import c_BP18_064 from "./BP18-064";
import c_BP18_065 from "./BP18-065";
import c_BP18_066 from "./BP18-066";
import c_BP18_067 from "./BP18-067";
import c_BP18_068 from "./BP18-068";
import c_BP18_069 from "./BP18-069";
import c_BP18_070 from "./BP18-070";
import c_BP18_071 from "./BP18-071";
import c_BP18_072 from "./BP18-072";
import c_BP18_073 from "./BP18-073";
import c_BP18_074 from "./BP18-074";
import c_BP18_075 from "./BP18-075";
import c_BP18_076 from "./BP18-076";
import c_BP18_077 from "./BP18-077";
import c_BP18_078 from "./BP18-078";
import c_BP18_079 from "./BP18-079";
import c_BP18_080 from "./BP18-080";
import c_BP18_081 from "./BP18-081";
import c_BP18_082 from "./BP18-082";
import c_BP18_083 from "./BP18-083";
import c_BP18_084 from "./BP18-084";
import c_BP18_085 from "./BP18-085";
import c_BP18_086 from "./BP18-086";
import c_BP18_087 from "./BP18-087";
import c_BP18_088 from "./BP18-088";
import c_BP18_089 from "./BP18-089";
import c_BP18_090 from "./BP18-090";
import c_BP18_091 from "./BP18-091";
import c_BP18_092 from "./BP18-092";
import c_BP18_093 from "./BP18-093";
import c_BP18_094 from "./BP18-094";
import c_BP18_095 from "./BP18-095";
import c_BP18_096 from "./BP18-096";
import c_BP18_097 from "./BP18-097";
import c_BP18_098 from "./BP18-098";
import c_BP18_099 from "./BP18-099";
import c_BP18_100 from "./BP18-100";
import c_BP18_101 from "./BP18-101";
import c_BP18_102 from "./BP18-102";
import c_BP18_103 from "./BP18-103";
import c_BP18_104 from "./BP18-104";
import c_BP18_105 from "./BP18-105";
import c_BP18_106 from "./BP18-106";
import c_BP18_107 from "./BP18-107";
import c_BP18_108 from "./BP18-108";
import c_BP18_109 from "./BP18-109";
import c_BP18_110 from "./BP18-110";
import c_BP18_111 from "./BP18-111";
import c_BP18_112 from "./BP18-112";
import c_BP18_113 from "./BP18-113";
import c_BP18_114 from "./BP18-114";
import c_BP18_115 from "./BP18-115";
import c_BP18_116 from "./BP18-116";
import c_BP18_117 from "./BP18-117";
import c_BP18_118 from "./BP18-118";
import c_BP18_119 from "./BP18-119";
import c_BP18_120 from "./BP18-120";
import c_BP18_121 from "./BP18-121";
import c_BP18_123 from "./BP18-123";
import c_BP18_124 from "./BP18-124";
import c_BP18_126 from "./BP18-126";
import c_BP18_T01 from "./BP18-T01";
import c_BP18_T02 from "./BP18-T02";
import c_BP18_T03 from "./BP18-T03";
import c_BP18_T04 from "./BP18-T04";
import c_BP18_T05 from "./BP18-T05";
import c_BP18_T06 from "./BP18-T06";
import c_BP18_T07 from "./BP18-T07";
import c_BP18_T08 from "./BP18-T08";
import c_BP18_T09 from "./BP18-T09";
import c_BP18_T10 from "./BP18-T10";

/**
 * Card scripts of BP18, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP18_SCRIPTS: ScriptRegistry = {
  "BP18-001": c_BP18_001,
  "BP18-002": c_BP18_002,
  "BP18-003": c_BP18_003,
  "BP18-004": c_BP18_004,
  "BP18-005": c_BP18_005,
  "BP18-006": c_BP18_006,
  "BP18-007": c_BP18_007,
  "BP18-008": c_BP18_008,
  "BP18-009": c_BP18_009,
  "BP18-010": c_BP18_010,
  "BP18-011": c_BP18_011,
  "BP18-012": c_BP18_012,
  "BP18-013": c_BP18_013,
  "BP18-014": c_BP18_014,
  "BP18-015": c_BP18_015,
  "BP18-016": c_BP18_016,
  "BP18-017": c_BP18_017,
  "BP18-018": c_BP18_018,
  "BP18-019": c_BP18_019,
  "BP18-020": c_BP18_020,
  "BP18-021": c_BP18_021,
  "BP18-022": c_BP18_022,
  "BP18-023": c_BP18_023,
  "BP18-024": c_BP18_024,
  "BP18-025": c_BP18_025,
  "BP18-026": c_BP18_026,
  "BP18-027": c_BP18_027,
  "BP18-028": c_BP18_028,
  "BP18-029": c_BP18_029,
  "BP18-030": c_BP18_030,
  "BP18-031": c_BP18_031,
  "BP18-032": c_BP18_032,
  "BP18-033": c_BP18_033,
  "BP18-034": c_BP18_034,
  "BP18-035": c_BP18_035,
  "BP18-036": c_BP18_036,
  "BP18-037": c_BP18_037,
  "BP18-038": c_BP18_038,
  "BP18-039": c_BP18_039,
  "BP18-040": c_BP18_040,
  "BP18-041": c_BP18_041,
  "BP18-042": c_BP18_042,
  "BP18-043": c_BP18_043,
  "BP18-044": c_BP18_044,
  "BP18-045": c_BP18_045,
  "BP18-046": c_BP18_046,
  "BP18-047": c_BP18_047,
  "BP18-048": c_BP18_048,
  "BP18-049": c_BP18_049,
  "BP18-050": c_BP18_050,
  "BP18-051": c_BP18_051,
  "BP18-052": c_BP18_052,
  "BP18-053": c_BP18_053,
  "BP18-054": c_BP18_054,
  "BP18-055": c_BP18_055,
  "BP18-056": c_BP18_056,
  "BP18-057": c_BP18_057,
  "BP18-058": c_BP18_058,
  "BP18-059": c_BP18_059,
  "BP18-060": c_BP18_060,
  "BP18-061": c_BP18_061,
  "BP18-062": c_BP18_062,
  "BP18-063": c_BP18_063,
  "BP18-064": c_BP18_064,
  "BP18-065": c_BP18_065,
  "BP18-066": c_BP18_066,
  "BP18-067": c_BP18_067,
  "BP18-068": c_BP18_068,
  "BP18-069": c_BP18_069,
  "BP18-070": c_BP18_070,
  "BP18-071": c_BP18_071,
  "BP18-072": c_BP18_072,
  "BP18-073": c_BP18_073,
  "BP18-074": c_BP18_074,
  "BP18-075": c_BP18_075,
  "BP18-076": c_BP18_076,
  "BP18-077": c_BP18_077,
  "BP18-078": c_BP18_078,
  "BP18-079": c_BP18_079,
  "BP18-080": c_BP18_080,
  "BP18-081": c_BP18_081,
  "BP18-082": c_BP18_082,
  "BP18-083": c_BP18_083,
  "BP18-084": c_BP18_084,
  "BP18-085": c_BP18_085,
  "BP18-086": c_BP18_086,
  "BP18-087": c_BP18_087,
  "BP18-088": c_BP18_088,
  "BP18-089": c_BP18_089,
  "BP18-090": c_BP18_090,
  "BP18-091": c_BP18_091,
  "BP18-092": c_BP18_092,
  "BP18-093": c_BP18_093,
  "BP18-094": c_BP18_094,
  "BP18-095": c_BP18_095,
  "BP18-096": c_BP18_096,
  "BP18-097": c_BP18_097,
  "BP18-098": c_BP18_098,
  "BP18-099": c_BP18_099,
  "BP18-100": c_BP18_100,
  "BP18-101": c_BP18_101,
  "BP18-102": c_BP18_102,
  "BP18-103": c_BP18_103,
  "BP18-104": c_BP18_104,
  "BP18-105": c_BP18_105,
  "BP18-106": c_BP18_106,
  "BP18-107": c_BP18_107,
  "BP18-108": c_BP18_108,
  "BP18-109": c_BP18_109,
  "BP18-110": c_BP18_110,
  "BP18-111": c_BP18_111,
  "BP18-112": c_BP18_112,
  "BP18-113": c_BP18_113,
  "BP18-114": c_BP18_114,
  "BP18-115": c_BP18_115,
  "BP18-116": c_BP18_116,
  "BP18-117": c_BP18_117,
  "BP18-118": c_BP18_118,
  "BP18-119": c_BP18_119,
  "BP18-120": c_BP18_120,
  "BP18-121": c_BP18_121,
  "BP18-123": c_BP18_123,
  "BP18-124": c_BP18_124,
  "BP18-126": c_BP18_126,
  "BP18-T01": c_BP18_T01,
  "BP18-T02": c_BP18_T02,
  "BP18-T03": c_BP18_T03,
  "BP18-T04": c_BP18_T04,
  "BP18-T05": c_BP18_T05,
  "BP18-T06": c_BP18_T06,
  "BP18-T07": c_BP18_T07,
  "BP18-T08": c_BP18_T08,
  "BP18-T09": c_BP18_T09,
  "BP18-T10": c_BP18_T10,
};
