// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD08_011 from "./SD08-011";

/**
 * Card scripts of SD08, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD08_SCRIPTS: ScriptRegistry = {
  "SD08-011": c_SD08_011,
};
