// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SP01_010 from "./SP01-010";
import c_SP01_026 from "./SP01-026";
import c_SP01_032 from "./SP01-032";
import c_SP01_039 from "./SP01-039";
import c_SP01_045 from "./SP01-045";

/**
 * Card scripts of SP01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SP01_SCRIPTS: ScriptRegistry = {
  "SP01-010": c_SP01_010,
  "SP01-026": c_SP01_026,
  "SP01-032": c_SP01_032,
  "SP01-039": c_SP01_039,
  "SP01-045": c_SP01_045,
};
