// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP03_001 from "./BP03-001";
import c_BP03_002 from "./BP03-002";
import c_BP03_003 from "./BP03-003";
import c_BP03_004 from "./BP03-004";
import c_BP03_005 from "./BP03-005";
import c_BP03_006 from "./BP03-006";
import c_BP03_007 from "./BP03-007";
import c_BP03_008 from "./BP03-008";
import c_BP03_009 from "./BP03-009";
import c_BP03_010 from "./BP03-010";
import c_BP03_011 from "./BP03-011";
import c_BP03_012 from "./BP03-012";
import c_BP03_013 from "./BP03-013";
import c_BP03_014 from "./BP03-014";
import c_BP03_015 from "./BP03-015";
import c_BP03_016 from "./BP03-016";
import c_BP03_017 from "./BP03-017";
import c_BP03_018 from "./BP03-018";
import c_BP03_020 from "./BP03-020";
import c_BP03_021 from "./BP03-021";
import c_BP03_022 from "./BP03-022";
import c_BP03_023 from "./BP03-023";
import c_BP03_024 from "./BP03-024";
import c_BP03_025 from "./BP03-025";
import c_BP03_027 from "./BP03-027";
import c_BP03_028 from "./BP03-028";
import c_BP03_029 from "./BP03-029";
import c_BP03_030 from "./BP03-030";
import c_BP03_032 from "./BP03-032";
import c_BP03_033 from "./BP03-033";
import c_BP03_034 from "./BP03-034";
import c_BP03_035 from "./BP03-035";
import c_BP03_036 from "./BP03-036";
import c_BP03_037 from "./BP03-037";
import c_BP03_038 from "./BP03-038";
import c_BP03_039 from "./BP03-039";
import c_BP03_040 from "./BP03-040";
import c_BP03_041 from "./BP03-041";
import c_BP03_042 from "./BP03-042";
import c_BP03_043 from "./BP03-043";
import c_BP03_044 from "./BP03-044";
import c_BP03_045 from "./BP03-045";
import c_BP03_046 from "./BP03-046";
import c_BP03_047 from "./BP03-047";
import c_BP03_048 from "./BP03-048";
import c_BP03_049 from "./BP03-049";
import c_BP03_050 from "./BP03-050";
import c_BP03_051 from "./BP03-051";
import c_BP03_052 from "./BP03-052";
import c_BP03_053 from "./BP03-053";
import c_BP03_054 from "./BP03-054";
import c_BP03_055 from "./BP03-055";
import c_BP03_056 from "./BP03-056";
import c_BP03_057 from "./BP03-057";
import c_BP03_058 from "./BP03-058";
import c_BP03_059 from "./BP03-059";
import c_BP03_060 from "./BP03-060";
import c_BP03_061 from "./BP03-061";
import c_BP03_062 from "./BP03-062";
import c_BP03_063 from "./BP03-063";
import c_BP03_064 from "./BP03-064";
import c_BP03_065 from "./BP03-065";
import c_BP03_066 from "./BP03-066";
import c_BP03_067 from "./BP03-067";
import c_BP03_068 from "./BP03-068";
import c_BP03_069 from "./BP03-069";
import c_BP03_070 from "./BP03-070";
import c_BP03_071 from "./BP03-071";
import c_BP03_072 from "./BP03-072";
import c_BP03_073 from "./BP03-073";
import c_BP03_074 from "./BP03-074";
import c_BP03_075 from "./BP03-075";
import c_BP03_076 from "./BP03-076";
import c_BP03_077 from "./BP03-077";
import c_BP03_078 from "./BP03-078";
import c_BP03_079 from "./BP03-079";
import c_BP03_080 from "./BP03-080";
import c_BP03_081 from "./BP03-081";
import c_BP03_082 from "./BP03-082";
import c_BP03_083 from "./BP03-083";
import c_BP03_084 from "./BP03-084";
import c_BP03_085 from "./BP03-085";
import c_BP03_086 from "./BP03-086";
import c_BP03_087 from "./BP03-087";
import c_BP03_088 from "./BP03-088";
import c_BP03_089 from "./BP03-089";
import c_BP03_090 from "./BP03-090";
import c_BP03_091 from "./BP03-091";
import c_BP03_092 from "./BP03-092";
import c_BP03_093 from "./BP03-093";
import c_BP03_094 from "./BP03-094";
import c_BP03_095 from "./BP03-095";
import c_BP03_096 from "./BP03-096";
import c_BP03_097 from "./BP03-097";
import c_BP03_098 from "./BP03-098";
import c_BP03_099 from "./BP03-099";
import c_BP03_100 from "./BP03-100";
import c_BP03_101 from "./BP03-101";
import c_BP03_102 from "./BP03-102";
import c_BP03_103 from "./BP03-103";
import c_BP03_104 from "./BP03-104";
import c_BP03_105 from "./BP03-105";
import c_BP03_106 from "./BP03-106";
import c_BP03_107 from "./BP03-107";
import c_BP03_108 from "./BP03-108";
import c_BP03_109 from "./BP03-109";
import c_BP03_110 from "./BP03-110";
import c_BP03_111 from "./BP03-111";
import c_BP03_112 from "./BP03-112";
import c_BP03_113 from "./BP03-113";
import c_BP03_114 from "./BP03-114";
import c_BP03_115 from "./BP03-115";
import c_BP03_116 from "./BP03-116";
import c_BP03_117 from "./BP03-117";
import c_BP03_118 from "./BP03-118";
import c_BP03_119 from "./BP03-119";
import c_BP03_120 from "./BP03-120";
import c_BP03_121 from "./BP03-121";
import c_BP03_T06 from "./BP03-T06";

/**
 * Card scripts of BP03, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP03_SCRIPTS: ScriptRegistry = {
  "BP03-001": c_BP03_001,
  "BP03-002": c_BP03_002,
  "BP03-003": c_BP03_003,
  "BP03-004": c_BP03_004,
  "BP03-005": c_BP03_005,
  "BP03-006": c_BP03_006,
  "BP03-007": c_BP03_007,
  "BP03-008": c_BP03_008,
  "BP03-009": c_BP03_009,
  "BP03-010": c_BP03_010,
  "BP03-011": c_BP03_011,
  "BP03-012": c_BP03_012,
  "BP03-013": c_BP03_013,
  "BP03-014": c_BP03_014,
  "BP03-015": c_BP03_015,
  "BP03-016": c_BP03_016,
  "BP03-017": c_BP03_017,
  "BP03-018": c_BP03_018,
  "BP03-020": c_BP03_020,
  "BP03-021": c_BP03_021,
  "BP03-022": c_BP03_022,
  "BP03-023": c_BP03_023,
  "BP03-024": c_BP03_024,
  "BP03-025": c_BP03_025,
  "BP03-027": c_BP03_027,
  "BP03-028": c_BP03_028,
  "BP03-029": c_BP03_029,
  "BP03-030": c_BP03_030,
  "BP03-032": c_BP03_032,
  "BP03-033": c_BP03_033,
  "BP03-034": c_BP03_034,
  "BP03-035": c_BP03_035,
  "BP03-036": c_BP03_036,
  "BP03-037": c_BP03_037,
  "BP03-038": c_BP03_038,
  "BP03-039": c_BP03_039,
  "BP03-040": c_BP03_040,
  "BP03-041": c_BP03_041,
  "BP03-042": c_BP03_042,
  "BP03-043": c_BP03_043,
  "BP03-044": c_BP03_044,
  "BP03-045": c_BP03_045,
  "BP03-046": c_BP03_046,
  "BP03-047": c_BP03_047,
  "BP03-048": c_BP03_048,
  "BP03-049": c_BP03_049,
  "BP03-050": c_BP03_050,
  "BP03-051": c_BP03_051,
  "BP03-052": c_BP03_052,
  "BP03-053": c_BP03_053,
  "BP03-054": c_BP03_054,
  "BP03-055": c_BP03_055,
  "BP03-056": c_BP03_056,
  "BP03-057": c_BP03_057,
  "BP03-058": c_BP03_058,
  "BP03-059": c_BP03_059,
  "BP03-060": c_BP03_060,
  "BP03-061": c_BP03_061,
  "BP03-062": c_BP03_062,
  "BP03-063": c_BP03_063,
  "BP03-064": c_BP03_064,
  "BP03-065": c_BP03_065,
  "BP03-066": c_BP03_066,
  "BP03-067": c_BP03_067,
  "BP03-068": c_BP03_068,
  "BP03-069": c_BP03_069,
  "BP03-070": c_BP03_070,
  "BP03-071": c_BP03_071,
  "BP03-072": c_BP03_072,
  "BP03-073": c_BP03_073,
  "BP03-074": c_BP03_074,
  "BP03-075": c_BP03_075,
  "BP03-076": c_BP03_076,
  "BP03-077": c_BP03_077,
  "BP03-078": c_BP03_078,
  "BP03-079": c_BP03_079,
  "BP03-080": c_BP03_080,
  "BP03-081": c_BP03_081,
  "BP03-082": c_BP03_082,
  "BP03-083": c_BP03_083,
  "BP03-084": c_BP03_084,
  "BP03-085": c_BP03_085,
  "BP03-086": c_BP03_086,
  "BP03-087": c_BP03_087,
  "BP03-088": c_BP03_088,
  "BP03-089": c_BP03_089,
  "BP03-090": c_BP03_090,
  "BP03-091": c_BP03_091,
  "BP03-092": c_BP03_092,
  "BP03-093": c_BP03_093,
  "BP03-094": c_BP03_094,
  "BP03-095": c_BP03_095,
  "BP03-096": c_BP03_096,
  "BP03-097": c_BP03_097,
  "BP03-098": c_BP03_098,
  "BP03-099": c_BP03_099,
  "BP03-100": c_BP03_100,
  "BP03-101": c_BP03_101,
  "BP03-102": c_BP03_102,
  "BP03-103": c_BP03_103,
  "BP03-104": c_BP03_104,
  "BP03-105": c_BP03_105,
  "BP03-106": c_BP03_106,
  "BP03-107": c_BP03_107,
  "BP03-108": c_BP03_108,
  "BP03-109": c_BP03_109,
  "BP03-110": c_BP03_110,
  "BP03-111": c_BP03_111,
  "BP03-112": c_BP03_112,
  "BP03-113": c_BP03_113,
  "BP03-114": c_BP03_114,
  "BP03-115": c_BP03_115,
  "BP03-116": c_BP03_116,
  "BP03-117": c_BP03_117,
  "BP03-118": c_BP03_118,
  "BP03-119": c_BP03_119,
  "BP03-120": c_BP03_120,
  "BP03-121": c_BP03_121,
  "BP03-T06": c_BP03_T06,
};
