// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP14_001 from "./BP14-001";
import c_BP14_002 from "./BP14-002";
import c_BP14_003 from "./BP14-003";
import c_BP14_004 from "./BP14-004";
import c_BP14_005 from "./BP14-005";
import c_BP14_006 from "./BP14-006";
import c_BP14_007 from "./BP14-007";
import c_BP14_008 from "./BP14-008";
import c_BP14_009 from "./BP14-009";
import c_BP14_010 from "./BP14-010";
import c_BP14_011 from "./BP14-011";
import c_BP14_012 from "./BP14-012";
import c_BP14_013 from "./BP14-013";
import c_BP14_014 from "./BP14-014";
import c_BP14_015 from "./BP14-015";
import c_BP14_016 from "./BP14-016";
import c_BP14_017 from "./BP14-017";
import c_BP14_018 from "./BP14-018";
import c_BP14_019 from "./BP14-019";
import c_BP14_020 from "./BP14-020";
import c_BP14_021 from "./BP14-021";
import c_BP14_022 from "./BP14-022";
import c_BP14_023 from "./BP14-023";
import c_BP14_024 from "./BP14-024";
import c_BP14_025 from "./BP14-025";
import c_BP14_026 from "./BP14-026";
import c_BP14_027 from "./BP14-027";
import c_BP14_028 from "./BP14-028";
import c_BP14_029 from "./BP14-029";
import c_BP14_030 from "./BP14-030";
import c_BP14_031 from "./BP14-031";
import c_BP14_032 from "./BP14-032";
import c_BP14_033 from "./BP14-033";
import c_BP14_034 from "./BP14-034";
import c_BP14_035 from "./BP14-035";
import c_BP14_036 from "./BP14-036";
import c_BP14_037 from "./BP14-037";
import c_BP14_038 from "./BP14-038";
import c_BP14_039 from "./BP14-039";
import c_BP14_040 from "./BP14-040";
import c_BP14_041 from "./BP14-041";
import c_BP14_042 from "./BP14-042";
import c_BP14_043 from "./BP14-043";
import c_BP14_044 from "./BP14-044";
import c_BP14_045 from "./BP14-045";
import c_BP14_046 from "./BP14-046";
import c_BP14_047 from "./BP14-047";
import c_BP14_048 from "./BP14-048";
import c_BP14_049 from "./BP14-049";
import c_BP14_050 from "./BP14-050";
import c_BP14_051 from "./BP14-051";
import c_BP14_052 from "./BP14-052";
import c_BP14_053 from "./BP14-053";
import c_BP14_054 from "./BP14-054";
import c_BP14_055 from "./BP14-055";
import c_BP14_056 from "./BP14-056";
import c_BP14_057 from "./BP14-057";
import c_BP14_058 from "./BP14-058";
import c_BP14_059 from "./BP14-059";
import c_BP14_060 from "./BP14-060";
import c_BP14_061 from "./BP14-061";
import c_BP14_062 from "./BP14-062";
import c_BP14_063 from "./BP14-063";
import c_BP14_064 from "./BP14-064";
import c_BP14_065 from "./BP14-065";
import c_BP14_066 from "./BP14-066";
import c_BP14_067 from "./BP14-067";
import c_BP14_068 from "./BP14-068";
import c_BP14_069 from "./BP14-069";
import c_BP14_070 from "./BP14-070";
import c_BP14_071 from "./BP14-071";
import c_BP14_072 from "./BP14-072";
import c_BP14_073 from "./BP14-073";
import c_BP14_074 from "./BP14-074";
import c_BP14_075 from "./BP14-075";
import c_BP14_076 from "./BP14-076";
import c_BP14_077 from "./BP14-077";
import c_BP14_078 from "./BP14-078";
import c_BP14_079 from "./BP14-079";
import c_BP14_080 from "./BP14-080";
import c_BP14_081 from "./BP14-081";
import c_BP14_082 from "./BP14-082";
import c_BP14_083 from "./BP14-083";
import c_BP14_084 from "./BP14-084";
import c_BP14_085 from "./BP14-085";
import c_BP14_086 from "./BP14-086";
import c_BP14_087 from "./BP14-087";
import c_BP14_088 from "./BP14-088";
import c_BP14_089 from "./BP14-089";
import c_BP14_090 from "./BP14-090";
import c_BP14_091 from "./BP14-091";
import c_BP14_092 from "./BP14-092";
import c_BP14_093 from "./BP14-093";
import c_BP14_094 from "./BP14-094";
import c_BP14_095 from "./BP14-095";
import c_BP14_096 from "./BP14-096";
import c_BP14_097 from "./BP14-097";
import c_BP14_098 from "./BP14-098";
import c_BP14_099 from "./BP14-099";
import c_BP14_100 from "./BP14-100";
import c_BP14_101 from "./BP14-101";
import c_BP14_102 from "./BP14-102";
import c_BP14_103 from "./BP14-103";
import c_BP14_104 from "./BP14-104";
import c_BP14_105 from "./BP14-105";
import c_BP14_106 from "./BP14-106";
import c_BP14_107 from "./BP14-107";
import c_BP14_108 from "./BP14-108";
import c_BP14_109 from "./BP14-109";
import c_BP14_110 from "./BP14-110";
import c_BP14_111 from "./BP14-111";
import c_BP14_112 from "./BP14-112";
import c_BP14_113 from "./BP14-113";
import c_BP14_114 from "./BP14-114";
import c_BP14_115 from "./BP14-115";
import c_BP14_116 from "./BP14-116";
import c_BP14_117 from "./BP14-117";
import c_BP14_118 from "./BP14-118";
import c_BP14_119 from "./BP14-119";
import c_BP14_T01 from "./BP14-T01";
import c_BP14_T02 from "./BP14-T02";
import c_BP14_T03 from "./BP14-T03";
import c_BP14_T04 from "./BP14-T04";
import c_BP14_T05 from "./BP14-T05";
import c_BP14_T06 from "./BP14-T06";
import c_BP14_T07 from "./BP14-T07";

/**
 * Card scripts of BP14, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP14_SCRIPTS: ScriptRegistry = {
  "BP14-001": c_BP14_001,
  "BP14-002": c_BP14_002,
  "BP14-003": c_BP14_003,
  "BP14-004": c_BP14_004,
  "BP14-005": c_BP14_005,
  "BP14-006": c_BP14_006,
  "BP14-007": c_BP14_007,
  "BP14-008": c_BP14_008,
  "BP14-009": c_BP14_009,
  "BP14-010": c_BP14_010,
  "BP14-011": c_BP14_011,
  "BP14-012": c_BP14_012,
  "BP14-013": c_BP14_013,
  "BP14-014": c_BP14_014,
  "BP14-015": c_BP14_015,
  "BP14-016": c_BP14_016,
  "BP14-017": c_BP14_017,
  "BP14-018": c_BP14_018,
  "BP14-019": c_BP14_019,
  "BP14-020": c_BP14_020,
  "BP14-021": c_BP14_021,
  "BP14-022": c_BP14_022,
  "BP14-023": c_BP14_023,
  "BP14-024": c_BP14_024,
  "BP14-025": c_BP14_025,
  "BP14-026": c_BP14_026,
  "BP14-027": c_BP14_027,
  "BP14-028": c_BP14_028,
  "BP14-029": c_BP14_029,
  "BP14-030": c_BP14_030,
  "BP14-031": c_BP14_031,
  "BP14-032": c_BP14_032,
  "BP14-033": c_BP14_033,
  "BP14-034": c_BP14_034,
  "BP14-035": c_BP14_035,
  "BP14-036": c_BP14_036,
  "BP14-037": c_BP14_037,
  "BP14-038": c_BP14_038,
  "BP14-039": c_BP14_039,
  "BP14-040": c_BP14_040,
  "BP14-041": c_BP14_041,
  "BP14-042": c_BP14_042,
  "BP14-043": c_BP14_043,
  "BP14-044": c_BP14_044,
  "BP14-045": c_BP14_045,
  "BP14-046": c_BP14_046,
  "BP14-047": c_BP14_047,
  "BP14-048": c_BP14_048,
  "BP14-049": c_BP14_049,
  "BP14-050": c_BP14_050,
  "BP14-051": c_BP14_051,
  "BP14-052": c_BP14_052,
  "BP14-053": c_BP14_053,
  "BP14-054": c_BP14_054,
  "BP14-055": c_BP14_055,
  "BP14-056": c_BP14_056,
  "BP14-057": c_BP14_057,
  "BP14-058": c_BP14_058,
  "BP14-059": c_BP14_059,
  "BP14-060": c_BP14_060,
  "BP14-061": c_BP14_061,
  "BP14-062": c_BP14_062,
  "BP14-063": c_BP14_063,
  "BP14-064": c_BP14_064,
  "BP14-065": c_BP14_065,
  "BP14-066": c_BP14_066,
  "BP14-067": c_BP14_067,
  "BP14-068": c_BP14_068,
  "BP14-069": c_BP14_069,
  "BP14-070": c_BP14_070,
  "BP14-071": c_BP14_071,
  "BP14-072": c_BP14_072,
  "BP14-073": c_BP14_073,
  "BP14-074": c_BP14_074,
  "BP14-075": c_BP14_075,
  "BP14-076": c_BP14_076,
  "BP14-077": c_BP14_077,
  "BP14-078": c_BP14_078,
  "BP14-079": c_BP14_079,
  "BP14-080": c_BP14_080,
  "BP14-081": c_BP14_081,
  "BP14-082": c_BP14_082,
  "BP14-083": c_BP14_083,
  "BP14-084": c_BP14_084,
  "BP14-085": c_BP14_085,
  "BP14-086": c_BP14_086,
  "BP14-087": c_BP14_087,
  "BP14-088": c_BP14_088,
  "BP14-089": c_BP14_089,
  "BP14-090": c_BP14_090,
  "BP14-091": c_BP14_091,
  "BP14-092": c_BP14_092,
  "BP14-093": c_BP14_093,
  "BP14-094": c_BP14_094,
  "BP14-095": c_BP14_095,
  "BP14-096": c_BP14_096,
  "BP14-097": c_BP14_097,
  "BP14-098": c_BP14_098,
  "BP14-099": c_BP14_099,
  "BP14-100": c_BP14_100,
  "BP14-101": c_BP14_101,
  "BP14-102": c_BP14_102,
  "BP14-103": c_BP14_103,
  "BP14-104": c_BP14_104,
  "BP14-105": c_BP14_105,
  "BP14-106": c_BP14_106,
  "BP14-107": c_BP14_107,
  "BP14-108": c_BP14_108,
  "BP14-109": c_BP14_109,
  "BP14-110": c_BP14_110,
  "BP14-111": c_BP14_111,
  "BP14-112": c_BP14_112,
  "BP14-113": c_BP14_113,
  "BP14-114": c_BP14_114,
  "BP14-115": c_BP14_115,
  "BP14-116": c_BP14_116,
  "BP14-117": c_BP14_117,
  "BP14-118": c_BP14_118,
  "BP14-119": c_BP14_119,
  "BP14-T01": c_BP14_T01,
  "BP14-T02": c_BP14_T02,
  "BP14-T03": c_BP14_T03,
  "BP14-T04": c_BP14_T04,
  "BP14-T05": c_BP14_T05,
  "BP14-T06": c_BP14_T06,
  "BP14-T07": c_BP14_T07,
};
