// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP06_001 from "./BP06-001";
import c_BP06_002 from "./BP06-002";
import c_BP06_003 from "./BP06-003";
import c_BP06_004 from "./BP06-004";
import c_BP06_005 from "./BP06-005";
import c_BP06_006 from "./BP06-006";
import c_BP06_007 from "./BP06-007";
import c_BP06_008 from "./BP06-008";
import c_BP06_009 from "./BP06-009";
import c_BP06_010 from "./BP06-010";
import c_BP06_011 from "./BP06-011";
import c_BP06_012 from "./BP06-012";
import c_BP06_013 from "./BP06-013";
import c_BP06_014 from "./BP06-014";
import c_BP06_015 from "./BP06-015";
import c_BP06_016 from "./BP06-016";
import c_BP06_017 from "./BP06-017";
import c_BP06_018 from "./BP06-018";
import c_BP06_019 from "./BP06-019";
import c_BP06_020 from "./BP06-020";
import c_BP06_021 from "./BP06-021";
import c_BP06_022 from "./BP06-022";
import c_BP06_023 from "./BP06-023";
import c_BP06_024 from "./BP06-024";
import c_BP06_025 from "./BP06-025";
import c_BP06_026 from "./BP06-026";
import c_BP06_027 from "./BP06-027";
import c_BP06_028 from "./BP06-028";
import c_BP06_029 from "./BP06-029";
import c_BP06_031 from "./BP06-031";
import c_BP06_032 from "./BP06-032";
import c_BP06_033 from "./BP06-033";
import c_BP06_034 from "./BP06-034";
import c_BP06_035 from "./BP06-035";
import c_BP06_036 from "./BP06-036";
import c_BP06_037 from "./BP06-037";
import c_BP06_038 from "./BP06-038";
import c_BP06_039 from "./BP06-039";
import c_BP06_040 from "./BP06-040";
import c_BP06_041 from "./BP06-041";
import c_BP06_042 from "./BP06-042";
import c_BP06_043 from "./BP06-043";
import c_BP06_044 from "./BP06-044";
import c_BP06_045 from "./BP06-045";
import c_BP06_046 from "./BP06-046";
import c_BP06_047 from "./BP06-047";
import c_BP06_048 from "./BP06-048";
import c_BP06_049 from "./BP06-049";
import c_BP06_050 from "./BP06-050";
import c_BP06_051 from "./BP06-051";
import c_BP06_052 from "./BP06-052";
import c_BP06_053 from "./BP06-053";
import c_BP06_054 from "./BP06-054";
import c_BP06_055 from "./BP06-055";
import c_BP06_056 from "./BP06-056";
import c_BP06_057 from "./BP06-057";
import c_BP06_058 from "./BP06-058";
import c_BP06_059 from "./BP06-059";
import c_BP06_060 from "./BP06-060";
import c_BP06_061 from "./BP06-061";
import c_BP06_062 from "./BP06-062";
import c_BP06_063 from "./BP06-063";
import c_BP06_064 from "./BP06-064";
import c_BP06_065 from "./BP06-065";
import c_BP06_066 from "./BP06-066";
import c_BP06_067 from "./BP06-067";
import c_BP06_068 from "./BP06-068";
import c_BP06_069 from "./BP06-069";
import c_BP06_070 from "./BP06-070";
import c_BP06_071 from "./BP06-071";
import c_BP06_072 from "./BP06-072";
import c_BP06_073 from "./BP06-073";
import c_BP06_074 from "./BP06-074";
import c_BP06_075 from "./BP06-075";
import c_BP06_076 from "./BP06-076";
import c_BP06_077 from "./BP06-077";
import c_BP06_078 from "./BP06-078";
import c_BP06_079 from "./BP06-079";
import c_BP06_080 from "./BP06-080";
import c_BP06_081 from "./BP06-081";
import c_BP06_082 from "./BP06-082";
import c_BP06_083 from "./BP06-083";
import c_BP06_084 from "./BP06-084";
import c_BP06_085 from "./BP06-085";
import c_BP06_086 from "./BP06-086";
import c_BP06_087 from "./BP06-087";
import c_BP06_088 from "./BP06-088";
import c_BP06_089 from "./BP06-089";
import c_BP06_090 from "./BP06-090";
import c_BP06_091 from "./BP06-091";
import c_BP06_092 from "./BP06-092";
import c_BP06_093 from "./BP06-093";
import c_BP06_094 from "./BP06-094";
import c_BP06_095 from "./BP06-095";
import c_BP06_096 from "./BP06-096";
import c_BP06_097 from "./BP06-097";
import c_BP06_098 from "./BP06-098";
import c_BP06_099 from "./BP06-099";
import c_BP06_100 from "./BP06-100";
import c_BP06_101 from "./BP06-101";
import c_BP06_102 from "./BP06-102";
import c_BP06_103 from "./BP06-103";
import c_BP06_104 from "./BP06-104";
import c_BP06_105 from "./BP06-105";
import c_BP06_106 from "./BP06-106";
import c_BP06_107 from "./BP06-107";
import c_BP06_108 from "./BP06-108";
import c_BP06_109 from "./BP06-109";
import c_BP06_110 from "./BP06-110";
import c_BP06_111 from "./BP06-111";
import c_BP06_112 from "./BP06-112";
import c_BP06_113 from "./BP06-113";
import c_BP06_114 from "./BP06-114";
import c_BP06_115 from "./BP06-115";
import c_BP06_116 from "./BP06-116";
import c_BP06_117 from "./BP06-117";
import c_BP06_118 from "./BP06-118";
import c_BP06_119 from "./BP06-119";
import c_BP06_120 from "./BP06-120";
import c_BP06_121 from "./BP06-121";
import c_BP06_T01 from "./BP06-T01";
import c_BP06_T02 from "./BP06-T02";
import c_BP06_T03 from "./BP06-T03";

/**
 * Card scripts of BP06, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP06_SCRIPTS: ScriptRegistry = {
  "BP06-001": c_BP06_001,
  "BP06-002": c_BP06_002,
  "BP06-003": c_BP06_003,
  "BP06-004": c_BP06_004,
  "BP06-005": c_BP06_005,
  "BP06-006": c_BP06_006,
  "BP06-007": c_BP06_007,
  "BP06-008": c_BP06_008,
  "BP06-009": c_BP06_009,
  "BP06-010": c_BP06_010,
  "BP06-011": c_BP06_011,
  "BP06-012": c_BP06_012,
  "BP06-013": c_BP06_013,
  "BP06-014": c_BP06_014,
  "BP06-015": c_BP06_015,
  "BP06-016": c_BP06_016,
  "BP06-017": c_BP06_017,
  "BP06-018": c_BP06_018,
  "BP06-019": c_BP06_019,
  "BP06-020": c_BP06_020,
  "BP06-021": c_BP06_021,
  "BP06-022": c_BP06_022,
  "BP06-023": c_BP06_023,
  "BP06-024": c_BP06_024,
  "BP06-025": c_BP06_025,
  "BP06-026": c_BP06_026,
  "BP06-027": c_BP06_027,
  "BP06-028": c_BP06_028,
  "BP06-029": c_BP06_029,
  "BP06-031": c_BP06_031,
  "BP06-032": c_BP06_032,
  "BP06-033": c_BP06_033,
  "BP06-034": c_BP06_034,
  "BP06-035": c_BP06_035,
  "BP06-036": c_BP06_036,
  "BP06-037": c_BP06_037,
  "BP06-038": c_BP06_038,
  "BP06-039": c_BP06_039,
  "BP06-040": c_BP06_040,
  "BP06-041": c_BP06_041,
  "BP06-042": c_BP06_042,
  "BP06-043": c_BP06_043,
  "BP06-044": c_BP06_044,
  "BP06-045": c_BP06_045,
  "BP06-046": c_BP06_046,
  "BP06-047": c_BP06_047,
  "BP06-048": c_BP06_048,
  "BP06-049": c_BP06_049,
  "BP06-050": c_BP06_050,
  "BP06-051": c_BP06_051,
  "BP06-052": c_BP06_052,
  "BP06-053": c_BP06_053,
  "BP06-054": c_BP06_054,
  "BP06-055": c_BP06_055,
  "BP06-056": c_BP06_056,
  "BP06-057": c_BP06_057,
  "BP06-058": c_BP06_058,
  "BP06-059": c_BP06_059,
  "BP06-060": c_BP06_060,
  "BP06-061": c_BP06_061,
  "BP06-062": c_BP06_062,
  "BP06-063": c_BP06_063,
  "BP06-064": c_BP06_064,
  "BP06-065": c_BP06_065,
  "BP06-066": c_BP06_066,
  "BP06-067": c_BP06_067,
  "BP06-068": c_BP06_068,
  "BP06-069": c_BP06_069,
  "BP06-070": c_BP06_070,
  "BP06-071": c_BP06_071,
  "BP06-072": c_BP06_072,
  "BP06-073": c_BP06_073,
  "BP06-074": c_BP06_074,
  "BP06-075": c_BP06_075,
  "BP06-076": c_BP06_076,
  "BP06-077": c_BP06_077,
  "BP06-078": c_BP06_078,
  "BP06-079": c_BP06_079,
  "BP06-080": c_BP06_080,
  "BP06-081": c_BP06_081,
  "BP06-082": c_BP06_082,
  "BP06-083": c_BP06_083,
  "BP06-084": c_BP06_084,
  "BP06-085": c_BP06_085,
  "BP06-086": c_BP06_086,
  "BP06-087": c_BP06_087,
  "BP06-088": c_BP06_088,
  "BP06-089": c_BP06_089,
  "BP06-090": c_BP06_090,
  "BP06-091": c_BP06_091,
  "BP06-092": c_BP06_092,
  "BP06-093": c_BP06_093,
  "BP06-094": c_BP06_094,
  "BP06-095": c_BP06_095,
  "BP06-096": c_BP06_096,
  "BP06-097": c_BP06_097,
  "BP06-098": c_BP06_098,
  "BP06-099": c_BP06_099,
  "BP06-100": c_BP06_100,
  "BP06-101": c_BP06_101,
  "BP06-102": c_BP06_102,
  "BP06-103": c_BP06_103,
  "BP06-104": c_BP06_104,
  "BP06-105": c_BP06_105,
  "BP06-106": c_BP06_106,
  "BP06-107": c_BP06_107,
  "BP06-108": c_BP06_108,
  "BP06-109": c_BP06_109,
  "BP06-110": c_BP06_110,
  "BP06-111": c_BP06_111,
  "BP06-112": c_BP06_112,
  "BP06-113": c_BP06_113,
  "BP06-114": c_BP06_114,
  "BP06-115": c_BP06_115,
  "BP06-116": c_BP06_116,
  "BP06-117": c_BP06_117,
  "BP06-118": c_BP06_118,
  "BP06-119": c_BP06_119,
  "BP06-120": c_BP06_120,
  "BP06-121": c_BP06_121,
  "BP06-T01": c_BP06_T01,
  "BP06-T02": c_BP06_T02,
  "BP06-T03": c_BP06_T03,
};
