// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD06_001 from "./SD06-001";
import c_SD06_002 from "./SD06-002";
import c_SD06_003 from "./SD06-003";
import c_SD06_004 from "./SD06-004";
import c_SD06_005 from "./SD06-005";
import c_SD06_006 from "./SD06-006";
import c_SD06_009 from "./SD06-009";
import c_SD06_010 from "./SD06-010";
import c_SD06_011 from "./SD06-011";
import c_SD06_012 from "./SD06-012";
import c_SD06_015 from "./SD06-015";
import c_SD06_016 from "./SD06-016";

/**
 * Card scripts of SD06, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD06_SCRIPTS: ScriptRegistry = {
  "SD06-001": c_SD06_001,
  "SD06-002": c_SD06_002,
  "SD06-003": c_SD06_003,
  "SD06-004": c_SD06_004,
  "SD06-005": c_SD06_005,
  "SD06-006": c_SD06_006,
  "SD06-009": c_SD06_009,
  "SD06-010": c_SD06_010,
  "SD06-011": c_SD06_011,
  "SD06-012": c_SD06_012,
  "SD06-015": c_SD06_015,
  "SD06-016": c_SD06_016,
};
