// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CP04_001 from "./CP04-001";
import c_CP04_002 from "./CP04-002";
import c_CP04_003 from "./CP04-003";
import c_CP04_004 from "./CP04-004";
import c_CP04_005 from "./CP04-005";
import c_CP04_006 from "./CP04-006";
import c_CP04_007 from "./CP04-007";
import c_CP04_008 from "./CP04-008";
import c_CP04_009 from "./CP04-009";
import c_CP04_010 from "./CP04-010";
import c_CP04_011 from "./CP04-011";
import c_CP04_012 from "./CP04-012";
import c_CP04_013 from "./CP04-013";
import c_CP04_014 from "./CP04-014";
import c_CP04_015 from "./CP04-015";
import c_CP04_016 from "./CP04-016";
import c_CP04_017 from "./CP04-017";
import c_CP04_018 from "./CP04-018";
import c_CP04_019 from "./CP04-019";
import c_CP04_020 from "./CP04-020";
import c_CP04_021 from "./CP04-021";
import c_CP04_022 from "./CP04-022";
import c_CP04_023 from "./CP04-023";
import c_CP04_024 from "./CP04-024";
import c_CP04_025 from "./CP04-025";
import c_CP04_026 from "./CP04-026";
import c_CP04_027 from "./CP04-027";
import c_CP04_028 from "./CP04-028";
import c_CP04_029 from "./CP04-029";
import c_CP04_030 from "./CP04-030";
import c_CP04_031 from "./CP04-031";
import c_CP04_032 from "./CP04-032";
import c_CP04_033 from "./CP04-033";
import c_CP04_034 from "./CP04-034";
import c_CP04_035 from "./CP04-035";
import c_CP04_036 from "./CP04-036";
import c_CP04_037 from "./CP04-037";
import c_CP04_038 from "./CP04-038";
import c_CP04_039 from "./CP04-039";
import c_CP04_040 from "./CP04-040";
import c_CP04_041 from "./CP04-041";
import c_CP04_042 from "./CP04-042";
import c_CP04_043 from "./CP04-043";
import c_CP04_044 from "./CP04-044";
import c_CP04_045 from "./CP04-045";
import c_CP04_046 from "./CP04-046";
import c_CP04_047 from "./CP04-047";
import c_CP04_048 from "./CP04-048";
import c_CP04_049 from "./CP04-049";
import c_CP04_050 from "./CP04-050";
import c_CP04_051 from "./CP04-051";
import c_CP04_052 from "./CP04-052";
import c_CP04_053 from "./CP04-053";
import c_CP04_054 from "./CP04-054";
import c_CP04_055 from "./CP04-055";
import c_CP04_056 from "./CP04-056";
import c_CP04_057 from "./CP04-057";
import c_CP04_058 from "./CP04-058";
import c_CP04_059 from "./CP04-059";
import c_CP04_060 from "./CP04-060";
import c_CP04_061 from "./CP04-061";
import c_CP04_062 from "./CP04-062";
import c_CP04_063 from "./CP04-063";
import c_CP04_064 from "./CP04-064";
import c_CP04_065 from "./CP04-065";
import c_CP04_066 from "./CP04-066";
import c_CP04_067 from "./CP04-067";
import c_CP04_068 from "./CP04-068";
import c_CP04_069 from "./CP04-069";
import c_CP04_070 from "./CP04-070";
import c_CP04_071 from "./CP04-071";
import c_CP04_072 from "./CP04-072";
import c_CP04_073 from "./CP04-073";
import c_CP04_074 from "./CP04-074";
import c_CP04_075 from "./CP04-075";
import c_CP04_076 from "./CP04-076";
import c_CP04_077 from "./CP04-077";
import c_CP04_078 from "./CP04-078";
import c_CP04_079 from "./CP04-079";
import c_CP04_080 from "./CP04-080";
import c_CP04_081 from "./CP04-081";
import c_CP04_082 from "./CP04-082";
import c_CP04_083 from "./CP04-083";
import c_CP04_084 from "./CP04-084";
import c_CP04_085 from "./CP04-085";
import c_CP04_086 from "./CP04-086";
import c_CP04_087 from "./CP04-087";
import c_CP04_088 from "./CP04-088";
import c_CP04_089 from "./CP04-089";
import c_CP04_090 from "./CP04-090";
import c_CP04_091 from "./CP04-091";
import c_CP04_092 from "./CP04-092";
import c_CP04_093 from "./CP04-093";
import c_CP04_094 from "./CP04-094";
import c_CP04_095 from "./CP04-095";
import c_CP04_096 from "./CP04-096";
import c_CP04_097 from "./CP04-097";
import c_CP04_098 from "./CP04-098";
import c_CP04_099 from "./CP04-099";
import c_CP04_100 from "./CP04-100";
import c_CP04_101 from "./CP04-101";
import c_CP04_102 from "./CP04-102";
import c_CP04_103 from "./CP04-103";
import c_CP04_104 from "./CP04-104";
import c_CP04_105 from "./CP04-105";
import c_CP04_106 from "./CP04-106";
import c_CP04_107 from "./CP04-107";
import c_CP04_108 from "./CP04-108";
import c_CP04_109 from "./CP04-109";
import c_CP04_110 from "./CP04-110";
import c_CP04_111 from "./CP04-111";
import c_CP04_112 from "./CP04-112";
import c_CP04_113 from "./CP04-113";
import c_CP04_114 from "./CP04-114";
import c_CP04_115 from "./CP04-115";
import c_CP04_116 from "./CP04-116";
import c_CP04_117 from "./CP04-117";
import c_CP04_118 from "./CP04-118";
import c_CP04_119 from "./CP04-119";
import c_CP04_T01 from "./CP04-T01";
import c_CP04_T02 from "./CP04-T02";
import c_CP04_T03 from "./CP04-T03";
import c_CP04_T04 from "./CP04-T04";
import c_CP04_T05 from "./CP04-T05";
import c_CP04_T06 from "./CP04-T06";
import c_CP04_T07 from "./CP04-T07";
import c_CP04_T08 from "./CP04-T08";
import c_CP04_T09 from "./CP04-T09";
import c_CP04_T10 from "./CP04-T10";
import c_CP04_T11 from "./CP04-T11";
import c_CP04_T12 from "./CP04-T12";

/**
 * Card scripts of CP04, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CP04_SCRIPTS: ScriptRegistry = {
  "CP04-001": c_CP04_001,
  "CP04-002": c_CP04_002,
  "CP04-003": c_CP04_003,
  "CP04-004": c_CP04_004,
  "CP04-005": c_CP04_005,
  "CP04-006": c_CP04_006,
  "CP04-007": c_CP04_007,
  "CP04-008": c_CP04_008,
  "CP04-009": c_CP04_009,
  "CP04-010": c_CP04_010,
  "CP04-011": c_CP04_011,
  "CP04-012": c_CP04_012,
  "CP04-013": c_CP04_013,
  "CP04-014": c_CP04_014,
  "CP04-015": c_CP04_015,
  "CP04-016": c_CP04_016,
  "CP04-017": c_CP04_017,
  "CP04-018": c_CP04_018,
  "CP04-019": c_CP04_019,
  "CP04-020": c_CP04_020,
  "CP04-021": c_CP04_021,
  "CP04-022": c_CP04_022,
  "CP04-023": c_CP04_023,
  "CP04-024": c_CP04_024,
  "CP04-025": c_CP04_025,
  "CP04-026": c_CP04_026,
  "CP04-027": c_CP04_027,
  "CP04-028": c_CP04_028,
  "CP04-029": c_CP04_029,
  "CP04-030": c_CP04_030,
  "CP04-031": c_CP04_031,
  "CP04-032": c_CP04_032,
  "CP04-033": c_CP04_033,
  "CP04-034": c_CP04_034,
  "CP04-035": c_CP04_035,
  "CP04-036": c_CP04_036,
  "CP04-037": c_CP04_037,
  "CP04-038": c_CP04_038,
  "CP04-039": c_CP04_039,
  "CP04-040": c_CP04_040,
  "CP04-041": c_CP04_041,
  "CP04-042": c_CP04_042,
  "CP04-043": c_CP04_043,
  "CP04-044": c_CP04_044,
  "CP04-045": c_CP04_045,
  "CP04-046": c_CP04_046,
  "CP04-047": c_CP04_047,
  "CP04-048": c_CP04_048,
  "CP04-049": c_CP04_049,
  "CP04-050": c_CP04_050,
  "CP04-051": c_CP04_051,
  "CP04-052": c_CP04_052,
  "CP04-053": c_CP04_053,
  "CP04-054": c_CP04_054,
  "CP04-055": c_CP04_055,
  "CP04-056": c_CP04_056,
  "CP04-057": c_CP04_057,
  "CP04-058": c_CP04_058,
  "CP04-059": c_CP04_059,
  "CP04-060": c_CP04_060,
  "CP04-061": c_CP04_061,
  "CP04-062": c_CP04_062,
  "CP04-063": c_CP04_063,
  "CP04-064": c_CP04_064,
  "CP04-065": c_CP04_065,
  "CP04-066": c_CP04_066,
  "CP04-067": c_CP04_067,
  "CP04-068": c_CP04_068,
  "CP04-069": c_CP04_069,
  "CP04-070": c_CP04_070,
  "CP04-071": c_CP04_071,
  "CP04-072": c_CP04_072,
  "CP04-073": c_CP04_073,
  "CP04-074": c_CP04_074,
  "CP04-075": c_CP04_075,
  "CP04-076": c_CP04_076,
  "CP04-077": c_CP04_077,
  "CP04-078": c_CP04_078,
  "CP04-079": c_CP04_079,
  "CP04-080": c_CP04_080,
  "CP04-081": c_CP04_081,
  "CP04-082": c_CP04_082,
  "CP04-083": c_CP04_083,
  "CP04-084": c_CP04_084,
  "CP04-085": c_CP04_085,
  "CP04-086": c_CP04_086,
  "CP04-087": c_CP04_087,
  "CP04-088": c_CP04_088,
  "CP04-089": c_CP04_089,
  "CP04-090": c_CP04_090,
  "CP04-091": c_CP04_091,
  "CP04-092": c_CP04_092,
  "CP04-093": c_CP04_093,
  "CP04-094": c_CP04_094,
  "CP04-095": c_CP04_095,
  "CP04-096": c_CP04_096,
  "CP04-097": c_CP04_097,
  "CP04-098": c_CP04_098,
  "CP04-099": c_CP04_099,
  "CP04-100": c_CP04_100,
  "CP04-101": c_CP04_101,
  "CP04-102": c_CP04_102,
  "CP04-103": c_CP04_103,
  "CP04-104": c_CP04_104,
  "CP04-105": c_CP04_105,
  "CP04-106": c_CP04_106,
  "CP04-107": c_CP04_107,
  "CP04-108": c_CP04_108,
  "CP04-109": c_CP04_109,
  "CP04-110": c_CP04_110,
  "CP04-111": c_CP04_111,
  "CP04-112": c_CP04_112,
  "CP04-113": c_CP04_113,
  "CP04-114": c_CP04_114,
  "CP04-115": c_CP04_115,
  "CP04-116": c_CP04_116,
  "CP04-117": c_CP04_117,
  "CP04-118": c_CP04_118,
  "CP04-119": c_CP04_119,
  "CP04-T01": c_CP04_T01,
  "CP04-T02": c_CP04_T02,
  "CP04-T03": c_CP04_T03,
  "CP04-T04": c_CP04_T04,
  "CP04-T05": c_CP04_T05,
  "CP04-T06": c_CP04_T06,
  "CP04-T07": c_CP04_T07,
  "CP04-T08": c_CP04_T08,
  "CP04-T09": c_CP04_T09,
  "CP04-T10": c_CP04_T10,
  "CP04-T11": c_CP04_T11,
  "CP04-T12": c_CP04_T12,
};
