// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP16_001 from "./BP16-001";
import c_BP16_002 from "./BP16-002";
import c_BP16_003 from "./BP16-003";
import c_BP16_004 from "./BP16-004";
import c_BP16_005 from "./BP16-005";
import c_BP16_006 from "./BP16-006";
import c_BP16_007 from "./BP16-007";
import c_BP16_008 from "./BP16-008";
import c_BP16_009 from "./BP16-009";
import c_BP16_010 from "./BP16-010";
import c_BP16_011 from "./BP16-011";
import c_BP16_012 from "./BP16-012";
import c_BP16_013 from "./BP16-013";
import c_BP16_014 from "./BP16-014";
import c_BP16_015 from "./BP16-015";
import c_BP16_016 from "./BP16-016";
import c_BP16_017 from "./BP16-017";
import c_BP16_018 from "./BP16-018";
import c_BP16_019 from "./BP16-019";
import c_BP16_020 from "./BP16-020";
import c_BP16_021 from "./BP16-021";
import c_BP16_022 from "./BP16-022";
import c_BP16_023 from "./BP16-023";
import c_BP16_024 from "./BP16-024";
import c_BP16_025 from "./BP16-025";
import c_BP16_026 from "./BP16-026";
import c_BP16_027 from "./BP16-027";
import c_BP16_028 from "./BP16-028";
import c_BP16_029 from "./BP16-029";
import c_BP16_030 from "./BP16-030";
import c_BP16_031 from "./BP16-031";
import c_BP16_032 from "./BP16-032";
import c_BP16_033 from "./BP16-033";
import c_BP16_034 from "./BP16-034";
import c_BP16_035 from "./BP16-035";
import c_BP16_036 from "./BP16-036";
import c_BP16_037 from "./BP16-037";
import c_BP16_038 from "./BP16-038";
import c_BP16_039 from "./BP16-039";
import c_BP16_040 from "./BP16-040";
import c_BP16_041 from "./BP16-041";
import c_BP16_042 from "./BP16-042";
import c_BP16_043 from "./BP16-043";
import c_BP16_044 from "./BP16-044";
import c_BP16_045 from "./BP16-045";
import c_BP16_046 from "./BP16-046";
import c_BP16_047 from "./BP16-047";
import c_BP16_048 from "./BP16-048";
import c_BP16_049 from "./BP16-049";
import c_BP16_050 from "./BP16-050";
import c_BP16_051 from "./BP16-051";
import c_BP16_052 from "./BP16-052";
import c_BP16_053 from "./BP16-053";
import c_BP16_054 from "./BP16-054";
import c_BP16_055 from "./BP16-055";
import c_BP16_056 from "./BP16-056";
import c_BP16_057 from "./BP16-057";
import c_BP16_058 from "./BP16-058";
import c_BP16_059 from "./BP16-059";
import c_BP16_060 from "./BP16-060";
import c_BP16_061 from "./BP16-061";
import c_BP16_062 from "./BP16-062";
import c_BP16_063 from "./BP16-063";
import c_BP16_064 from "./BP16-064";
import c_BP16_065 from "./BP16-065";
import c_BP16_066 from "./BP16-066";
import c_BP16_067 from "./BP16-067";
import c_BP16_068 from "./BP16-068";
import c_BP16_069 from "./BP16-069";
import c_BP16_070 from "./BP16-070";
import c_BP16_071 from "./BP16-071";
import c_BP16_072 from "./BP16-072";
import c_BP16_073 from "./BP16-073";
import c_BP16_074 from "./BP16-074";
import c_BP16_075 from "./BP16-075";
import c_BP16_076 from "./BP16-076";
import c_BP16_077 from "./BP16-077";
import c_BP16_078 from "./BP16-078";
import c_BP16_079 from "./BP16-079";
import c_BP16_080 from "./BP16-080";
import c_BP16_081 from "./BP16-081";
import c_BP16_082 from "./BP16-082";
import c_BP16_083 from "./BP16-083";
import c_BP16_084 from "./BP16-084";
import c_BP16_085 from "./BP16-085";
import c_BP16_086 from "./BP16-086";
import c_BP16_087 from "./BP16-087";
import c_BP16_088 from "./BP16-088";
import c_BP16_089 from "./BP16-089";
import c_BP16_090 from "./BP16-090";
import c_BP16_091 from "./BP16-091";
import c_BP16_092 from "./BP16-092";
import c_BP16_093 from "./BP16-093";
import c_BP16_094 from "./BP16-094";
import c_BP16_095 from "./BP16-095";
import c_BP16_096 from "./BP16-096";
import c_BP16_097 from "./BP16-097";
import c_BP16_098 from "./BP16-098";
import c_BP16_099 from "./BP16-099";
import c_BP16_100 from "./BP16-100";
import c_BP16_101 from "./BP16-101";
import c_BP16_102 from "./BP16-102";
import c_BP16_103 from "./BP16-103";
import c_BP16_104 from "./BP16-104";
import c_BP16_105 from "./BP16-105";
import c_BP16_106 from "./BP16-106";
import c_BP16_107 from "./BP16-107";
import c_BP16_108 from "./BP16-108";
import c_BP16_109 from "./BP16-109";
import c_BP16_110 from "./BP16-110";
import c_BP16_111 from "./BP16-111";
import c_BP16_112 from "./BP16-112";
import c_BP16_113 from "./BP16-113";
import c_BP16_114 from "./BP16-114";
import c_BP16_115 from "./BP16-115";
import c_BP16_116 from "./BP16-116";
import c_BP16_117 from "./BP16-117";
import c_BP16_118 from "./BP16-118";
import c_BP16_119 from "./BP16-119";
import c_BP16_120 from "./BP16-120";
import c_BP16_121 from "./BP16-121";
import c_BP16_T01 from "./BP16-T01";
import c_BP16_T02 from "./BP16-T02";
import c_BP16_T03 from "./BP16-T03";
import c_BP16_T04 from "./BP16-T04";
import c_BP16_T05 from "./BP16-T05";
import c_BP16_T06 from "./BP16-T06";
import c_BP16_T08 from "./BP16-T08";
import c_BP16_T09 from "./BP16-T09";

/**
 * Card scripts of BP16, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP16_SCRIPTS: ScriptRegistry = {
  "BP16-001": c_BP16_001,
  "BP16-002": c_BP16_002,
  "BP16-003": c_BP16_003,
  "BP16-004": c_BP16_004,
  "BP16-005": c_BP16_005,
  "BP16-006": c_BP16_006,
  "BP16-007": c_BP16_007,
  "BP16-008": c_BP16_008,
  "BP16-009": c_BP16_009,
  "BP16-010": c_BP16_010,
  "BP16-011": c_BP16_011,
  "BP16-012": c_BP16_012,
  "BP16-013": c_BP16_013,
  "BP16-014": c_BP16_014,
  "BP16-015": c_BP16_015,
  "BP16-016": c_BP16_016,
  "BP16-017": c_BP16_017,
  "BP16-018": c_BP16_018,
  "BP16-019": c_BP16_019,
  "BP16-020": c_BP16_020,
  "BP16-021": c_BP16_021,
  "BP16-022": c_BP16_022,
  "BP16-023": c_BP16_023,
  "BP16-024": c_BP16_024,
  "BP16-025": c_BP16_025,
  "BP16-026": c_BP16_026,
  "BP16-027": c_BP16_027,
  "BP16-028": c_BP16_028,
  "BP16-029": c_BP16_029,
  "BP16-030": c_BP16_030,
  "BP16-031": c_BP16_031,
  "BP16-032": c_BP16_032,
  "BP16-033": c_BP16_033,
  "BP16-034": c_BP16_034,
  "BP16-035": c_BP16_035,
  "BP16-036": c_BP16_036,
  "BP16-037": c_BP16_037,
  "BP16-038": c_BP16_038,
  "BP16-039": c_BP16_039,
  "BP16-040": c_BP16_040,
  "BP16-041": c_BP16_041,
  "BP16-042": c_BP16_042,
  "BP16-043": c_BP16_043,
  "BP16-044": c_BP16_044,
  "BP16-045": c_BP16_045,
  "BP16-046": c_BP16_046,
  "BP16-047": c_BP16_047,
  "BP16-048": c_BP16_048,
  "BP16-049": c_BP16_049,
  "BP16-050": c_BP16_050,
  "BP16-051": c_BP16_051,
  "BP16-052": c_BP16_052,
  "BP16-053": c_BP16_053,
  "BP16-054": c_BP16_054,
  "BP16-055": c_BP16_055,
  "BP16-056": c_BP16_056,
  "BP16-057": c_BP16_057,
  "BP16-058": c_BP16_058,
  "BP16-059": c_BP16_059,
  "BP16-060": c_BP16_060,
  "BP16-061": c_BP16_061,
  "BP16-062": c_BP16_062,
  "BP16-063": c_BP16_063,
  "BP16-064": c_BP16_064,
  "BP16-065": c_BP16_065,
  "BP16-066": c_BP16_066,
  "BP16-067": c_BP16_067,
  "BP16-068": c_BP16_068,
  "BP16-069": c_BP16_069,
  "BP16-070": c_BP16_070,
  "BP16-071": c_BP16_071,
  "BP16-072": c_BP16_072,
  "BP16-073": c_BP16_073,
  "BP16-074": c_BP16_074,
  "BP16-075": c_BP16_075,
  "BP16-076": c_BP16_076,
  "BP16-077": c_BP16_077,
  "BP16-078": c_BP16_078,
  "BP16-079": c_BP16_079,
  "BP16-080": c_BP16_080,
  "BP16-081": c_BP16_081,
  "BP16-082": c_BP16_082,
  "BP16-083": c_BP16_083,
  "BP16-084": c_BP16_084,
  "BP16-085": c_BP16_085,
  "BP16-086": c_BP16_086,
  "BP16-087": c_BP16_087,
  "BP16-088": c_BP16_088,
  "BP16-089": c_BP16_089,
  "BP16-090": c_BP16_090,
  "BP16-091": c_BP16_091,
  "BP16-092": c_BP16_092,
  "BP16-093": c_BP16_093,
  "BP16-094": c_BP16_094,
  "BP16-095": c_BP16_095,
  "BP16-096": c_BP16_096,
  "BP16-097": c_BP16_097,
  "BP16-098": c_BP16_098,
  "BP16-099": c_BP16_099,
  "BP16-100": c_BP16_100,
  "BP16-101": c_BP16_101,
  "BP16-102": c_BP16_102,
  "BP16-103": c_BP16_103,
  "BP16-104": c_BP16_104,
  "BP16-105": c_BP16_105,
  "BP16-106": c_BP16_106,
  "BP16-107": c_BP16_107,
  "BP16-108": c_BP16_108,
  "BP16-109": c_BP16_109,
  "BP16-110": c_BP16_110,
  "BP16-111": c_BP16_111,
  "BP16-112": c_BP16_112,
  "BP16-113": c_BP16_113,
  "BP16-114": c_BP16_114,
  "BP16-115": c_BP16_115,
  "BP16-116": c_BP16_116,
  "BP16-117": c_BP16_117,
  "BP16-118": c_BP16_118,
  "BP16-119": c_BP16_119,
  "BP16-120": c_BP16_120,
  "BP16-121": c_BP16_121,
  "BP16-T01": c_BP16_T01,
  "BP16-T02": c_BP16_T02,
  "BP16-T03": c_BP16_T03,
  "BP16-T04": c_BP16_T04,
  "BP16-T05": c_BP16_T05,
  "BP16-T06": c_BP16_T06,
  "BP16-T08": c_BP16_T08,
  "BP16-T09": c_BP16_T09,
};
