// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_ECP01_001 from "./ECP01-001";
import c_ECP01_002 from "./ECP01-002";
import c_ECP01_003 from "./ECP01-003";
import c_ECP01_004 from "./ECP01-004";
import c_ECP01_005 from "./ECP01-005";
import c_ECP01_006 from "./ECP01-006";
import c_ECP01_007 from "./ECP01-007";
import c_ECP01_008 from "./ECP01-008";
import c_ECP01_009 from "./ECP01-009";
import c_ECP01_010 from "./ECP01-010";
import c_ECP01_011 from "./ECP01-011";
import c_ECP01_012 from "./ECP01-012";
import c_ECP01_013 from "./ECP01-013";
import c_ECP01_014 from "./ECP01-014";
import c_ECP01_015 from "./ECP01-015";
import c_ECP01_016 from "./ECP01-016";
import c_ECP01_017 from "./ECP01-017";
import c_ECP01_018 from "./ECP01-018";
import c_ECP01_019 from "./ECP01-019";
import c_ECP01_020 from "./ECP01-020";
import c_ECP01_021 from "./ECP01-021";
import c_ECP01_022 from "./ECP01-022";
import c_ECP01_023 from "./ECP01-023";
import c_ECP01_024 from "./ECP01-024";
import c_ECP01_025 from "./ECP01-025";
import c_ECP01_026 from "./ECP01-026";
import c_ECP01_027 from "./ECP01-027";
import c_ECP01_028 from "./ECP01-028";
import c_ECP01_029 from "./ECP01-029";
import c_ECP01_030 from "./ECP01-030";
import c_ECP01_031 from "./ECP01-031";
import c_ECP01_032 from "./ECP01-032";
import c_ECP01_033 from "./ECP01-033";
import c_ECP01_034 from "./ECP01-034";
import c_ECP01_035 from "./ECP01-035";
import c_ECP01_036 from "./ECP01-036";
import c_ECP01_037 from "./ECP01-037";
import c_ECP01_038 from "./ECP01-038";
import c_ECP01_039 from "./ECP01-039";
import c_ECP01_040 from "./ECP01-040";
import c_ECP01_041 from "./ECP01-041";
import c_ECP01_042 from "./ECP01-042";
import c_ECP01_043 from "./ECP01-043";
import c_ECP01_044 from "./ECP01-044";
import c_ECP01_045 from "./ECP01-045";
import c_ECP01_046 from "./ECP01-046";
import c_ECP01_047 from "./ECP01-047";
import c_ECP01_048 from "./ECP01-048";
import c_ECP01_049 from "./ECP01-049";
import c_ECP01_050 from "./ECP01-050";
import c_ECP01_051 from "./ECP01-051";
import c_ECP01_052 from "./ECP01-052";
import c_ECP01_053 from "./ECP01-053";
import c_ECP01_054 from "./ECP01-054";
import c_ECP01_055 from "./ECP01-055";
import c_ECP01_056 from "./ECP01-056";
import c_ECP01_057 from "./ECP01-057";

/**
 * Card scripts of ECP01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const ECP01_SCRIPTS: ScriptRegistry = {
  "ECP01-001": c_ECP01_001,
  "ECP01-002": c_ECP01_002,
  "ECP01-003": c_ECP01_003,
  "ECP01-004": c_ECP01_004,
  "ECP01-005": c_ECP01_005,
  "ECP01-006": c_ECP01_006,
  "ECP01-007": c_ECP01_007,
  "ECP01-008": c_ECP01_008,
  "ECP01-009": c_ECP01_009,
  "ECP01-010": c_ECP01_010,
  "ECP01-011": c_ECP01_011,
  "ECP01-012": c_ECP01_012,
  "ECP01-013": c_ECP01_013,
  "ECP01-014": c_ECP01_014,
  "ECP01-015": c_ECP01_015,
  "ECP01-016": c_ECP01_016,
  "ECP01-017": c_ECP01_017,
  "ECP01-018": c_ECP01_018,
  "ECP01-019": c_ECP01_019,
  "ECP01-020": c_ECP01_020,
  "ECP01-021": c_ECP01_021,
  "ECP01-022": c_ECP01_022,
  "ECP01-023": c_ECP01_023,
  "ECP01-024": c_ECP01_024,
  "ECP01-025": c_ECP01_025,
  "ECP01-026": c_ECP01_026,
  "ECP01-027": c_ECP01_027,
  "ECP01-028": c_ECP01_028,
  "ECP01-029": c_ECP01_029,
  "ECP01-030": c_ECP01_030,
  "ECP01-031": c_ECP01_031,
  "ECP01-032": c_ECP01_032,
  "ECP01-033": c_ECP01_033,
  "ECP01-034": c_ECP01_034,
  "ECP01-035": c_ECP01_035,
  "ECP01-036": c_ECP01_036,
  "ECP01-037": c_ECP01_037,
  "ECP01-038": c_ECP01_038,
  "ECP01-039": c_ECP01_039,
  "ECP01-040": c_ECP01_040,
  "ECP01-041": c_ECP01_041,
  "ECP01-042": c_ECP01_042,
  "ECP01-043": c_ECP01_043,
  "ECP01-044": c_ECP01_044,
  "ECP01-045": c_ECP01_045,
  "ECP01-046": c_ECP01_046,
  "ECP01-047": c_ECP01_047,
  "ECP01-048": c_ECP01_048,
  "ECP01-049": c_ECP01_049,
  "ECP01-050": c_ECP01_050,
  "ECP01-051": c_ECP01_051,
  "ECP01-052": c_ECP01_052,
  "ECP01-053": c_ECP01_053,
  "ECP01-054": c_ECP01_054,
  "ECP01-055": c_ECP01_055,
  "ECP01-056": c_ECP01_056,
  "ECP01-057": c_ECP01_057,
};
