// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP11_001 from "./BP11-001";
import c_BP11_002 from "./BP11-002";
import c_BP11_003 from "./BP11-003";
import c_BP11_004 from "./BP11-004";
import c_BP11_005 from "./BP11-005";
import c_BP11_006 from "./BP11-006";
import c_BP11_007 from "./BP11-007";
import c_BP11_008 from "./BP11-008";
import c_BP11_009 from "./BP11-009";
import c_BP11_010 from "./BP11-010";
import c_BP11_011 from "./BP11-011";
import c_BP11_012 from "./BP11-012";
import c_BP11_013 from "./BP11-013";
import c_BP11_014 from "./BP11-014";
import c_BP11_015 from "./BP11-015";
import c_BP11_016 from "./BP11-016";
import c_BP11_017 from "./BP11-017";
import c_BP11_018 from "./BP11-018";
import c_BP11_019 from "./BP11-019";
import c_BP11_020 from "./BP11-020";
import c_BP11_021 from "./BP11-021";
import c_BP11_022 from "./BP11-022";
import c_BP11_023 from "./BP11-023";
import c_BP11_024 from "./BP11-024";
import c_BP11_025 from "./BP11-025";
import c_BP11_026 from "./BP11-026";
import c_BP11_027 from "./BP11-027";
import c_BP11_028 from "./BP11-028";
import c_BP11_029 from "./BP11-029";
import c_BP11_030 from "./BP11-030";
import c_BP11_031 from "./BP11-031";
import c_BP11_032 from "./BP11-032";
import c_BP11_033 from "./BP11-033";
import c_BP11_034 from "./BP11-034";
import c_BP11_035 from "./BP11-035";
import c_BP11_036 from "./BP11-036";
import c_BP11_037 from "./BP11-037";
import c_BP11_038 from "./BP11-038";
import c_BP11_039 from "./BP11-039";
import c_BP11_040 from "./BP11-040";
import c_BP11_041 from "./BP11-041";
import c_BP11_042 from "./BP11-042";
import c_BP11_043 from "./BP11-043";
import c_BP11_044 from "./BP11-044";
import c_BP11_045 from "./BP11-045";
import c_BP11_046 from "./BP11-046";
import c_BP11_047 from "./BP11-047";
import c_BP11_048 from "./BP11-048";
import c_BP11_049 from "./BP11-049";
import c_BP11_050 from "./BP11-050";
import c_BP11_051 from "./BP11-051";
import c_BP11_052 from "./BP11-052";
import c_BP11_053 from "./BP11-053";
import c_BP11_054 from "./BP11-054";
import c_BP11_055 from "./BP11-055";
import c_BP11_056 from "./BP11-056";
import c_BP11_057 from "./BP11-057";
import c_BP11_058 from "./BP11-058";
import c_BP11_059 from "./BP11-059";
import c_BP11_060 from "./BP11-060";
import c_BP11_061 from "./BP11-061";
import c_BP11_062 from "./BP11-062";
import c_BP11_063 from "./BP11-063";
import c_BP11_064 from "./BP11-064";
import c_BP11_065 from "./BP11-065";
import c_BP11_066 from "./BP11-066";
import c_BP11_067 from "./BP11-067";
import c_BP11_068 from "./BP11-068";
import c_BP11_069 from "./BP11-069";
import c_BP11_070 from "./BP11-070";
import c_BP11_071 from "./BP11-071";
import c_BP11_072 from "./BP11-072";
import c_BP11_073 from "./BP11-073";
import c_BP11_074 from "./BP11-074";
import c_BP11_075 from "./BP11-075";
import c_BP11_076 from "./BP11-076";
import c_BP11_077 from "./BP11-077";
import c_BP11_078 from "./BP11-078";
import c_BP11_079 from "./BP11-079";
import c_BP11_080 from "./BP11-080";
import c_BP11_081 from "./BP11-081";
import c_BP11_082 from "./BP11-082";
import c_BP11_083 from "./BP11-083";
import c_BP11_084 from "./BP11-084";
import c_BP11_085 from "./BP11-085";
import c_BP11_086 from "./BP11-086";
import c_BP11_087 from "./BP11-087";
import c_BP11_088 from "./BP11-088";
import c_BP11_089 from "./BP11-089";
import c_BP11_090 from "./BP11-090";
import c_BP11_091 from "./BP11-091";
import c_BP11_092 from "./BP11-092";
import c_BP11_093 from "./BP11-093";
import c_BP11_094 from "./BP11-094";
import c_BP11_095 from "./BP11-095";
import c_BP11_096 from "./BP11-096";
import c_BP11_097 from "./BP11-097";
import c_BP11_098 from "./BP11-098";
import c_BP11_099 from "./BP11-099";
import c_BP11_100 from "./BP11-100";
import c_BP11_101 from "./BP11-101";
import c_BP11_102 from "./BP11-102";
import c_BP11_103 from "./BP11-103";
import c_BP11_104 from "./BP11-104";
import c_BP11_105 from "./BP11-105";
import c_BP11_106 from "./BP11-106";
import c_BP11_107 from "./BP11-107";
import c_BP11_108 from "./BP11-108";
import c_BP11_109 from "./BP11-109";
import c_BP11_110 from "./BP11-110";
import c_BP11_111 from "./BP11-111";
import c_BP11_112 from "./BP11-112";
import c_BP11_113 from "./BP11-113";
import c_BP11_114 from "./BP11-114";
import c_BP11_115 from "./BP11-115";
import c_BP11_116 from "./BP11-116";
import c_BP11_T01 from "./BP11-T01";
import c_BP11_T02 from "./BP11-T02";
import c_BP11_T03 from "./BP11-T03";
import c_BP11_T04 from "./BP11-T04";
import c_BP11_T05 from "./BP11-T05";

/**
 * Card scripts of BP11, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP11_SCRIPTS: ScriptRegistry = {
  "BP11-001": c_BP11_001,
  "BP11-002": c_BP11_002,
  "BP11-003": c_BP11_003,
  "BP11-004": c_BP11_004,
  "BP11-005": c_BP11_005,
  "BP11-006": c_BP11_006,
  "BP11-007": c_BP11_007,
  "BP11-008": c_BP11_008,
  "BP11-009": c_BP11_009,
  "BP11-010": c_BP11_010,
  "BP11-011": c_BP11_011,
  "BP11-012": c_BP11_012,
  "BP11-013": c_BP11_013,
  "BP11-014": c_BP11_014,
  "BP11-015": c_BP11_015,
  "BP11-016": c_BP11_016,
  "BP11-017": c_BP11_017,
  "BP11-018": c_BP11_018,
  "BP11-019": c_BP11_019,
  "BP11-020": c_BP11_020,
  "BP11-021": c_BP11_021,
  "BP11-022": c_BP11_022,
  "BP11-023": c_BP11_023,
  "BP11-024": c_BP11_024,
  "BP11-025": c_BP11_025,
  "BP11-026": c_BP11_026,
  "BP11-027": c_BP11_027,
  "BP11-028": c_BP11_028,
  "BP11-029": c_BP11_029,
  "BP11-030": c_BP11_030,
  "BP11-031": c_BP11_031,
  "BP11-032": c_BP11_032,
  "BP11-033": c_BP11_033,
  "BP11-034": c_BP11_034,
  "BP11-035": c_BP11_035,
  "BP11-036": c_BP11_036,
  "BP11-037": c_BP11_037,
  "BP11-038": c_BP11_038,
  "BP11-039": c_BP11_039,
  "BP11-040": c_BP11_040,
  "BP11-041": c_BP11_041,
  "BP11-042": c_BP11_042,
  "BP11-043": c_BP11_043,
  "BP11-044": c_BP11_044,
  "BP11-045": c_BP11_045,
  "BP11-046": c_BP11_046,
  "BP11-047": c_BP11_047,
  "BP11-048": c_BP11_048,
  "BP11-049": c_BP11_049,
  "BP11-050": c_BP11_050,
  "BP11-051": c_BP11_051,
  "BP11-052": c_BP11_052,
  "BP11-053": c_BP11_053,
  "BP11-054": c_BP11_054,
  "BP11-055": c_BP11_055,
  "BP11-056": c_BP11_056,
  "BP11-057": c_BP11_057,
  "BP11-058": c_BP11_058,
  "BP11-059": c_BP11_059,
  "BP11-060": c_BP11_060,
  "BP11-061": c_BP11_061,
  "BP11-062": c_BP11_062,
  "BP11-063": c_BP11_063,
  "BP11-064": c_BP11_064,
  "BP11-065": c_BP11_065,
  "BP11-066": c_BP11_066,
  "BP11-067": c_BP11_067,
  "BP11-068": c_BP11_068,
  "BP11-069": c_BP11_069,
  "BP11-070": c_BP11_070,
  "BP11-071": c_BP11_071,
  "BP11-072": c_BP11_072,
  "BP11-073": c_BP11_073,
  "BP11-074": c_BP11_074,
  "BP11-075": c_BP11_075,
  "BP11-076": c_BP11_076,
  "BP11-077": c_BP11_077,
  "BP11-078": c_BP11_078,
  "BP11-079": c_BP11_079,
  "BP11-080": c_BP11_080,
  "BP11-081": c_BP11_081,
  "BP11-082": c_BP11_082,
  "BP11-083": c_BP11_083,
  "BP11-084": c_BP11_084,
  "BP11-085": c_BP11_085,
  "BP11-086": c_BP11_086,
  "BP11-087": c_BP11_087,
  "BP11-088": c_BP11_088,
  "BP11-089": c_BP11_089,
  "BP11-090": c_BP11_090,
  "BP11-091": c_BP11_091,
  "BP11-092": c_BP11_092,
  "BP11-093": c_BP11_093,
  "BP11-094": c_BP11_094,
  "BP11-095": c_BP11_095,
  "BP11-096": c_BP11_096,
  "BP11-097": c_BP11_097,
  "BP11-098": c_BP11_098,
  "BP11-099": c_BP11_099,
  "BP11-100": c_BP11_100,
  "BP11-101": c_BP11_101,
  "BP11-102": c_BP11_102,
  "BP11-103": c_BP11_103,
  "BP11-104": c_BP11_104,
  "BP11-105": c_BP11_105,
  "BP11-106": c_BP11_106,
  "BP11-107": c_BP11_107,
  "BP11-108": c_BP11_108,
  "BP11-109": c_BP11_109,
  "BP11-110": c_BP11_110,
  "BP11-111": c_BP11_111,
  "BP11-112": c_BP11_112,
  "BP11-113": c_BP11_113,
  "BP11-114": c_BP11_114,
  "BP11-115": c_BP11_115,
  "BP11-116": c_BP11_116,
  "BP11-T01": c_BP11_T01,
  "BP11-T02": c_BP11_T02,
  "BP11-T03": c_BP11_T03,
  "BP11-T04": c_BP11_T04,
  "BP11-T05": c_BP11_T05,
};
