// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_PCS01_048 from "./PCS01-048";
import c_PCS01_049 from "./PCS01-049";

/**
 * Card scripts of PCS01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const PCS01_SCRIPTS: ScriptRegistry = {
  "PCS01-048": c_PCS01_048,
  "PCS01-049": c_PCS01_049,
};
