// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CSD03b_001 from "./CSD03b-001";
import c_CSD03b_002 from "./CSD03b-002";
import c_CSD03b_003 from "./CSD03b-003";
import c_CSD03b_004 from "./CSD03b-004";
import c_CSD03b_005 from "./CSD03b-005";
import c_CSD03b_006 from "./CSD03b-006";
import c_CSD03b_007 from "./CSD03b-007";
import c_CSD03b_008 from "./CSD03b-008";
import c_CSD03b_009 from "./CSD03b-009";
import c_CSD03b_010 from "./CSD03b-010";
import c_CSD03b_011 from "./CSD03b-011";
import c_CSD03b_016 from "./CSD03b-016";

/**
 * Card scripts of CSD03b, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CSD03b_SCRIPTS: ScriptRegistry = {
  "CSD03b-001": c_CSD03b_001,
  "CSD03b-002": c_CSD03b_002,
  "CSD03b-003": c_CSD03b_003,
  "CSD03b-004": c_CSD03b_004,
  "CSD03b-005": c_CSD03b_005,
  "CSD03b-006": c_CSD03b_006,
  "CSD03b-007": c_CSD03b_007,
  "CSD03b-008": c_CSD03b_008,
  "CSD03b-009": c_CSD03b_009,
  "CSD03b-010": c_CSD03b_010,
  "CSD03b-011": c_CSD03b_011,
  "CSD03b-016": c_CSD03b_016,
};
