// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_EBD01_007 from "./EBD01-007";

/**
 * Card scripts of EBD01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const EBD01_SCRIPTS: ScriptRegistry = {
  "EBD01-007": c_EBD01_007,
};
