// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP07_001 from "./BP07-001";
import c_BP07_002 from "./BP07-002";
import c_BP07_003 from "./BP07-003";
import c_BP07_004 from "./BP07-004";
import c_BP07_005 from "./BP07-005";
import c_BP07_006 from "./BP07-006";
import c_BP07_007 from "./BP07-007";
import c_BP07_008 from "./BP07-008";
import c_BP07_009 from "./BP07-009";
import c_BP07_010 from "./BP07-010";
import c_BP07_011 from "./BP07-011";
import c_BP07_012 from "./BP07-012";
import c_BP07_013 from "./BP07-013";
import c_BP07_014 from "./BP07-014";
import c_BP07_015 from "./BP07-015";
import c_BP07_016 from "./BP07-016";
import c_BP07_017 from "./BP07-017";
import c_BP07_018 from "./BP07-018";
import c_BP07_019 from "./BP07-019";
import c_BP07_020 from "./BP07-020";
import c_BP07_021 from "./BP07-021";
import c_BP07_022 from "./BP07-022";
import c_BP07_023 from "./BP07-023";
import c_BP07_024 from "./BP07-024";
import c_BP07_025 from "./BP07-025";
import c_BP07_026 from "./BP07-026";
import c_BP07_027 from "./BP07-027";
import c_BP07_028 from "./BP07-028";
import c_BP07_029 from "./BP07-029";
import c_BP07_030 from "./BP07-030";
import c_BP07_031 from "./BP07-031";
import c_BP07_032 from "./BP07-032";
import c_BP07_033 from "./BP07-033";
import c_BP07_034 from "./BP07-034";
import c_BP07_035 from "./BP07-035";
import c_BP07_036 from "./BP07-036";
import c_BP07_037 from "./BP07-037";
import c_BP07_038 from "./BP07-038";
import c_BP07_039 from "./BP07-039";
import c_BP07_040 from "./BP07-040";
import c_BP07_041 from "./BP07-041";
import c_BP07_042 from "./BP07-042";
import c_BP07_043 from "./BP07-043";
import c_BP07_044 from "./BP07-044";
import c_BP07_045 from "./BP07-045";
import c_BP07_046 from "./BP07-046";
import c_BP07_047 from "./BP07-047";
import c_BP07_048 from "./BP07-048";
import c_BP07_049 from "./BP07-049";
import c_BP07_050 from "./BP07-050";
import c_BP07_051 from "./BP07-051";
import c_BP07_052 from "./BP07-052";
import c_BP07_053 from "./BP07-053";
import c_BP07_054 from "./BP07-054";
import c_BP07_055 from "./BP07-055";
import c_BP07_056 from "./BP07-056";
import c_BP07_057 from "./BP07-057";
import c_BP07_058 from "./BP07-058";
import c_BP07_059 from "./BP07-059";
import c_BP07_060 from "./BP07-060";
import c_BP07_061 from "./BP07-061";
import c_BP07_062 from "./BP07-062";
import c_BP07_063 from "./BP07-063";
import c_BP07_064 from "./BP07-064";
import c_BP07_065 from "./BP07-065";
import c_BP07_066 from "./BP07-066";
import c_BP07_067 from "./BP07-067";
import c_BP07_068 from "./BP07-068";
import c_BP07_069 from "./BP07-069";
import c_BP07_070 from "./BP07-070";
import c_BP07_071 from "./BP07-071";
import c_BP07_072 from "./BP07-072";
import c_BP07_073 from "./BP07-073";
import c_BP07_074 from "./BP07-074";
import c_BP07_075 from "./BP07-075";
import c_BP07_076 from "./BP07-076";
import c_BP07_077 from "./BP07-077";
import c_BP07_078 from "./BP07-078";
import c_BP07_079 from "./BP07-079";
import c_BP07_080 from "./BP07-080";
import c_BP07_081 from "./BP07-081";
import c_BP07_082 from "./BP07-082";
import c_BP07_083 from "./BP07-083";
import c_BP07_084 from "./BP07-084";
import c_BP07_085 from "./BP07-085";
import c_BP07_086 from "./BP07-086";
import c_BP07_087 from "./BP07-087";
import c_BP07_088 from "./BP07-088";
import c_BP07_089 from "./BP07-089";
import c_BP07_090 from "./BP07-090";
import c_BP07_091 from "./BP07-091";
import c_BP07_092 from "./BP07-092";
import c_BP07_093 from "./BP07-093";
import c_BP07_094 from "./BP07-094";
import c_BP07_095 from "./BP07-095";
import c_BP07_096 from "./BP07-096";
import c_BP07_097 from "./BP07-097";
import c_BP07_098 from "./BP07-098";
import c_BP07_099 from "./BP07-099";
import c_BP07_100 from "./BP07-100";
import c_BP07_101 from "./BP07-101";
import c_BP07_102 from "./BP07-102";
import c_BP07_103 from "./BP07-103";
import c_BP07_104 from "./BP07-104";
import c_BP07_105 from "./BP07-105";
import c_BP07_106 from "./BP07-106";
import c_BP07_107 from "./BP07-107";
import c_BP07_108 from "./BP07-108";
import c_BP07_109 from "./BP07-109";
import c_BP07_110 from "./BP07-110";
import c_BP07_111 from "./BP07-111";
import c_BP07_112 from "./BP07-112";
import c_BP07_113 from "./BP07-113";
import c_BP07_114 from "./BP07-114";
import c_BP07_115 from "./BP07-115";
import c_BP07_116 from "./BP07-116";
import c_BP07_117 from "./BP07-117";
import c_BP07_T01 from "./BP07-T01";
import c_BP07_T02 from "./BP07-T02";
import c_BP07_T03 from "./BP07-T03";

/**
 * Card scripts of BP07, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP07_SCRIPTS: ScriptRegistry = {
  "BP07-001": c_BP07_001,
  "BP07-002": c_BP07_002,
  "BP07-003": c_BP07_003,
  "BP07-004": c_BP07_004,
  "BP07-005": c_BP07_005,
  "BP07-006": c_BP07_006,
  "BP07-007": c_BP07_007,
  "BP07-008": c_BP07_008,
  "BP07-009": c_BP07_009,
  "BP07-010": c_BP07_010,
  "BP07-011": c_BP07_011,
  "BP07-012": c_BP07_012,
  "BP07-013": c_BP07_013,
  "BP07-014": c_BP07_014,
  "BP07-015": c_BP07_015,
  "BP07-016": c_BP07_016,
  "BP07-017": c_BP07_017,
  "BP07-018": c_BP07_018,
  "BP07-019": c_BP07_019,
  "BP07-020": c_BP07_020,
  "BP07-021": c_BP07_021,
  "BP07-022": c_BP07_022,
  "BP07-023": c_BP07_023,
  "BP07-024": c_BP07_024,
  "BP07-025": c_BP07_025,
  "BP07-026": c_BP07_026,
  "BP07-027": c_BP07_027,
  "BP07-028": c_BP07_028,
  "BP07-029": c_BP07_029,
  "BP07-030": c_BP07_030,
  "BP07-031": c_BP07_031,
  "BP07-032": c_BP07_032,
  "BP07-033": c_BP07_033,
  "BP07-034": c_BP07_034,
  "BP07-035": c_BP07_035,
  "BP07-036": c_BP07_036,
  "BP07-037": c_BP07_037,
  "BP07-038": c_BP07_038,
  "BP07-039": c_BP07_039,
  "BP07-040": c_BP07_040,
  "BP07-041": c_BP07_041,
  "BP07-042": c_BP07_042,
  "BP07-043": c_BP07_043,
  "BP07-044": c_BP07_044,
  "BP07-045": c_BP07_045,
  "BP07-046": c_BP07_046,
  "BP07-047": c_BP07_047,
  "BP07-048": c_BP07_048,
  "BP07-049": c_BP07_049,
  "BP07-050": c_BP07_050,
  "BP07-051": c_BP07_051,
  "BP07-052": c_BP07_052,
  "BP07-053": c_BP07_053,
  "BP07-054": c_BP07_054,
  "BP07-055": c_BP07_055,
  "BP07-056": c_BP07_056,
  "BP07-057": c_BP07_057,
  "BP07-058": c_BP07_058,
  "BP07-059": c_BP07_059,
  "BP07-060": c_BP07_060,
  "BP07-061": c_BP07_061,
  "BP07-062": c_BP07_062,
  "BP07-063": c_BP07_063,
  "BP07-064": c_BP07_064,
  "BP07-065": c_BP07_065,
  "BP07-066": c_BP07_066,
  "BP07-067": c_BP07_067,
  "BP07-068": c_BP07_068,
  "BP07-069": c_BP07_069,
  "BP07-070": c_BP07_070,
  "BP07-071": c_BP07_071,
  "BP07-072": c_BP07_072,
  "BP07-073": c_BP07_073,
  "BP07-074": c_BP07_074,
  "BP07-075": c_BP07_075,
  "BP07-076": c_BP07_076,
  "BP07-077": c_BP07_077,
  "BP07-078": c_BP07_078,
  "BP07-079": c_BP07_079,
  "BP07-080": c_BP07_080,
  "BP07-081": c_BP07_081,
  "BP07-082": c_BP07_082,
  "BP07-083": c_BP07_083,
  "BP07-084": c_BP07_084,
  "BP07-085": c_BP07_085,
  "BP07-086": c_BP07_086,
  "BP07-087": c_BP07_087,
  "BP07-088": c_BP07_088,
  "BP07-089": c_BP07_089,
  "BP07-090": c_BP07_090,
  "BP07-091": c_BP07_091,
  "BP07-092": c_BP07_092,
  "BP07-093": c_BP07_093,
  "BP07-094": c_BP07_094,
  "BP07-095": c_BP07_095,
  "BP07-096": c_BP07_096,
  "BP07-097": c_BP07_097,
  "BP07-098": c_BP07_098,
  "BP07-099": c_BP07_099,
  "BP07-100": c_BP07_100,
  "BP07-101": c_BP07_101,
  "BP07-102": c_BP07_102,
  "BP07-103": c_BP07_103,
  "BP07-104": c_BP07_104,
  "BP07-105": c_BP07_105,
  "BP07-106": c_BP07_106,
  "BP07-107": c_BP07_107,
  "BP07-108": c_BP07_108,
  "BP07-109": c_BP07_109,
  "BP07-110": c_BP07_110,
  "BP07-111": c_BP07_111,
  "BP07-112": c_BP07_112,
  "BP07-113": c_BP07_113,
  "BP07-114": c_BP07_114,
  "BP07-115": c_BP07_115,
  "BP07-116": c_BP07_116,
  "BP07-117": c_BP07_117,
  "BP07-T01": c_BP07_T01,
  "BP07-T02": c_BP07_T02,
  "BP07-T03": c_BP07_T03,
};
