// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD02_001 from "./SD02-001";
import c_SD02_003 from "./SD02-003";
import c_SD02_004 from "./SD02-004";
import c_SD02_005 from "./SD02-005";
import c_SD02_006 from "./SD02-006";
import c_SD02_009 from "./SD02-009";
import c_SD02_010 from "./SD02-010";
import c_SD02_011 from "./SD02-011";
import c_SD02_012 from "./SD02-012";
import c_SD02_013 from "./SD02-013";
import c_SD02_016 from "./SD02-016";

/**
 * Card scripts of SD02, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD02_SCRIPTS: ScriptRegistry = {
  "SD02-001": c_SD02_001,
  "SD02-003": c_SD02_003,
  "SD02-004": c_SD02_004,
  "SD02-005": c_SD02_005,
  "SD02-006": c_SD02_006,
  "SD02-009": c_SD02_009,
  "SD02-010": c_SD02_010,
  "SD02-011": c_SD02_011,
  "SD02-012": c_SD02_012,
  "SD02-013": c_SD02_013,
  "SD02-016": c_SD02_016,
};
