// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP09_001 from "./BP09-001";
import c_BP09_002 from "./BP09-002";
import c_BP09_003 from "./BP09-003";
import c_BP09_004 from "./BP09-004";
import c_BP09_005 from "./BP09-005";
import c_BP09_005_back from "./BP09-005_back";
import c_BP09_006 from "./BP09-006";
import c_BP09_007 from "./BP09-007";
import c_BP09_008 from "./BP09-008";
import c_BP09_009 from "./BP09-009";
import c_BP09_010 from "./BP09-010";
import c_BP09_011 from "./BP09-011";
import c_BP09_012 from "./BP09-012";
import c_BP09_013 from "./BP09-013";
import c_BP09_014 from "./BP09-014";
import c_BP09_015 from "./BP09-015";
import c_BP09_016 from "./BP09-016";
import c_BP09_017 from "./BP09-017";
import c_BP09_018 from "./BP09-018";
import c_BP09_019 from "./BP09-019";
import c_BP09_019_back from "./BP09-019_back";
import c_BP09_020 from "./BP09-020";
import c_BP09_021 from "./BP09-021";
import c_BP09_022 from "./BP09-022";
import c_BP09_023 from "./BP09-023";
import c_BP09_024 from "./BP09-024";
import c_BP09_025 from "./BP09-025";
import c_BP09_026 from "./BP09-026";
import c_BP09_027 from "./BP09-027";
import c_BP09_028 from "./BP09-028";
import c_BP09_029 from "./BP09-029";
import c_BP09_030 from "./BP09-030";
import c_BP09_031 from "./BP09-031";
import c_BP09_032 from "./BP09-032";
import c_BP09_033 from "./BP09-033";
import c_BP09_034 from "./BP09-034";
import c_BP09_035 from "./BP09-035";
import c_BP09_036 from "./BP09-036";
import c_BP09_037 from "./BP09-037";
import c_BP09_038 from "./BP09-038";
import c_BP09_039 from "./BP09-039";
import c_BP09_039_back from "./BP09-039_back";
import c_BP09_040 from "./BP09-040";
import c_BP09_041 from "./BP09-041";
import c_BP09_042 from "./BP09-042";
import c_BP09_043 from "./BP09-043";
import c_BP09_044 from "./BP09-044";
import c_BP09_045 from "./BP09-045";
import c_BP09_046 from "./BP09-046";
import c_BP09_047 from "./BP09-047";
import c_BP09_048 from "./BP09-048";
import c_BP09_049 from "./BP09-049";
import c_BP09_050 from "./BP09-050";
import c_BP09_051 from "./BP09-051";
import c_BP09_052 from "./BP09-052";
import c_BP09_053 from "./BP09-053";
import c_BP09_054 from "./BP09-054";
import c_BP09_055 from "./BP09-055";
import c_BP09_056 from "./BP09-056";
import c_BP09_056_back from "./BP09-056_back";
import c_BP09_057 from "./BP09-057";
import c_BP09_058 from "./BP09-058";
import c_BP09_059 from "./BP09-059";
import c_BP09_060 from "./BP09-060";
import c_BP09_061 from "./BP09-061";
import c_BP09_062 from "./BP09-062";
import c_BP09_063 from "./BP09-063";
import c_BP09_064 from "./BP09-064";
import c_BP09_065 from "./BP09-065";
import c_BP09_066 from "./BP09-066";
import c_BP09_067 from "./BP09-067";
import c_BP09_068 from "./BP09-068";
import c_BP09_069 from "./BP09-069";
import c_BP09_070 from "./BP09-070";
import c_BP09_070_back from "./BP09-070_back";
import c_BP09_071 from "./BP09-071";
import c_BP09_072 from "./BP09-072";
import c_BP09_073 from "./BP09-073";
import c_BP09_074 from "./BP09-074";
import c_BP09_075 from "./BP09-075";
import c_BP09_076 from "./BP09-076";
import c_BP09_077 from "./BP09-077";
import c_BP09_078 from "./BP09-078";
import c_BP09_079 from "./BP09-079";
import c_BP09_080 from "./BP09-080";
import c_BP09_081 from "./BP09-081";
import c_BP09_082 from "./BP09-082";
import c_BP09_083 from "./BP09-083";
import c_BP09_084 from "./BP09-084";
import c_BP09_085 from "./BP09-085";
import c_BP09_086 from "./BP09-086";
import c_BP09_087 from "./BP09-087";
import c_BP09_088 from "./BP09-088";
import c_BP09_089 from "./BP09-089";
import c_BP09_090 from "./BP09-090";
import c_BP09_090_back from "./BP09-090_back";
import c_BP09_091 from "./BP09-091";
import c_BP09_092 from "./BP09-092";
import c_BP09_093 from "./BP09-093";
import c_BP09_094 from "./BP09-094";
import c_BP09_095 from "./BP09-095";
import c_BP09_096 from "./BP09-096";
import c_BP09_097 from "./BP09-097";
import c_BP09_098 from "./BP09-098";
import c_BP09_099 from "./BP09-099";
import c_BP09_100 from "./BP09-100";
import c_BP09_101 from "./BP09-101";
import c_BP09_102 from "./BP09-102";
import c_BP09_103 from "./BP09-103";
import c_BP09_104 from "./BP09-104";
import c_BP09_105 from "./BP09-105";
import c_BP09_106 from "./BP09-106";
import c_BP09_107 from "./BP09-107";
import c_BP09_108 from "./BP09-108";
import c_BP09_109 from "./BP09-109";
import c_BP09_110 from "./BP09-110";
import c_BP09_111 from "./BP09-111";
import c_BP09_112 from "./BP09-112";
import c_BP09_113 from "./BP09-113";
import c_BP09_114 from "./BP09-114";
import c_BP09_115 from "./BP09-115";
import c_BP09_116 from "./BP09-116";
import c_BP09_117 from "./BP09-117";
import c_BP09_T01 from "./BP09-T01";
import c_BP09_T02 from "./BP09-T02";

/**
 * Card scripts of BP09, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP09_SCRIPTS: ScriptRegistry = {
  "BP09-001": c_BP09_001,
  "BP09-002": c_BP09_002,
  "BP09-003": c_BP09_003,
  "BP09-004": c_BP09_004,
  "BP09-005": c_BP09_005,
  "BP09-005_back": c_BP09_005_back,
  "BP09-006": c_BP09_006,
  "BP09-007": c_BP09_007,
  "BP09-008": c_BP09_008,
  "BP09-009": c_BP09_009,
  "BP09-010": c_BP09_010,
  "BP09-011": c_BP09_011,
  "BP09-012": c_BP09_012,
  "BP09-013": c_BP09_013,
  "BP09-014": c_BP09_014,
  "BP09-015": c_BP09_015,
  "BP09-016": c_BP09_016,
  "BP09-017": c_BP09_017,
  "BP09-018": c_BP09_018,
  "BP09-019": c_BP09_019,
  "BP09-019_back": c_BP09_019_back,
  "BP09-020": c_BP09_020,
  "BP09-021": c_BP09_021,
  "BP09-022": c_BP09_022,
  "BP09-023": c_BP09_023,
  "BP09-024": c_BP09_024,
  "BP09-025": c_BP09_025,
  "BP09-026": c_BP09_026,
  "BP09-027": c_BP09_027,
  "BP09-028": c_BP09_028,
  "BP09-029": c_BP09_029,
  "BP09-030": c_BP09_030,
  "BP09-031": c_BP09_031,
  "BP09-032": c_BP09_032,
  "BP09-033": c_BP09_033,
  "BP09-034": c_BP09_034,
  "BP09-035": c_BP09_035,
  "BP09-036": c_BP09_036,
  "BP09-037": c_BP09_037,
  "BP09-038": c_BP09_038,
  "BP09-039": c_BP09_039,
  "BP09-039_back": c_BP09_039_back,
  "BP09-040": c_BP09_040,
  "BP09-041": c_BP09_041,
  "BP09-042": c_BP09_042,
  "BP09-043": c_BP09_043,
  "BP09-044": c_BP09_044,
  "BP09-045": c_BP09_045,
  "BP09-046": c_BP09_046,
  "BP09-047": c_BP09_047,
  "BP09-048": c_BP09_048,
  "BP09-049": c_BP09_049,
  "BP09-050": c_BP09_050,
  "BP09-051": c_BP09_051,
  "BP09-052": c_BP09_052,
  "BP09-053": c_BP09_053,
  "BP09-054": c_BP09_054,
  "BP09-055": c_BP09_055,
  "BP09-056": c_BP09_056,
  "BP09-056_back": c_BP09_056_back,
  "BP09-057": c_BP09_057,
  "BP09-058": c_BP09_058,
  "BP09-059": c_BP09_059,
  "BP09-060": c_BP09_060,
  "BP09-061": c_BP09_061,
  "BP09-062": c_BP09_062,
  "BP09-063": c_BP09_063,
  "BP09-064": c_BP09_064,
  "BP09-065": c_BP09_065,
  "BP09-066": c_BP09_066,
  "BP09-067": c_BP09_067,
  "BP09-068": c_BP09_068,
  "BP09-069": c_BP09_069,
  "BP09-070": c_BP09_070,
  "BP09-070_back": c_BP09_070_back,
  "BP09-071": c_BP09_071,
  "BP09-072": c_BP09_072,
  "BP09-073": c_BP09_073,
  "BP09-074": c_BP09_074,
  "BP09-075": c_BP09_075,
  "BP09-076": c_BP09_076,
  "BP09-077": c_BP09_077,
  "BP09-078": c_BP09_078,
  "BP09-079": c_BP09_079,
  "BP09-080": c_BP09_080,
  "BP09-081": c_BP09_081,
  "BP09-082": c_BP09_082,
  "BP09-083": c_BP09_083,
  "BP09-084": c_BP09_084,
  "BP09-085": c_BP09_085,
  "BP09-086": c_BP09_086,
  "BP09-087": c_BP09_087,
  "BP09-088": c_BP09_088,
  "BP09-089": c_BP09_089,
  "BP09-090": c_BP09_090,
  "BP09-090_back": c_BP09_090_back,
  "BP09-091": c_BP09_091,
  "BP09-092": c_BP09_092,
  "BP09-093": c_BP09_093,
  "BP09-094": c_BP09_094,
  "BP09-095": c_BP09_095,
  "BP09-096": c_BP09_096,
  "BP09-097": c_BP09_097,
  "BP09-098": c_BP09_098,
  "BP09-099": c_BP09_099,
  "BP09-100": c_BP09_100,
  "BP09-101": c_BP09_101,
  "BP09-102": c_BP09_102,
  "BP09-103": c_BP09_103,
  "BP09-104": c_BP09_104,
  "BP09-105": c_BP09_105,
  "BP09-106": c_BP09_106,
  "BP09-107": c_BP09_107,
  "BP09-108": c_BP09_108,
  "BP09-109": c_BP09_109,
  "BP09-110": c_BP09_110,
  "BP09-111": c_BP09_111,
  "BP09-112": c_BP09_112,
  "BP09-113": c_BP09_113,
  "BP09-114": c_BP09_114,
  "BP09-115": c_BP09_115,
  "BP09-116": c_BP09_116,
  "BP09-117": c_BP09_117,
  "BP09-T01": c_BP09_T01,
  "BP09-T02": c_BP09_T02,
};
