// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_EBD02_003 from "./EBD02-003";

/**
 * Card scripts of EBD02, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const EBD02_SCRIPTS: ScriptRegistry = {
  "EBD02-003": c_EBD02_003,
};
