// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CSD01_007 from "./CSD01-007";
import c_CSD01_030 from "./CSD01-030";
import c_CSD01_031 from "./CSD01-031";

/**
 * Card scripts of CSD01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CSD01_SCRIPTS: ScriptRegistry = {
  "CSD01-007": c_CSD01_007,
  "CSD01-030": c_CSD01_030,
  "CSD01-031": c_CSD01_031,
};
