// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP08_001 from "./BP08-001";
import c_BP08_002 from "./BP08-002";
import c_BP08_003 from "./BP08-003";
import c_BP08_003_back from "./BP08-003_back";
import c_BP08_004 from "./BP08-004";
import c_BP08_005 from "./BP08-005";
import c_BP08_006 from "./BP08-006";
import c_BP08_007 from "./BP08-007";
import c_BP08_008 from "./BP08-008";
import c_BP08_009 from "./BP08-009";
import c_BP08_010 from "./BP08-010";
import c_BP08_011 from "./BP08-011";
import c_BP08_012 from "./BP08-012";
import c_BP08_013 from "./BP08-013";
import c_BP08_014 from "./BP08-014";
import c_BP08_015 from "./BP08-015";
import c_BP08_016 from "./BP08-016";
import c_BP08_017 from "./BP08-017";
import c_BP08_018 from "./BP08-018";
import c_BP08_019 from "./BP08-019";
import c_BP08_020 from "./BP08-020";
import c_BP08_021 from "./BP08-021";
import c_BP08_022 from "./BP08-022";
import c_BP08_023 from "./BP08-023";
import c_BP08_024 from "./BP08-024";
import c_BP08_025 from "./BP08-025";
import c_BP08_026 from "./BP08-026";
import c_BP08_027 from "./BP08-027";
import c_BP08_028 from "./BP08-028";
import c_BP08_029 from "./BP08-029";
import c_BP08_030 from "./BP08-030";
import c_BP08_031 from "./BP08-031";
import c_BP08_032 from "./BP08-032";
import c_BP08_033 from "./BP08-033";
import c_BP08_034 from "./BP08-034";
import c_BP08_035 from "./BP08-035";
import c_BP08_036 from "./BP08-036";
import c_BP08_037 from "./BP08-037";
import c_BP08_038 from "./BP08-038";
import c_BP08_039 from "./BP08-039";
import c_BP08_040 from "./BP08-040";
import c_BP08_041 from "./BP08-041";
import c_BP08_042 from "./BP08-042";
import c_BP08_043 from "./BP08-043";
import c_BP08_044 from "./BP08-044";
import c_BP08_045 from "./BP08-045";
import c_BP08_046 from "./BP08-046";
import c_BP08_047 from "./BP08-047";
import c_BP08_048 from "./BP08-048";
import c_BP08_049 from "./BP08-049";
import c_BP08_050 from "./BP08-050";
import c_BP08_051 from "./BP08-051";
import c_BP08_052 from "./BP08-052";
import c_BP08_053 from "./BP08-053";
import c_BP08_054 from "./BP08-054";
import c_BP08_055 from "./BP08-055";
import c_BP08_056 from "./BP08-056";
import c_BP08_057 from "./BP08-057";
import c_BP08_058 from "./BP08-058";
import c_BP08_059 from "./BP08-059";
import c_BP08_060 from "./BP08-060";
import c_BP08_061 from "./BP08-061";
import c_BP08_062 from "./BP08-062";
import c_BP08_063 from "./BP08-063";
import c_BP08_064 from "./BP08-064";
import c_BP08_065 from "./BP08-065";
import c_BP08_066 from "./BP08-066";
import c_BP08_067 from "./BP08-067";
import c_BP08_068 from "./BP08-068";
import c_BP08_069 from "./BP08-069";
import c_BP08_070 from "./BP08-070";
import c_BP08_071 from "./BP08-071";
import c_BP08_072 from "./BP08-072";
import c_BP08_073 from "./BP08-073";
import c_BP08_074 from "./BP08-074";
import c_BP08_075 from "./BP08-075";
import c_BP08_076 from "./BP08-076";
import c_BP08_077 from "./BP08-077";
import c_BP08_078 from "./BP08-078";
import c_BP08_079 from "./BP08-079";
import c_BP08_080 from "./BP08-080";
import c_BP08_081 from "./BP08-081";
import c_BP08_082 from "./BP08-082";
import c_BP08_083 from "./BP08-083";
import c_BP08_084 from "./BP08-084";
import c_BP08_085 from "./BP08-085";
import c_BP08_086 from "./BP08-086";
import c_BP08_087 from "./BP08-087";
import c_BP08_088 from "./BP08-088";
import c_BP08_089 from "./BP08-089";
import c_BP08_090 from "./BP08-090";
import c_BP08_091 from "./BP08-091";
import c_BP08_092 from "./BP08-092";
import c_BP08_093 from "./BP08-093";
import c_BP08_094 from "./BP08-094";
import c_BP08_095 from "./BP08-095";
import c_BP08_096 from "./BP08-096";
import c_BP08_097 from "./BP08-097";
import c_BP08_098 from "./BP08-098";
import c_BP08_099 from "./BP08-099";
import c_BP08_100 from "./BP08-100";
import c_BP08_101 from "./BP08-101";
import c_BP08_102 from "./BP08-102";
import c_BP08_103 from "./BP08-103";
import c_BP08_104 from "./BP08-104";
import c_BP08_105 from "./BP08-105";
import c_BP08_106 from "./BP08-106";
import c_BP08_107 from "./BP08-107";
import c_BP08_108 from "./BP08-108";
import c_BP08_109 from "./BP08-109";
import c_BP08_110 from "./BP08-110";
import c_BP08_111 from "./BP08-111";
import c_BP08_112 from "./BP08-112";
import c_BP08_113 from "./BP08-113";
import c_BP08_114 from "./BP08-114";
import c_BP08_115 from "./BP08-115";
import c_BP08_116 from "./BP08-116";
import c_BP08_117 from "./BP08-117";
import c_BP08_T01 from "./BP08-T01";
import c_BP08_T02 from "./BP08-T02";
import c_BP08_T03 from "./BP08-T03";
import c_BP08_U07 from "./BP08-U07";

/**
 * Card scripts of BP08, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP08_SCRIPTS: ScriptRegistry = {
  "BP08-001": c_BP08_001,
  "BP08-002": c_BP08_002,
  "BP08-003": c_BP08_003,
  "BP08-003_back": c_BP08_003_back,
  "BP08-004": c_BP08_004,
  "BP08-005": c_BP08_005,
  "BP08-006": c_BP08_006,
  "BP08-007": c_BP08_007,
  "BP08-008": c_BP08_008,
  "BP08-009": c_BP08_009,
  "BP08-010": c_BP08_010,
  "BP08-011": c_BP08_011,
  "BP08-012": c_BP08_012,
  "BP08-013": c_BP08_013,
  "BP08-014": c_BP08_014,
  "BP08-015": c_BP08_015,
  "BP08-016": c_BP08_016,
  "BP08-017": c_BP08_017,
  "BP08-018": c_BP08_018,
  "BP08-019": c_BP08_019,
  "BP08-020": c_BP08_020,
  "BP08-021": c_BP08_021,
  "BP08-022": c_BP08_022,
  "BP08-023": c_BP08_023,
  "BP08-024": c_BP08_024,
  "BP08-025": c_BP08_025,
  "BP08-026": c_BP08_026,
  "BP08-027": c_BP08_027,
  "BP08-028": c_BP08_028,
  "BP08-029": c_BP08_029,
  "BP08-030": c_BP08_030,
  "BP08-031": c_BP08_031,
  "BP08-032": c_BP08_032,
  "BP08-033": c_BP08_033,
  "BP08-034": c_BP08_034,
  "BP08-035": c_BP08_035,
  "BP08-036": c_BP08_036,
  "BP08-037": c_BP08_037,
  "BP08-038": c_BP08_038,
  "BP08-039": c_BP08_039,
  "BP08-040": c_BP08_040,
  "BP08-041": c_BP08_041,
  "BP08-042": c_BP08_042,
  "BP08-043": c_BP08_043,
  "BP08-044": c_BP08_044,
  "BP08-045": c_BP08_045,
  "BP08-046": c_BP08_046,
  "BP08-047": c_BP08_047,
  "BP08-048": c_BP08_048,
  "BP08-049": c_BP08_049,
  "BP08-050": c_BP08_050,
  "BP08-051": c_BP08_051,
  "BP08-052": c_BP08_052,
  "BP08-053": c_BP08_053,
  "BP08-054": c_BP08_054,
  "BP08-055": c_BP08_055,
  "BP08-056": c_BP08_056,
  "BP08-057": c_BP08_057,
  "BP08-058": c_BP08_058,
  "BP08-059": c_BP08_059,
  "BP08-060": c_BP08_060,
  "BP08-061": c_BP08_061,
  "BP08-062": c_BP08_062,
  "BP08-063": c_BP08_063,
  "BP08-064": c_BP08_064,
  "BP08-065": c_BP08_065,
  "BP08-066": c_BP08_066,
  "BP08-067": c_BP08_067,
  "BP08-068": c_BP08_068,
  "BP08-069": c_BP08_069,
  "BP08-070": c_BP08_070,
  "BP08-071": c_BP08_071,
  "BP08-072": c_BP08_072,
  "BP08-073": c_BP08_073,
  "BP08-074": c_BP08_074,
  "BP08-075": c_BP08_075,
  "BP08-076": c_BP08_076,
  "BP08-077": c_BP08_077,
  "BP08-078": c_BP08_078,
  "BP08-079": c_BP08_079,
  "BP08-080": c_BP08_080,
  "BP08-081": c_BP08_081,
  "BP08-082": c_BP08_082,
  "BP08-083": c_BP08_083,
  "BP08-084": c_BP08_084,
  "BP08-085": c_BP08_085,
  "BP08-086": c_BP08_086,
  "BP08-087": c_BP08_087,
  "BP08-088": c_BP08_088,
  "BP08-089": c_BP08_089,
  "BP08-090": c_BP08_090,
  "BP08-091": c_BP08_091,
  "BP08-092": c_BP08_092,
  "BP08-093": c_BP08_093,
  "BP08-094": c_BP08_094,
  "BP08-095": c_BP08_095,
  "BP08-096": c_BP08_096,
  "BP08-097": c_BP08_097,
  "BP08-098": c_BP08_098,
  "BP08-099": c_BP08_099,
  "BP08-100": c_BP08_100,
  "BP08-101": c_BP08_101,
  "BP08-102": c_BP08_102,
  "BP08-103": c_BP08_103,
  "BP08-104": c_BP08_104,
  "BP08-105": c_BP08_105,
  "BP08-106": c_BP08_106,
  "BP08-107": c_BP08_107,
  "BP08-108": c_BP08_108,
  "BP08-109": c_BP08_109,
  "BP08-110": c_BP08_110,
  "BP08-111": c_BP08_111,
  "BP08-112": c_BP08_112,
  "BP08-113": c_BP08_113,
  "BP08-114": c_BP08_114,
  "BP08-115": c_BP08_115,
  "BP08-116": c_BP08_116,
  "BP08-117": c_BP08_117,
  "BP08-T01": c_BP08_T01,
  "BP08-T02": c_BP08_T02,
  "BP08-T03": c_BP08_T03,
  "BP08-U07": c_BP08_U07,
};
