// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP05_001 from "./BP05-001";
import c_BP05_002 from "./BP05-002";
import c_BP05_003 from "./BP05-003";
import c_BP05_004 from "./BP05-004";
import c_BP05_005 from "./BP05-005";
import c_BP05_006 from "./BP05-006";
import c_BP05_007 from "./BP05-007";
import c_BP05_008 from "./BP05-008";
import c_BP05_009 from "./BP05-009";
import c_BP05_010 from "./BP05-010";
import c_BP05_011 from "./BP05-011";
import c_BP05_012 from "./BP05-012";
import c_BP05_013 from "./BP05-013";
import c_BP05_014 from "./BP05-014";
import c_BP05_015 from "./BP05-015";
import c_BP05_016 from "./BP05-016";
import c_BP05_017 from "./BP05-017";
import c_BP05_018 from "./BP05-018";
import c_BP05_019 from "./BP05-019";
import c_BP05_020 from "./BP05-020";
import c_BP05_021 from "./BP05-021";
import c_BP05_022 from "./BP05-022";
import c_BP05_023 from "./BP05-023";
import c_BP05_024 from "./BP05-024";
import c_BP05_025 from "./BP05-025";
import c_BP05_026 from "./BP05-026";
import c_BP05_027 from "./BP05-027";
import c_BP05_028 from "./BP05-028";
import c_BP05_029 from "./BP05-029";
import c_BP05_030 from "./BP05-030";
import c_BP05_031 from "./BP05-031";
import c_BP05_032 from "./BP05-032";
import c_BP05_033 from "./BP05-033";
import c_BP05_034 from "./BP05-034";
import c_BP05_035 from "./BP05-035";
import c_BP05_036 from "./BP05-036";
import c_BP05_037 from "./BP05-037";
import c_BP05_038 from "./BP05-038";
import c_BP05_039 from "./BP05-039";
import c_BP05_040 from "./BP05-040";
import c_BP05_041 from "./BP05-041";
import c_BP05_042 from "./BP05-042";
import c_BP05_043 from "./BP05-043";
import c_BP05_044 from "./BP05-044";
import c_BP05_045 from "./BP05-045";
import c_BP05_046 from "./BP05-046";
import c_BP05_047 from "./BP05-047";
import c_BP05_048 from "./BP05-048";
import c_BP05_049 from "./BP05-049";
import c_BP05_050 from "./BP05-050";
import c_BP05_051 from "./BP05-051";
import c_BP05_052 from "./BP05-052";
import c_BP05_053 from "./BP05-053";
import c_BP05_054 from "./BP05-054";
import c_BP05_055 from "./BP05-055";
import c_BP05_056 from "./BP05-056";
import c_BP05_057 from "./BP05-057";
import c_BP05_058 from "./BP05-058";
import c_BP05_059 from "./BP05-059";
import c_BP05_060 from "./BP05-060";
import c_BP05_061 from "./BP05-061";
import c_BP05_062 from "./BP05-062";
import c_BP05_063 from "./BP05-063";
import c_BP05_064 from "./BP05-064";
import c_BP05_065 from "./BP05-065";
import c_BP05_066 from "./BP05-066";
import c_BP05_067 from "./BP05-067";
import c_BP05_068 from "./BP05-068";
import c_BP05_069 from "./BP05-069";
import c_BP05_070 from "./BP05-070";
import c_BP05_071 from "./BP05-071";
import c_BP05_072 from "./BP05-072";
import c_BP05_073 from "./BP05-073";
import c_BP05_074 from "./BP05-074";
import c_BP05_075 from "./BP05-075";
import c_BP05_076 from "./BP05-076";
import c_BP05_077 from "./BP05-077";
import c_BP05_078 from "./BP05-078";
import c_BP05_079 from "./BP05-079";
import c_BP05_080 from "./BP05-080";
import c_BP05_081 from "./BP05-081";
import c_BP05_082 from "./BP05-082";
import c_BP05_083 from "./BP05-083";
import c_BP05_084 from "./BP05-084";
import c_BP05_085 from "./BP05-085";
import c_BP05_086 from "./BP05-086";
import c_BP05_087 from "./BP05-087";
import c_BP05_088 from "./BP05-088";
import c_BP05_089 from "./BP05-089";
import c_BP05_090 from "./BP05-090";
import c_BP05_091 from "./BP05-091";
import c_BP05_092 from "./BP05-092";
import c_BP05_093 from "./BP05-093";
import c_BP05_094 from "./BP05-094";
import c_BP05_095 from "./BP05-095";
import c_BP05_096 from "./BP05-096";
import c_BP05_097 from "./BP05-097";
import c_BP05_098 from "./BP05-098";
import c_BP05_099 from "./BP05-099";
import c_BP05_100 from "./BP05-100";
import c_BP05_101 from "./BP05-101";
import c_BP05_102 from "./BP05-102";
import c_BP05_103 from "./BP05-103";
import c_BP05_104 from "./BP05-104";
import c_BP05_105 from "./BP05-105";
import c_BP05_106 from "./BP05-106";
import c_BP05_107 from "./BP05-107";
import c_BP05_108 from "./BP05-108";
import c_BP05_109 from "./BP05-109";
import c_BP05_110 from "./BP05-110";
import c_BP05_111 from "./BP05-111";
import c_BP05_112 from "./BP05-112";
import c_BP05_113 from "./BP05-113";
import c_BP05_114 from "./BP05-114";
import c_BP05_115 from "./BP05-115";
import c_BP05_116 from "./BP05-116";
import c_BP05_117 from "./BP05-117";
import c_BP05_T01 from "./BP05-T01";
import c_BP05_T02 from "./BP05-T02";
import c_BP05_T03 from "./BP05-T03";
import c_BP05_T04 from "./BP05-T04";
import c_BP05_T05 from "./BP05-T05";

/**
 * Card scripts of BP05, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP05_SCRIPTS: ScriptRegistry = {
  "BP05-001": c_BP05_001,
  "BP05-002": c_BP05_002,
  "BP05-003": c_BP05_003,
  "BP05-004": c_BP05_004,
  "BP05-005": c_BP05_005,
  "BP05-006": c_BP05_006,
  "BP05-007": c_BP05_007,
  "BP05-008": c_BP05_008,
  "BP05-009": c_BP05_009,
  "BP05-010": c_BP05_010,
  "BP05-011": c_BP05_011,
  "BP05-012": c_BP05_012,
  "BP05-013": c_BP05_013,
  "BP05-014": c_BP05_014,
  "BP05-015": c_BP05_015,
  "BP05-016": c_BP05_016,
  "BP05-017": c_BP05_017,
  "BP05-018": c_BP05_018,
  "BP05-019": c_BP05_019,
  "BP05-020": c_BP05_020,
  "BP05-021": c_BP05_021,
  "BP05-022": c_BP05_022,
  "BP05-023": c_BP05_023,
  "BP05-024": c_BP05_024,
  "BP05-025": c_BP05_025,
  "BP05-026": c_BP05_026,
  "BP05-027": c_BP05_027,
  "BP05-028": c_BP05_028,
  "BP05-029": c_BP05_029,
  "BP05-030": c_BP05_030,
  "BP05-031": c_BP05_031,
  "BP05-032": c_BP05_032,
  "BP05-033": c_BP05_033,
  "BP05-034": c_BP05_034,
  "BP05-035": c_BP05_035,
  "BP05-036": c_BP05_036,
  "BP05-037": c_BP05_037,
  "BP05-038": c_BP05_038,
  "BP05-039": c_BP05_039,
  "BP05-040": c_BP05_040,
  "BP05-041": c_BP05_041,
  "BP05-042": c_BP05_042,
  "BP05-043": c_BP05_043,
  "BP05-044": c_BP05_044,
  "BP05-045": c_BP05_045,
  "BP05-046": c_BP05_046,
  "BP05-047": c_BP05_047,
  "BP05-048": c_BP05_048,
  "BP05-049": c_BP05_049,
  "BP05-050": c_BP05_050,
  "BP05-051": c_BP05_051,
  "BP05-052": c_BP05_052,
  "BP05-053": c_BP05_053,
  "BP05-054": c_BP05_054,
  "BP05-055": c_BP05_055,
  "BP05-056": c_BP05_056,
  "BP05-057": c_BP05_057,
  "BP05-058": c_BP05_058,
  "BP05-059": c_BP05_059,
  "BP05-060": c_BP05_060,
  "BP05-061": c_BP05_061,
  "BP05-062": c_BP05_062,
  "BP05-063": c_BP05_063,
  "BP05-064": c_BP05_064,
  "BP05-065": c_BP05_065,
  "BP05-066": c_BP05_066,
  "BP05-067": c_BP05_067,
  "BP05-068": c_BP05_068,
  "BP05-069": c_BP05_069,
  "BP05-070": c_BP05_070,
  "BP05-071": c_BP05_071,
  "BP05-072": c_BP05_072,
  "BP05-073": c_BP05_073,
  "BP05-074": c_BP05_074,
  "BP05-075": c_BP05_075,
  "BP05-076": c_BP05_076,
  "BP05-077": c_BP05_077,
  "BP05-078": c_BP05_078,
  "BP05-079": c_BP05_079,
  "BP05-080": c_BP05_080,
  "BP05-081": c_BP05_081,
  "BP05-082": c_BP05_082,
  "BP05-083": c_BP05_083,
  "BP05-084": c_BP05_084,
  "BP05-085": c_BP05_085,
  "BP05-086": c_BP05_086,
  "BP05-087": c_BP05_087,
  "BP05-088": c_BP05_088,
  "BP05-089": c_BP05_089,
  "BP05-090": c_BP05_090,
  "BP05-091": c_BP05_091,
  "BP05-092": c_BP05_092,
  "BP05-093": c_BP05_093,
  "BP05-094": c_BP05_094,
  "BP05-095": c_BP05_095,
  "BP05-096": c_BP05_096,
  "BP05-097": c_BP05_097,
  "BP05-098": c_BP05_098,
  "BP05-099": c_BP05_099,
  "BP05-100": c_BP05_100,
  "BP05-101": c_BP05_101,
  "BP05-102": c_BP05_102,
  "BP05-103": c_BP05_103,
  "BP05-104": c_BP05_104,
  "BP05-105": c_BP05_105,
  "BP05-106": c_BP05_106,
  "BP05-107": c_BP05_107,
  "BP05-108": c_BP05_108,
  "BP05-109": c_BP05_109,
  "BP05-110": c_BP05_110,
  "BP05-111": c_BP05_111,
  "BP05-112": c_BP05_112,
  "BP05-113": c_BP05_113,
  "BP05-114": c_BP05_114,
  "BP05-115": c_BP05_115,
  "BP05-116": c_BP05_116,
  "BP05-117": c_BP05_117,
  "BP05-T01": c_BP05_T01,
  "BP05-T02": c_BP05_T02,
  "BP05-T03": c_BP05_T03,
  "BP05-T04": c_BP05_T04,
  "BP05-T05": c_BP05_T05,
};
