import data from "../../data/BP01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP01_SCRIPTS } from "../script/BP01";

/** BP01 card definitions (generated by `npm run build:cards`). */
export const BP01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP01_SCRIPTS };
