import data from "../../data/BP02.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP02_SCRIPTS } from "../script/BP02";

/**
 * BP02 card definitions (generated by `npm run build:cards`). Its reprinted tokens (Fairy,
 * Knight, Magic Sediment ...) are BP01 definitions, so play with the whole pool (`sets/index.ts`).
 */
export const BP02_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP02_SCRIPTS };
