import data from "../../data/BP03.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP03_SCRIPTS } from "../script/BP03";

/**
 * BP03 card definitions (generated by `npm run build:cards`). Reprinted tokens (Fairy, Ghost,
 * Draconic Weapon ...) stay the earlier set's definitions, so play with the whole pool.
 */
export const BP03_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP03_SCRIPTS };
