import data from "../../data/BP04.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP04_SCRIPTS } from "../script/BP04";

/**
 * BP04 card definitions (generated by `npm run build:cards`). Reprinted tokens (Fairy, Fairy
 * Wisp ...) stay the earlier set's definitions, so play with the whole pool.
 */
export const BP04_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP04_SCRIPTS };
