import data from "../../data/BP05.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP05_SCRIPTS } from "../script/BP05";

/**
 * BP05 card definitions (generated by `npm run build:cards`). Reprinted tokens (Fairy, Fairy
 * Wisp ...) stay the earlier set's definitions, so play with the whole pool.
 */
export const BP05_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP05_SCRIPTS };
