import data from "../../data/BP06.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP06_SCRIPTS } from "../script/BP06";

/**
 * BP06 card definitions (generated by `npm run build:cards`). Reprinted tokens (Fairy, Fairy
 * Wisp ...) stay the earlier set's definitions, so play with the whole pool.
 */
export const BP06_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP06_SCRIPTS };
