import data from "../../data/BP07.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP07_SCRIPTS } from "../script/BP07";

/**
 * BP07 card definitions (generated by `npm run build:cards`). Reprinted tokens (Fairy Wisp, Fairy,
 * Magic Sediment, Ghost) stay the earlier set's definitions, so play with the whole pool.
 */
export const BP07_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP07_SCRIPTS };
