import data from "../../data/BP08.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP08_SCRIPTS } from "../script/BP08";

/**
 * BP08 card definitions (generated by `npm run build:cards`), including the back face of Orchis,
 * Vengeful Puppet (`BP08-003_back`, CR 2.14). Reprinted tokens keep their earlier definitions, so
 * play with the whole pool.
 */
export const BP08_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP08_SCRIPTS };
