import data from "../../data/BP09.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP09_SCRIPTS } from "../script/BP09";

/**
 * BP09 card definitions (generated by `npm run build:cards`), including the back faces of its
 * double-faced evolved cards (`<id>_back`, CR 2.14). Reprinted tokens (Fairy Wisp, Fairy, Knight,
 * Steelclad Knight, Shield Guardian, the Golems, Magic Sediment, Dragon, Megalorca, Ghost, Holy
 * Falcon, Puppet) stay the earlier sets' definitions, so play with the whole pool.
 */
export const BP09_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP09_SCRIPTS };
