import data from "../../data/BP10.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP10_SCRIPTS } from "../script/BP10";

/**
 * BP10 card definitions (generated by `npm run build:cards`), including its advanced cards
 * (CR 9.2), which are built into the evolve deck. Reprinted tokens stay the earlier sets'
 * definitions, so play with the whole pool.
 */
export const BP10_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP10_SCRIPTS };
