import data from "../../data/BP11.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP11_SCRIPTS } from "../script/BP11";

/**
 * BP11 card definitions (generated by `npm run build:cards`), including the amulet tokens that can
 * be maneuvered (CR 5.32). Reprinted cards and tokens stay the earlier sets' definitions, so play
 * with the whole pool.
 */
export const BP11_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP11_SCRIPTS };
