import data from "../../data/BP12.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP12_SCRIPTS } from "../script/BP12";

/**
 * BP12 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP12_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP12_SCRIPTS };
