import data from "../../data/BP15.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP15_SCRIPTS } from "../script/BP15";

/**
 * BP15 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP15_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP15_SCRIPTS };
