import data from "../../data/BP16.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP16_SCRIPTS } from "../script/BP16";

/**
 * BP16 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP16_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP16_SCRIPTS };
