import data from "../../data/BP17.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP17_SCRIPTS } from "../script/BP17";

/**
 * BP17 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP17_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP17_SCRIPTS };
