import data from "../../data/BP18.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP18_SCRIPTS } from "../script/BP18";

/**
 * BP18 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP18_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP18_SCRIPTS };
