import data from "../../data/BP19.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP19_SCRIPTS } from "../script/BP19";

/**
 * BP19 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP19_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP19_SCRIPTS };
