import data from "../../data/BP20.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP20_SCRIPTS } from "../script/BP20";

/**
 * BP20 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP20_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP20_SCRIPTS };
