import data from "../../data/BP21.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP21_SCRIPTS } from "../script/BP21";

/**
 * BP21 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const BP21_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP21_SCRIPTS };
