import data from "../../data/BP22.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { BP22_SCRIPTS } from "../script/BP22";

/**
 * BP22 card definitions (generated by `npm run build:cards` from the pre-release Japanese data, data/preview.ts: their
 * English names and texts are placeholders). Reprinted cards and tokens stay the earlier sets' definitions, so play with
 * the whole pool.
 */
export const BP22_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { BP22_SCRIPTS };
