import data from "../../data/CP01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CP01_SCRIPTS } from "../script/CP01";

/**
 * CP01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CP01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CP01_SCRIPTS };
