import data from "../../data/CP02.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CP02_SCRIPTS } from "../script/CP02";

/**
 * CP02 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CP02_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CP02_SCRIPTS };
