import data from "../../data/CP03.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CP03_SCRIPTS } from "../script/CP03";

/**
 * CP03 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CP03_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CP03_SCRIPTS };
