import data from "../../data/CP04.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CP04_SCRIPTS } from "../script/CP04";

/**
 * CP04 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CP04_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CP04_SCRIPTS };
