import data from "../../data/CSD02a.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CSD02a_SCRIPTS } from "../script/CSD02a";

/**
 * CSD02a card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CSD02a_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CSD02a_SCRIPTS };
