import data from "../../data/CSD02b.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CSD02b_SCRIPTS } from "../script/CSD02b";

/**
 * CSD02b card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CSD02b_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CSD02b_SCRIPTS };
