import data from "../../data/CSD03a.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CSD03a_SCRIPTS } from "../script/CSD03a";

/**
 * CSD03a card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CSD03a_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CSD03a_SCRIPTS };
