import data from "../../data/CSD01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CSD01_SCRIPTS } from "../script/CSD01";

/**
 * CSD01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CSD01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CSD01_SCRIPTS };
