import data from "../../data/CSD03b.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CSD03b_SCRIPTS } from "../script/CSD03b";

/**
 * CSD03b card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CSD03b_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CSD03b_SCRIPTS };
