import data from "../../data/CSD02c.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { CSD02c_SCRIPTS } from "../script/CSD02c";

/**
 * CSD02c card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const CSD02c_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { CSD02c_SCRIPTS };
