import data from "../../data/DSD01a.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { DSD01a_SCRIPTS } from "../script/DSD01a";

/**
 * DSD01a card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const DSD01a_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { DSD01a_SCRIPTS };
