import data from "../../data/DSD01b.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { DSD01b_SCRIPTS } from "../script/DSD01b";

/**
 * DSD01b card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const DSD01b_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { DSD01b_SCRIPTS };
