import data from "../../data/EBD01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { EBD01_SCRIPTS } from "../script/EBD01";

/**
 * EBD01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const EBD01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { EBD01_SCRIPTS };
