import data from "../../data/EBD02.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { EBD02_SCRIPTS } from "../script/EBD02";

/**
 * EBD02 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const EBD02_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { EBD02_SCRIPTS };
