import data from "../../data/EBD04.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { EBD04_SCRIPTS } from "../script/EBD04";

/**
 * EBD04 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const EBD04_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { EBD04_SCRIPTS };
