import data from "../../data/EBD03.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { EBD03_SCRIPTS } from "../script/EBD03";

/**
 * EBD03 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const EBD03_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { EBD03_SCRIPTS };
