import data from "../../data/ECP01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { ECP01_SCRIPTS } from "../script/ECP01";

/**
 * ECP01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const ECP01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { ECP01_SCRIPTS };
