import data from "../../data/ECP02.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { ECP02_SCRIPTS } from "../script/ECP02";

/**
 * ECP02 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const ECP02_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { ECP02_SCRIPTS };
