import data from "../../data/ETD01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { ETD01_SCRIPTS } from "../script/ETD01";

/**
 * ETD01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const ETD01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { ETD01_SCRIPTS };
