import data from "../../data/ETD03.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { ETD03_SCRIPTS } from "../script/ETD03";

/**
 * ETD03 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const ETD03_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { ETD03_SCRIPTS };
