import data from "../../data/ETD02.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { ETD02_SCRIPTS } from "../script/ETD02";

/**
 * ETD02 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const ETD02_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { ETD02_SCRIPTS };
