import data from "../../data/LCS01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { LCS01_SCRIPTS } from "../script/LCS01";

/**
 * LCS01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const LCS01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { LCS01_SCRIPTS };
