import data from "../../data/PCS01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { PCS01_SCRIPTS } from "../script/PCS01";

/**
 * PCS01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const PCS01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { PCS01_SCRIPTS };
