import data from "../../data/PCS02.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { PCS02_SCRIPTS } from "../script/PCS02";

/**
 * PCS02 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const PCS02_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { PCS02_SCRIPTS };
