import data from "../../data/PR.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { PR_SCRIPTS } from "../script/PR";

/**
 * PR card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const PR_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { PR_SCRIPTS };
