import data from "../../data/SCS01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SCS01_SCRIPTS } from "../script/SCS01";

/**
 * SCS01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SCS01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SCS01_SCRIPTS };
