import data from "../../data/SD01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD01_SCRIPTS } from "../script/SD01";

/**
 * SD01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD01_SCRIPTS };
