import data from "../../data/SD02.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD02_SCRIPTS } from "../script/SD02";

/**
 * SD02 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD02_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD02_SCRIPTS };
