import data from "../../data/SD03.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD03_SCRIPTS } from "../script/SD03";

/**
 * SD03 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD03_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD03_SCRIPTS };
