import data from "../../data/SD04.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD04_SCRIPTS } from "../script/SD04";

/**
 * SD04 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD04_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD04_SCRIPTS };
