import data from "../../data/SD05.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD05_SCRIPTS } from "../script/SD05";

/**
 * SD05 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD05_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD05_SCRIPTS };
