import data from "../../data/SD06.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD06_SCRIPTS } from "../script/SD06";

/**
 * SD06 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD06_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD06_SCRIPTS };
