import data from "../../data/SD07.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD07_SCRIPTS } from "../script/SD07";

/**
 * SD07 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD07_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD07_SCRIPTS };
