import data from "../../data/SD08.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SD08_SCRIPTS } from "../script/SD08";

/**
 * SD08 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SD08_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SD08_SCRIPTS };
