import data from "../../data/SP01.json" with { type: "json" };
import { readCardSetFile } from "../data/set-file";
import type { CardDefinition } from "../model/card";
import { SP01_SCRIPTS } from "../script/SP01";

/**
 * SP01 card definitions (generated by `npm run build:cards`). Reprinted cards and tokens stay the
 * earlier sets' definitions, so play with the whole pool.
 */
export const SP01_CARDS: readonly CardDefinition[] = readCardSetFile(data).cards;

export { SP01_SCRIPTS };
