// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD03_001 from "./SD03-001";
import c_SD03_002 from "./SD03-002";
import c_SD03_003 from "./SD03-003";
import c_SD03_004 from "./SD03-004";
import c_SD03_005 from "./SD03-005";
import c_SD03_006 from "./SD03-006";
import c_SD03_008 from "./SD03-008";
import c_SD03_009 from "./SD03-009";
import c_SD03_010 from "./SD03-010";
import c_SD03_011 from "./SD03-011";
import c_SD03_015 from "./SD03-015";
import c_SD03_016 from "./SD03-016";

/**
 * Card scripts of SD03, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD03_SCRIPTS: ScriptRegistry = {
  "SD03-001": c_SD03_001,
  "SD03-002": c_SD03_002,
  "SD03-003": c_SD03_003,
  "SD03-004": c_SD03_004,
  "SD03-005": c_SD03_005,
  "SD03-006": c_SD03_006,
  "SD03-008": c_SD03_008,
  "SD03-009": c_SD03_009,
  "SD03-010": c_SD03_010,
  "SD03-011": c_SD03_011,
  "SD03-015": c_SD03_015,
  "SD03-016": c_SD03_016,
};
