// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_DSD01a_001 from "./DSD01a-001";
import c_DSD01a_002 from "./DSD01a-002";
import c_DSD01a_003 from "./DSD01a-003";
import c_DSD01a_006 from "./DSD01a-006";
import c_DSD01a_008 from "./DSD01a-008";
import c_DSD01a_010 from "./DSD01a-010";
import c_DSD01a_011 from "./DSD01a-011";
import c_DSD01a_014 from "./DSD01a-014";
import c_DSD01a_015 from "./DSD01a-015";
import c_DSD01a_T01 from "./DSD01a-T01";

/**
 * Card scripts of DSD01a, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const DSD01a_SCRIPTS: ScriptRegistry = {
  "DSD01a-001": c_DSD01a_001,
  "DSD01a-002": c_DSD01a_002,
  "DSD01a-003": c_DSD01a_003,
  "DSD01a-006": c_DSD01a_006,
  "DSD01a-008": c_DSD01a_008,
  "DSD01a-010": c_DSD01a_010,
  "DSD01a-011": c_DSD01a_011,
  "DSD01a-014": c_DSD01a_014,
  "DSD01a-015": c_DSD01a_015,
  "DSD01a-T01": c_DSD01a_T01,
};
