// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CP01_001 from "./CP01-001";
import c_CP01_002 from "./CP01-002";
import c_CP01_003 from "./CP01-003";
import c_CP01_004 from "./CP01-004";
import c_CP01_005 from "./CP01-005";
import c_CP01_006 from "./CP01-006";
import c_CP01_007 from "./CP01-007";
import c_CP01_008 from "./CP01-008";
import c_CP01_009 from "./CP01-009";
import c_CP01_010 from "./CP01-010";
import c_CP01_011 from "./CP01-011";
import c_CP01_012 from "./CP01-012";
import c_CP01_013 from "./CP01-013";
import c_CP01_014 from "./CP01-014";
import c_CP01_015 from "./CP01-015";
import c_CP01_016 from "./CP01-016";
import c_CP01_017 from "./CP01-017";
import c_CP01_018 from "./CP01-018";
import c_CP01_019 from "./CP01-019";
import c_CP01_020 from "./CP01-020";
import c_CP01_021 from "./CP01-021";
import c_CP01_022 from "./CP01-022";
import c_CP01_023 from "./CP01-023";
import c_CP01_024 from "./CP01-024";
import c_CP01_025 from "./CP01-025";
import c_CP01_026 from "./CP01-026";
import c_CP01_027 from "./CP01-027";
import c_CP01_028 from "./CP01-028";
import c_CP01_029 from "./CP01-029";
import c_CP01_030 from "./CP01-030";
import c_CP01_031 from "./CP01-031";
import c_CP01_032 from "./CP01-032";
import c_CP01_033 from "./CP01-033";
import c_CP01_034 from "./CP01-034";
import c_CP01_035 from "./CP01-035";
import c_CP01_036 from "./CP01-036";
import c_CP01_037 from "./CP01-037";
import c_CP01_038 from "./CP01-038";
import c_CP01_039 from "./CP01-039";
import c_CP01_040 from "./CP01-040";
import c_CP01_041 from "./CP01-041";
import c_CP01_042 from "./CP01-042";
import c_CP01_043 from "./CP01-043";
import c_CP01_044 from "./CP01-044";
import c_CP01_045 from "./CP01-045";
import c_CP01_046 from "./CP01-046";
import c_CP01_047 from "./CP01-047";
import c_CP01_048 from "./CP01-048";
import c_CP01_049 from "./CP01-049";
import c_CP01_050 from "./CP01-050";
import c_CP01_051 from "./CP01-051";
import c_CP01_052 from "./CP01-052";
import c_CP01_053 from "./CP01-053";
import c_CP01_054 from "./CP01-054";
import c_CP01_055 from "./CP01-055";
import c_CP01_056 from "./CP01-056";
import c_CP01_057 from "./CP01-057";
import c_CP01_058 from "./CP01-058";
import c_CP01_059 from "./CP01-059";
import c_CP01_060 from "./CP01-060";
import c_CP01_061 from "./CP01-061";
import c_CP01_062 from "./CP01-062";
import c_CP01_063 from "./CP01-063";
import c_CP01_064 from "./CP01-064";
import c_CP01_065 from "./CP01-065";
import c_CP01_066 from "./CP01-066";
import c_CP01_067 from "./CP01-067";
import c_CP01_068 from "./CP01-068";
import c_CP01_069 from "./CP01-069";
import c_CP01_070 from "./CP01-070";
import c_CP01_071 from "./CP01-071";
import c_CP01_072 from "./CP01-072";
import c_CP01_073 from "./CP01-073";
import c_CP01_074 from "./CP01-074";
import c_CP01_075 from "./CP01-075";
import c_CP01_076 from "./CP01-076";
import c_CP01_077 from "./CP01-077";
import c_CP01_078 from "./CP01-078";
import c_CP01_079 from "./CP01-079";
import c_CP01_080 from "./CP01-080";
import c_CP01_081 from "./CP01-081";
import c_CP01_082 from "./CP01-082";
import c_CP01_083 from "./CP01-083";
import c_CP01_084 from "./CP01-084";
import c_CP01_085 from "./CP01-085";

/**
 * Card scripts of CP01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CP01_SCRIPTS: ScriptRegistry = {
  "CP01-001": c_CP01_001,
  "CP01-002": c_CP01_002,
  "CP01-003": c_CP01_003,
  "CP01-004": c_CP01_004,
  "CP01-005": c_CP01_005,
  "CP01-006": c_CP01_006,
  "CP01-007": c_CP01_007,
  "CP01-008": c_CP01_008,
  "CP01-009": c_CP01_009,
  "CP01-010": c_CP01_010,
  "CP01-011": c_CP01_011,
  "CP01-012": c_CP01_012,
  "CP01-013": c_CP01_013,
  "CP01-014": c_CP01_014,
  "CP01-015": c_CP01_015,
  "CP01-016": c_CP01_016,
  "CP01-017": c_CP01_017,
  "CP01-018": c_CP01_018,
  "CP01-019": c_CP01_019,
  "CP01-020": c_CP01_020,
  "CP01-021": c_CP01_021,
  "CP01-022": c_CP01_022,
  "CP01-023": c_CP01_023,
  "CP01-024": c_CP01_024,
  "CP01-025": c_CP01_025,
  "CP01-026": c_CP01_026,
  "CP01-027": c_CP01_027,
  "CP01-028": c_CP01_028,
  "CP01-029": c_CP01_029,
  "CP01-030": c_CP01_030,
  "CP01-031": c_CP01_031,
  "CP01-032": c_CP01_032,
  "CP01-033": c_CP01_033,
  "CP01-034": c_CP01_034,
  "CP01-035": c_CP01_035,
  "CP01-036": c_CP01_036,
  "CP01-037": c_CP01_037,
  "CP01-038": c_CP01_038,
  "CP01-039": c_CP01_039,
  "CP01-040": c_CP01_040,
  "CP01-041": c_CP01_041,
  "CP01-042": c_CP01_042,
  "CP01-043": c_CP01_043,
  "CP01-044": c_CP01_044,
  "CP01-045": c_CP01_045,
  "CP01-046": c_CP01_046,
  "CP01-047": c_CP01_047,
  "CP01-048": c_CP01_048,
  "CP01-049": c_CP01_049,
  "CP01-050": c_CP01_050,
  "CP01-051": c_CP01_051,
  "CP01-052": c_CP01_052,
  "CP01-053": c_CP01_053,
  "CP01-054": c_CP01_054,
  "CP01-055": c_CP01_055,
  "CP01-056": c_CP01_056,
  "CP01-057": c_CP01_057,
  "CP01-058": c_CP01_058,
  "CP01-059": c_CP01_059,
  "CP01-060": c_CP01_060,
  "CP01-061": c_CP01_061,
  "CP01-062": c_CP01_062,
  "CP01-063": c_CP01_063,
  "CP01-064": c_CP01_064,
  "CP01-065": c_CP01_065,
  "CP01-066": c_CP01_066,
  "CP01-067": c_CP01_067,
  "CP01-068": c_CP01_068,
  "CP01-069": c_CP01_069,
  "CP01-070": c_CP01_070,
  "CP01-071": c_CP01_071,
  "CP01-072": c_CP01_072,
  "CP01-073": c_CP01_073,
  "CP01-074": c_CP01_074,
  "CP01-075": c_CP01_075,
  "CP01-076": c_CP01_076,
  "CP01-077": c_CP01_077,
  "CP01-078": c_CP01_078,
  "CP01-079": c_CP01_079,
  "CP01-080": c_CP01_080,
  "CP01-081": c_CP01_081,
  "CP01-082": c_CP01_082,
  "CP01-083": c_CP01_083,
  "CP01-084": c_CP01_084,
  "CP01-085": c_CP01_085,
};
