// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CP03_001 from "./CP03-001";
import c_CP03_002 from "./CP03-002";
import c_CP03_003 from "./CP03-003";
import c_CP03_004 from "./CP03-004";
import c_CP03_005 from "./CP03-005";
import c_CP03_006 from "./CP03-006";
import c_CP03_007 from "./CP03-007";
import c_CP03_008 from "./CP03-008";
import c_CP03_009 from "./CP03-009";
import c_CP03_010 from "./CP03-010";
import c_CP03_011 from "./CP03-011";
import c_CP03_012 from "./CP03-012";
import c_CP03_013 from "./CP03-013";
import c_CP03_014 from "./CP03-014";
import c_CP03_015 from "./CP03-015";
import c_CP03_016 from "./CP03-016";
import c_CP03_017 from "./CP03-017";
import c_CP03_018 from "./CP03-018";
import c_CP03_019 from "./CP03-019";
import c_CP03_020 from "./CP03-020";
import c_CP03_021 from "./CP03-021";
import c_CP03_022 from "./CP03-022";
import c_CP03_023 from "./CP03-023";
import c_CP03_024 from "./CP03-024";
import c_CP03_025 from "./CP03-025";
import c_CP03_026 from "./CP03-026";
import c_CP03_027 from "./CP03-027";
import c_CP03_028 from "./CP03-028";
import c_CP03_029 from "./CP03-029";
import c_CP03_030 from "./CP03-030";
import c_CP03_031 from "./CP03-031";
import c_CP03_032 from "./CP03-032";
import c_CP03_033 from "./CP03-033";
import c_CP03_034 from "./CP03-034";
import c_CP03_035 from "./CP03-035";
import c_CP03_036 from "./CP03-036";
import c_CP03_037 from "./CP03-037";
import c_CP03_038 from "./CP03-038";
import c_CP03_039 from "./CP03-039";
import c_CP03_040 from "./CP03-040";
import c_CP03_041 from "./CP03-041";
import c_CP03_042 from "./CP03-042";
import c_CP03_043 from "./CP03-043";
import c_CP03_044 from "./CP03-044";
import c_CP03_045 from "./CP03-045";
import c_CP03_046 from "./CP03-046";
import c_CP03_047 from "./CP03-047";
import c_CP03_048 from "./CP03-048";
import c_CP03_049 from "./CP03-049";
import c_CP03_050 from "./CP03-050";
import c_CP03_051 from "./CP03-051";
import c_CP03_052 from "./CP03-052";
import c_CP03_053 from "./CP03-053";
import c_CP03_054 from "./CP03-054";
import c_CP03_055 from "./CP03-055";
import c_CP03_056 from "./CP03-056";
import c_CP03_057 from "./CP03-057";
import c_CP03_058 from "./CP03-058";
import c_CP03_059 from "./CP03-059";
import c_CP03_060 from "./CP03-060";
import c_CP03_061 from "./CP03-061";
import c_CP03_062 from "./CP03-062";
import c_CP03_063 from "./CP03-063";
import c_CP03_064 from "./CP03-064";
import c_CP03_065 from "./CP03-065";
import c_CP03_066 from "./CP03-066";
import c_CP03_067 from "./CP03-067";
import c_CP03_068 from "./CP03-068";
import c_CP03_069 from "./CP03-069";
import c_CP03_070 from "./CP03-070";
import c_CP03_071 from "./CP03-071";
import c_CP03_072 from "./CP03-072";
import c_CP03_073 from "./CP03-073";
import c_CP03_074 from "./CP03-074";
import c_CP03_075 from "./CP03-075";
import c_CP03_076 from "./CP03-076";
import c_CP03_077 from "./CP03-077";
import c_CP03_078 from "./CP03-078";
import c_CP03_079 from "./CP03-079";
import c_CP03_080 from "./CP03-080";
import c_CP03_081 from "./CP03-081";
import c_CP03_082 from "./CP03-082";
import c_CP03_083 from "./CP03-083";
import c_CP03_084 from "./CP03-084";
import c_CP03_085 from "./CP03-085";
import c_CP03_086 from "./CP03-086";
import c_CP03_087 from "./CP03-087";
import c_CP03_088 from "./CP03-088";
import c_CP03_089 from "./CP03-089";
import c_CP03_090 from "./CP03-090";
import c_CP03_091 from "./CP03-091";
import c_CP03_092 from "./CP03-092";
import c_CP03_093 from "./CP03-093";
import c_CP03_094 from "./CP03-094";
import c_CP03_095 from "./CP03-095";
import c_CP03_096 from "./CP03-096";
import c_CP03_097 from "./CP03-097";
import c_CP03_098 from "./CP03-098";
import c_CP03_099 from "./CP03-099";
import c_CP03_100 from "./CP03-100";
import c_CP03_101 from "./CP03-101";
import c_CP03_102 from "./CP03-102";
import c_CP03_103 from "./CP03-103";
import c_CP03_104 from "./CP03-104";
import c_CP03_105 from "./CP03-105";
import c_CP03_106 from "./CP03-106";
import c_CP03_107 from "./CP03-107";
import c_CP03_108 from "./CP03-108";
import c_CP03_109 from "./CP03-109";
import c_CP03_110 from "./CP03-110";
import c_CP03_111 from "./CP03-111";
import c_CP03_112 from "./CP03-112";
import c_CP03_113 from "./CP03-113";
import c_CP03_114 from "./CP03-114";
import c_CP03_115 from "./CP03-115";
import c_CP03_116 from "./CP03-116";
import c_CP03_117 from "./CP03-117";
import c_CP03_118 from "./CP03-118";
import c_CP03_119 from "./CP03-119";
import c_CP03_120 from "./CP03-120";
import c_CP03_121 from "./CP03-121";
import c_CP03_122 from "./CP03-122";
import c_CP03_123 from "./CP03-123";
import c_CP03_124 from "./CP03-124";
import c_CP03_125 from "./CP03-125";
import c_CP03_127 from "./CP03-127";

/**
 * Card scripts of CP03, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CP03_SCRIPTS: ScriptRegistry = {
  "CP03-001": c_CP03_001,
  "CP03-002": c_CP03_002,
  "CP03-003": c_CP03_003,
  "CP03-004": c_CP03_004,
  "CP03-005": c_CP03_005,
  "CP03-006": c_CP03_006,
  "CP03-007": c_CP03_007,
  "CP03-008": c_CP03_008,
  "CP03-009": c_CP03_009,
  "CP03-010": c_CP03_010,
  "CP03-011": c_CP03_011,
  "CP03-012": c_CP03_012,
  "CP03-013": c_CP03_013,
  "CP03-014": c_CP03_014,
  "CP03-015": c_CP03_015,
  "CP03-016": c_CP03_016,
  "CP03-017": c_CP03_017,
  "CP03-018": c_CP03_018,
  "CP03-019": c_CP03_019,
  "CP03-020": c_CP03_020,
  "CP03-021": c_CP03_021,
  "CP03-022": c_CP03_022,
  "CP03-023": c_CP03_023,
  "CP03-024": c_CP03_024,
  "CP03-025": c_CP03_025,
  "CP03-026": c_CP03_026,
  "CP03-027": c_CP03_027,
  "CP03-028": c_CP03_028,
  "CP03-029": c_CP03_029,
  "CP03-030": c_CP03_030,
  "CP03-031": c_CP03_031,
  "CP03-032": c_CP03_032,
  "CP03-033": c_CP03_033,
  "CP03-034": c_CP03_034,
  "CP03-035": c_CP03_035,
  "CP03-036": c_CP03_036,
  "CP03-037": c_CP03_037,
  "CP03-038": c_CP03_038,
  "CP03-039": c_CP03_039,
  "CP03-040": c_CP03_040,
  "CP03-041": c_CP03_041,
  "CP03-042": c_CP03_042,
  "CP03-043": c_CP03_043,
  "CP03-044": c_CP03_044,
  "CP03-045": c_CP03_045,
  "CP03-046": c_CP03_046,
  "CP03-047": c_CP03_047,
  "CP03-048": c_CP03_048,
  "CP03-049": c_CP03_049,
  "CP03-050": c_CP03_050,
  "CP03-051": c_CP03_051,
  "CP03-052": c_CP03_052,
  "CP03-053": c_CP03_053,
  "CP03-054": c_CP03_054,
  "CP03-055": c_CP03_055,
  "CP03-056": c_CP03_056,
  "CP03-057": c_CP03_057,
  "CP03-058": c_CP03_058,
  "CP03-059": c_CP03_059,
  "CP03-060": c_CP03_060,
  "CP03-061": c_CP03_061,
  "CP03-062": c_CP03_062,
  "CP03-063": c_CP03_063,
  "CP03-064": c_CP03_064,
  "CP03-065": c_CP03_065,
  "CP03-066": c_CP03_066,
  "CP03-067": c_CP03_067,
  "CP03-068": c_CP03_068,
  "CP03-069": c_CP03_069,
  "CP03-070": c_CP03_070,
  "CP03-071": c_CP03_071,
  "CP03-072": c_CP03_072,
  "CP03-073": c_CP03_073,
  "CP03-074": c_CP03_074,
  "CP03-075": c_CP03_075,
  "CP03-076": c_CP03_076,
  "CP03-077": c_CP03_077,
  "CP03-078": c_CP03_078,
  "CP03-079": c_CP03_079,
  "CP03-080": c_CP03_080,
  "CP03-081": c_CP03_081,
  "CP03-082": c_CP03_082,
  "CP03-083": c_CP03_083,
  "CP03-084": c_CP03_084,
  "CP03-085": c_CP03_085,
  "CP03-086": c_CP03_086,
  "CP03-087": c_CP03_087,
  "CP03-088": c_CP03_088,
  "CP03-089": c_CP03_089,
  "CP03-090": c_CP03_090,
  "CP03-091": c_CP03_091,
  "CP03-092": c_CP03_092,
  "CP03-093": c_CP03_093,
  "CP03-094": c_CP03_094,
  "CP03-095": c_CP03_095,
  "CP03-096": c_CP03_096,
  "CP03-097": c_CP03_097,
  "CP03-098": c_CP03_098,
  "CP03-099": c_CP03_099,
  "CP03-100": c_CP03_100,
  "CP03-101": c_CP03_101,
  "CP03-102": c_CP03_102,
  "CP03-103": c_CP03_103,
  "CP03-104": c_CP03_104,
  "CP03-105": c_CP03_105,
  "CP03-106": c_CP03_106,
  "CP03-107": c_CP03_107,
  "CP03-108": c_CP03_108,
  "CP03-109": c_CP03_109,
  "CP03-110": c_CP03_110,
  "CP03-111": c_CP03_111,
  "CP03-112": c_CP03_112,
  "CP03-113": c_CP03_113,
  "CP03-114": c_CP03_114,
  "CP03-115": c_CP03_115,
  "CP03-116": c_CP03_116,
  "CP03-117": c_CP03_117,
  "CP03-118": c_CP03_118,
  "CP03-119": c_CP03_119,
  "CP03-120": c_CP03_120,
  "CP03-121": c_CP03_121,
  "CP03-122": c_CP03_122,
  "CP03-123": c_CP03_123,
  "CP03-124": c_CP03_124,
  "CP03-125": c_CP03_125,
  "CP03-127": c_CP03_127,
};
