// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD07_012 from "./SD07-012";

/**
 * Card scripts of SD07, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD07_SCRIPTS: ScriptRegistry = {
  "SD07-012": c_SD07_012,
};
