// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP22_001 from "./BP22-001";
import c_BP22_002 from "./BP22-002";
import c_BP22_003 from "./BP22-003";
import c_BP22_004 from "./BP22-004";
import c_BP22_005 from "./BP22-005";
import c_BP22_006 from "./BP22-006";
import c_BP22_007 from "./BP22-007";
import c_BP22_008 from "./BP22-008";
import c_BP22_009 from "./BP22-009";
import c_BP22_010 from "./BP22-010";
import c_BP22_011 from "./BP22-011";
import c_BP22_012 from "./BP22-012";
import c_BP22_013 from "./BP22-013";
import c_BP22_014 from "./BP22-014";
import c_BP22_015 from "./BP22-015";
import c_BP22_016 from "./BP22-016";
import c_BP22_017 from "./BP22-017";
import c_BP22_018 from "./BP22-018";
import c_BP22_019 from "./BP22-019";
import c_BP22_020 from "./BP22-020";
import c_BP22_021 from "./BP22-021";
import c_BP22_022 from "./BP22-022";
import c_BP22_023 from "./BP22-023";
import c_BP22_024 from "./BP22-024";
import c_BP22_025 from "./BP22-025";
import c_BP22_026 from "./BP22-026";
import c_BP22_027 from "./BP22-027";
import c_BP22_028 from "./BP22-028";
import c_BP22_029 from "./BP22-029";
import c_BP22_030 from "./BP22-030";
import c_BP22_031 from "./BP22-031";
import c_BP22_032 from "./BP22-032";
import c_BP22_033 from "./BP22-033";
import c_BP22_034 from "./BP22-034";
import c_BP22_035 from "./BP22-035";
import c_BP22_036 from "./BP22-036";
import c_BP22_037 from "./BP22-037";
import c_BP22_038 from "./BP22-038";
import c_BP22_039 from "./BP22-039";
import c_BP22_040 from "./BP22-040";
import c_BP22_041 from "./BP22-041";
import c_BP22_042 from "./BP22-042";
import c_BP22_043 from "./BP22-043";
import c_BP22_044 from "./BP22-044";
import c_BP22_045 from "./BP22-045";
import c_BP22_046 from "./BP22-046";
import c_BP22_047 from "./BP22-047";
import c_BP22_048 from "./BP22-048";
import c_BP22_049 from "./BP22-049";
import c_BP22_050 from "./BP22-050";
import c_BP22_051 from "./BP22-051";
import c_BP22_052 from "./BP22-052";
import c_BP22_053 from "./BP22-053";
import c_BP22_054 from "./BP22-054";
import c_BP22_055 from "./BP22-055";
import c_BP22_056 from "./BP22-056";
import c_BP22_057 from "./BP22-057";
import c_BP22_058 from "./BP22-058";
import c_BP22_059 from "./BP22-059";
import c_BP22_060 from "./BP22-060";
import c_BP22_061 from "./BP22-061";
import c_BP22_062 from "./BP22-062";
import c_BP22_063 from "./BP22-063";
import c_BP22_064 from "./BP22-064";
import c_BP22_065 from "./BP22-065";
import c_BP22_066 from "./BP22-066";
import c_BP22_067 from "./BP22-067";
import c_BP22_068 from "./BP22-068";
import c_BP22_069 from "./BP22-069";
import c_BP22_070 from "./BP22-070";
import c_BP22_071 from "./BP22-071";
import c_BP22_072 from "./BP22-072";
import c_BP22_073 from "./BP22-073";
import c_BP22_074 from "./BP22-074";
import c_BP22_075 from "./BP22-075";
import c_BP22_076 from "./BP22-076";
import c_BP22_077 from "./BP22-077";
import c_BP22_078 from "./BP22-078";
import c_BP22_079 from "./BP22-079";
import c_BP22_080 from "./BP22-080";
import c_BP22_081 from "./BP22-081";
import c_BP22_082 from "./BP22-082";
import c_BP22_083 from "./BP22-083";
import c_BP22_084 from "./BP22-084";
import c_BP22_085 from "./BP22-085";
import c_BP22_086 from "./BP22-086";
import c_BP22_087 from "./BP22-087";
import c_BP22_088 from "./BP22-088";
import c_BP22_089 from "./BP22-089";
import c_BP22_090 from "./BP22-090";
import c_BP22_091 from "./BP22-091";
import c_BP22_092 from "./BP22-092";
import c_BP22_093 from "./BP22-093";
import c_BP22_094 from "./BP22-094";
import c_BP22_095 from "./BP22-095";
import c_BP22_096 from "./BP22-096";
import c_BP22_097 from "./BP22-097";
import c_BP22_098 from "./BP22-098";
import c_BP22_099 from "./BP22-099";
import c_BP22_100 from "./BP22-100";
import c_BP22_101 from "./BP22-101";
import c_BP22_102 from "./BP22-102";
import c_BP22_103 from "./BP22-103";
import c_BP22_104 from "./BP22-104";
import c_BP22_106 from "./BP22-106";
import c_BP22_107 from "./BP22-107";
import c_BP22_108 from "./BP22-108";
import c_BP22_109 from "./BP22-109";
import c_BP22_110 from "./BP22-110";
import c_BP22_111 from "./BP22-111";
import c_BP22_112 from "./BP22-112";
import c_BP22_113 from "./BP22-113";
import c_BP22_114 from "./BP22-114";
import c_BP22_115 from "./BP22-115";
import c_BP22_116 from "./BP22-116";
import c_BP22_117 from "./BP22-117";
import c_BP22_118 from "./BP22-118";
import c_BP22_T01 from "./BP22-T01";
import c_BP22_T02 from "./BP22-T02";
import c_BP22_T03 from "./BP22-T03";

/**
 * Card scripts of BP22, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP22_SCRIPTS: ScriptRegistry = {
  "BP22-001": c_BP22_001,
  "BP22-002": c_BP22_002,
  "BP22-003": c_BP22_003,
  "BP22-004": c_BP22_004,
  "BP22-005": c_BP22_005,
  "BP22-006": c_BP22_006,
  "BP22-007": c_BP22_007,
  "BP22-008": c_BP22_008,
  "BP22-009": c_BP22_009,
  "BP22-010": c_BP22_010,
  "BP22-011": c_BP22_011,
  "BP22-012": c_BP22_012,
  "BP22-013": c_BP22_013,
  "BP22-014": c_BP22_014,
  "BP22-015": c_BP22_015,
  "BP22-016": c_BP22_016,
  "BP22-017": c_BP22_017,
  "BP22-018": c_BP22_018,
  "BP22-019": c_BP22_019,
  "BP22-020": c_BP22_020,
  "BP22-021": c_BP22_021,
  "BP22-022": c_BP22_022,
  "BP22-023": c_BP22_023,
  "BP22-024": c_BP22_024,
  "BP22-025": c_BP22_025,
  "BP22-026": c_BP22_026,
  "BP22-027": c_BP22_027,
  "BP22-028": c_BP22_028,
  "BP22-029": c_BP22_029,
  "BP22-030": c_BP22_030,
  "BP22-031": c_BP22_031,
  "BP22-032": c_BP22_032,
  "BP22-033": c_BP22_033,
  "BP22-034": c_BP22_034,
  "BP22-035": c_BP22_035,
  "BP22-036": c_BP22_036,
  "BP22-037": c_BP22_037,
  "BP22-038": c_BP22_038,
  "BP22-039": c_BP22_039,
  "BP22-040": c_BP22_040,
  "BP22-041": c_BP22_041,
  "BP22-042": c_BP22_042,
  "BP22-043": c_BP22_043,
  "BP22-044": c_BP22_044,
  "BP22-045": c_BP22_045,
  "BP22-046": c_BP22_046,
  "BP22-047": c_BP22_047,
  "BP22-048": c_BP22_048,
  "BP22-049": c_BP22_049,
  "BP22-050": c_BP22_050,
  "BP22-051": c_BP22_051,
  "BP22-052": c_BP22_052,
  "BP22-053": c_BP22_053,
  "BP22-054": c_BP22_054,
  "BP22-055": c_BP22_055,
  "BP22-056": c_BP22_056,
  "BP22-057": c_BP22_057,
  "BP22-058": c_BP22_058,
  "BP22-059": c_BP22_059,
  "BP22-060": c_BP22_060,
  "BP22-061": c_BP22_061,
  "BP22-062": c_BP22_062,
  "BP22-063": c_BP22_063,
  "BP22-064": c_BP22_064,
  "BP22-065": c_BP22_065,
  "BP22-066": c_BP22_066,
  "BP22-067": c_BP22_067,
  "BP22-068": c_BP22_068,
  "BP22-069": c_BP22_069,
  "BP22-070": c_BP22_070,
  "BP22-071": c_BP22_071,
  "BP22-072": c_BP22_072,
  "BP22-073": c_BP22_073,
  "BP22-074": c_BP22_074,
  "BP22-075": c_BP22_075,
  "BP22-076": c_BP22_076,
  "BP22-077": c_BP22_077,
  "BP22-078": c_BP22_078,
  "BP22-079": c_BP22_079,
  "BP22-080": c_BP22_080,
  "BP22-081": c_BP22_081,
  "BP22-082": c_BP22_082,
  "BP22-083": c_BP22_083,
  "BP22-084": c_BP22_084,
  "BP22-085": c_BP22_085,
  "BP22-086": c_BP22_086,
  "BP22-087": c_BP22_087,
  "BP22-088": c_BP22_088,
  "BP22-089": c_BP22_089,
  "BP22-090": c_BP22_090,
  "BP22-091": c_BP22_091,
  "BP22-092": c_BP22_092,
  "BP22-093": c_BP22_093,
  "BP22-094": c_BP22_094,
  "BP22-095": c_BP22_095,
  "BP22-096": c_BP22_096,
  "BP22-097": c_BP22_097,
  "BP22-098": c_BP22_098,
  "BP22-099": c_BP22_099,
  "BP22-100": c_BP22_100,
  "BP22-101": c_BP22_101,
  "BP22-102": c_BP22_102,
  "BP22-103": c_BP22_103,
  "BP22-104": c_BP22_104,
  "BP22-106": c_BP22_106,
  "BP22-107": c_BP22_107,
  "BP22-108": c_BP22_108,
  "BP22-109": c_BP22_109,
  "BP22-110": c_BP22_110,
  "BP22-111": c_BP22_111,
  "BP22-112": c_BP22_112,
  "BP22-113": c_BP22_113,
  "BP22-114": c_BP22_114,
  "BP22-115": c_BP22_115,
  "BP22-116": c_BP22_116,
  "BP22-117": c_BP22_117,
  "BP22-118": c_BP22_118,
  "BP22-T01": c_BP22_T01,
  "BP22-T02": c_BP22_T02,
  "BP22-T03": c_BP22_T03,
};
