// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP22_001 from "./BP22-001";
import c_BP22_002 from "./BP22-002";
import c_BP22_003 from "./BP22-003";
import c_BP22_004 from "./BP22-004";
import c_BP22_005 from "./BP22-005";
import c_BP22_006 from "./BP22-006";
import c_BP22_007 from "./BP22-007";
import c_BP22_008 from "./BP22-008";
import c_BP22_009 from "./BP22-009";
import c_BP22_010 from "./BP22-010";
import c_BP22_011 from "./BP22-011";
import c_BP22_012 from "./BP22-012";
import c_BP22_013 from "./BP22-013";
import c_BP22_014 from "./BP22-014";
import c_BP22_015 from "./BP22-015";
import c_BP22_016 from "./BP22-016";
import c_BP22_017 from "./BP22-017";
import c_BP22_018 from "./BP22-018";
import c_BP22_019 from "./BP22-019";
import c_BP22_020 from "./BP22-020";
import c_BP22_021 from "./BP22-021";
import c_BP22_022 from "./BP22-022";
import c_BP22_023 from "./BP22-023";
import c_BP22_024 from "./BP22-024";
import c_BP22_025 from "./BP22-025";
import c_BP22_026 from "./BP22-026";
import c_BP22_027 from "./BP22-027";
import c_BP22_028 from "./BP22-028";
import c_BP22_029 from "./BP22-029";
import c_BP22_030 from "./BP22-030";
import c_BP22_031 from "./BP22-031";
import c_BP22_032 from "./BP22-032";
import c_BP22_033 from "./BP22-033";
import c_BP22_034 from "./BP22-034";
import c_BP22_035 from "./BP22-035";
import c_BP22_036 from "./BP22-036";
import c_BP22_037 from "./BP22-037";
import c_BP22_038 from "./BP22-038";
import c_BP22_039 from "./BP22-039";
import c_BP22_040 from "./BP22-040";
import c_BP22_041 from "./BP22-041";
import c_BP22_042 from "./BP22-042";
import c_BP22_043 from "./BP22-043";
import c_BP22_044 from "./BP22-044";
import c_BP22_045 from "./BP22-045";
import c_BP22_046 from "./BP22-046";
import c_BP22_047 from "./BP22-047";
import c_BP22_048 from "./BP22-048";
import c_BP22_049 from "./BP22-049";
import c_BP22_050 from "./BP22-050";
import c_BP22_051 from "./BP22-051";
import c_BP22_052 from "./BP22-052";
import c_BP22_053 from "./BP22-053";
import c_BP22_054 from "./BP22-054";
import c_BP22_055 from "./BP22-055";
import c_BP22_116 from "./BP22-116";
import c_BP22_T02 from "./BP22-T02";
import c_BP22_T03 from "./BP22-T03";

/**
 * Card scripts of BP22, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP22_SCRIPTS: ScriptRegistry = {
  "BP22-001": c_BP22_001,
  "BP22-002": c_BP22_002,
  "BP22-003": c_BP22_003,
  "BP22-004": c_BP22_004,
  "BP22-005": c_BP22_005,
  "BP22-006": c_BP22_006,
  "BP22-007": c_BP22_007,
  "BP22-008": c_BP22_008,
  "BP22-009": c_BP22_009,
  "BP22-010": c_BP22_010,
  "BP22-011": c_BP22_011,
  "BP22-012": c_BP22_012,
  "BP22-013": c_BP22_013,
  "BP22-014": c_BP22_014,
  "BP22-015": c_BP22_015,
  "BP22-016": c_BP22_016,
  "BP22-017": c_BP22_017,
  "BP22-018": c_BP22_018,
  "BP22-019": c_BP22_019,
  "BP22-020": c_BP22_020,
  "BP22-021": c_BP22_021,
  "BP22-022": c_BP22_022,
  "BP22-023": c_BP22_023,
  "BP22-024": c_BP22_024,
  "BP22-025": c_BP22_025,
  "BP22-026": c_BP22_026,
  "BP22-027": c_BP22_027,
  "BP22-028": c_BP22_028,
  "BP22-029": c_BP22_029,
  "BP22-030": c_BP22_030,
  "BP22-031": c_BP22_031,
  "BP22-032": c_BP22_032,
  "BP22-033": c_BP22_033,
  "BP22-034": c_BP22_034,
  "BP22-035": c_BP22_035,
  "BP22-036": c_BP22_036,
  "BP22-037": c_BP22_037,
  "BP22-038": c_BP22_038,
  "BP22-039": c_BP22_039,
  "BP22-040": c_BP22_040,
  "BP22-041": c_BP22_041,
  "BP22-042": c_BP22_042,
  "BP22-043": c_BP22_043,
  "BP22-044": c_BP22_044,
  "BP22-045": c_BP22_045,
  "BP22-046": c_BP22_046,
  "BP22-047": c_BP22_047,
  "BP22-048": c_BP22_048,
  "BP22-049": c_BP22_049,
  "BP22-050": c_BP22_050,
  "BP22-051": c_BP22_051,
  "BP22-052": c_BP22_052,
  "BP22-053": c_BP22_053,
  "BP22-054": c_BP22_054,
  "BP22-055": c_BP22_055,
  "BP22-116": c_BP22_116,
  "BP22-T02": c_BP22_T02,
  "BP22-T03": c_BP22_T03,
};
