// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP10_001 from "./BP10-001";
import c_BP10_002 from "./BP10-002";
import c_BP10_003 from "./BP10-003";
import c_BP10_004 from "./BP10-004";
import c_BP10_005 from "./BP10-005";
import c_BP10_006 from "./BP10-006";
import c_BP10_007 from "./BP10-007";
import c_BP10_008 from "./BP10-008";
import c_BP10_009 from "./BP10-009";
import c_BP10_010 from "./BP10-010";
import c_BP10_011 from "./BP10-011";
import c_BP10_012 from "./BP10-012";
import c_BP10_013 from "./BP10-013";
import c_BP10_014 from "./BP10-014";
import c_BP10_015 from "./BP10-015";
import c_BP10_016 from "./BP10-016";
import c_BP10_017 from "./BP10-017";
import c_BP10_018 from "./BP10-018";
import c_BP10_019 from "./BP10-019";
import c_BP10_020 from "./BP10-020";
import c_BP10_021 from "./BP10-021";
import c_BP10_022 from "./BP10-022";
import c_BP10_023 from "./BP10-023";
import c_BP10_024 from "./BP10-024";
import c_BP10_025 from "./BP10-025";
import c_BP10_026 from "./BP10-026";
import c_BP10_027 from "./BP10-027";
import c_BP10_028 from "./BP10-028";
import c_BP10_029 from "./BP10-029";
import c_BP10_030 from "./BP10-030";
import c_BP10_031 from "./BP10-031";
import c_BP10_032 from "./BP10-032";
import c_BP10_033 from "./BP10-033";
import c_BP10_034 from "./BP10-034";
import c_BP10_035 from "./BP10-035";
import c_BP10_036 from "./BP10-036";
import c_BP10_037 from "./BP10-037";
import c_BP10_038 from "./BP10-038";
import c_BP10_039 from "./BP10-039";
import c_BP10_040 from "./BP10-040";
import c_BP10_041 from "./BP10-041";
import c_BP10_042 from "./BP10-042";
import c_BP10_043 from "./BP10-043";
import c_BP10_044 from "./BP10-044";
import c_BP10_045 from "./BP10-045";
import c_BP10_046 from "./BP10-046";
import c_BP10_047 from "./BP10-047";
import c_BP10_048 from "./BP10-048";
import c_BP10_049 from "./BP10-049";
import c_BP10_050 from "./BP10-050";
import c_BP10_051 from "./BP10-051";
import c_BP10_052 from "./BP10-052";
import c_BP10_053 from "./BP10-053";
import c_BP10_054 from "./BP10-054";
import c_BP10_055 from "./BP10-055";
import c_BP10_056 from "./BP10-056";
import c_BP10_057 from "./BP10-057";
import c_BP10_058 from "./BP10-058";
import c_BP10_059 from "./BP10-059";
import c_BP10_060 from "./BP10-060";
import c_BP10_061 from "./BP10-061";
import c_BP10_062 from "./BP10-062";
import c_BP10_063 from "./BP10-063";
import c_BP10_064 from "./BP10-064";
import c_BP10_065 from "./BP10-065";
import c_BP10_066 from "./BP10-066";
import c_BP10_067 from "./BP10-067";
import c_BP10_068 from "./BP10-068";
import c_BP10_069 from "./BP10-069";
import c_BP10_070 from "./BP10-070";
import c_BP10_071 from "./BP10-071";
import c_BP10_072 from "./BP10-072";
import c_BP10_073 from "./BP10-073";
import c_BP10_074 from "./BP10-074";
import c_BP10_075 from "./BP10-075";
import c_BP10_076 from "./BP10-076";
import c_BP10_077 from "./BP10-077";
import c_BP10_078 from "./BP10-078";
import c_BP10_079 from "./BP10-079";
import c_BP10_080 from "./BP10-080";
import c_BP10_081 from "./BP10-081";
import c_BP10_082 from "./BP10-082";
import c_BP10_083 from "./BP10-083";
import c_BP10_084 from "./BP10-084";
import c_BP10_085 from "./BP10-085";
import c_BP10_086 from "./BP10-086";
import c_BP10_087 from "./BP10-087";
import c_BP10_088 from "./BP10-088";
import c_BP10_089 from "./BP10-089";
import c_BP10_090 from "./BP10-090";
import c_BP10_091 from "./BP10-091";
import c_BP10_092 from "./BP10-092";
import c_BP10_093 from "./BP10-093";
import c_BP10_094 from "./BP10-094";
import c_BP10_095 from "./BP10-095";
import c_BP10_096 from "./BP10-096";
import c_BP10_097 from "./BP10-097";
import c_BP10_098 from "./BP10-098";
import c_BP10_099 from "./BP10-099";
import c_BP10_100 from "./BP10-100";
import c_BP10_101 from "./BP10-101";
import c_BP10_102 from "./BP10-102";
import c_BP10_103 from "./BP10-103";
import c_BP10_104 from "./BP10-104";
import c_BP10_105 from "./BP10-105";
import c_BP10_106 from "./BP10-106";
import c_BP10_107 from "./BP10-107";
import c_BP10_108 from "./BP10-108";
import c_BP10_109 from "./BP10-109";
import c_BP10_110 from "./BP10-110";
import c_BP10_111 from "./BP10-111";
import c_BP10_112 from "./BP10-112";
import c_BP10_113 from "./BP10-113";
import c_BP10_114 from "./BP10-114";
import c_BP10_115 from "./BP10-115";
import c_BP10_116 from "./BP10-116";
import c_BP10_117 from "./BP10-117";
import c_BP10_118 from "./BP10-118";
import c_BP10_119 from "./BP10-119";
import c_BP10_120 from "./BP10-120";
import c_BP10_121 from "./BP10-121";
import c_BP10_122 from "./BP10-122";
import c_BP10_T01 from "./BP10-T01";
import c_BP10_T02 from "./BP10-T02";

/**
 * Card scripts of BP10, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP10_SCRIPTS: ScriptRegistry = {
  "BP10-001": c_BP10_001,
  "BP10-002": c_BP10_002,
  "BP10-003": c_BP10_003,
  "BP10-004": c_BP10_004,
  "BP10-005": c_BP10_005,
  "BP10-006": c_BP10_006,
  "BP10-007": c_BP10_007,
  "BP10-008": c_BP10_008,
  "BP10-009": c_BP10_009,
  "BP10-010": c_BP10_010,
  "BP10-011": c_BP10_011,
  "BP10-012": c_BP10_012,
  "BP10-013": c_BP10_013,
  "BP10-014": c_BP10_014,
  "BP10-015": c_BP10_015,
  "BP10-016": c_BP10_016,
  "BP10-017": c_BP10_017,
  "BP10-018": c_BP10_018,
  "BP10-019": c_BP10_019,
  "BP10-020": c_BP10_020,
  "BP10-021": c_BP10_021,
  "BP10-022": c_BP10_022,
  "BP10-023": c_BP10_023,
  "BP10-024": c_BP10_024,
  "BP10-025": c_BP10_025,
  "BP10-026": c_BP10_026,
  "BP10-027": c_BP10_027,
  "BP10-028": c_BP10_028,
  "BP10-029": c_BP10_029,
  "BP10-030": c_BP10_030,
  "BP10-031": c_BP10_031,
  "BP10-032": c_BP10_032,
  "BP10-033": c_BP10_033,
  "BP10-034": c_BP10_034,
  "BP10-035": c_BP10_035,
  "BP10-036": c_BP10_036,
  "BP10-037": c_BP10_037,
  "BP10-038": c_BP10_038,
  "BP10-039": c_BP10_039,
  "BP10-040": c_BP10_040,
  "BP10-041": c_BP10_041,
  "BP10-042": c_BP10_042,
  "BP10-043": c_BP10_043,
  "BP10-044": c_BP10_044,
  "BP10-045": c_BP10_045,
  "BP10-046": c_BP10_046,
  "BP10-047": c_BP10_047,
  "BP10-048": c_BP10_048,
  "BP10-049": c_BP10_049,
  "BP10-050": c_BP10_050,
  "BP10-051": c_BP10_051,
  "BP10-052": c_BP10_052,
  "BP10-053": c_BP10_053,
  "BP10-054": c_BP10_054,
  "BP10-055": c_BP10_055,
  "BP10-056": c_BP10_056,
  "BP10-057": c_BP10_057,
  "BP10-058": c_BP10_058,
  "BP10-059": c_BP10_059,
  "BP10-060": c_BP10_060,
  "BP10-061": c_BP10_061,
  "BP10-062": c_BP10_062,
  "BP10-063": c_BP10_063,
  "BP10-064": c_BP10_064,
  "BP10-065": c_BP10_065,
  "BP10-066": c_BP10_066,
  "BP10-067": c_BP10_067,
  "BP10-068": c_BP10_068,
  "BP10-069": c_BP10_069,
  "BP10-070": c_BP10_070,
  "BP10-071": c_BP10_071,
  "BP10-072": c_BP10_072,
  "BP10-073": c_BP10_073,
  "BP10-074": c_BP10_074,
  "BP10-075": c_BP10_075,
  "BP10-076": c_BP10_076,
  "BP10-077": c_BP10_077,
  "BP10-078": c_BP10_078,
  "BP10-079": c_BP10_079,
  "BP10-080": c_BP10_080,
  "BP10-081": c_BP10_081,
  "BP10-082": c_BP10_082,
  "BP10-083": c_BP10_083,
  "BP10-084": c_BP10_084,
  "BP10-085": c_BP10_085,
  "BP10-086": c_BP10_086,
  "BP10-087": c_BP10_087,
  "BP10-088": c_BP10_088,
  "BP10-089": c_BP10_089,
  "BP10-090": c_BP10_090,
  "BP10-091": c_BP10_091,
  "BP10-092": c_BP10_092,
  "BP10-093": c_BP10_093,
  "BP10-094": c_BP10_094,
  "BP10-095": c_BP10_095,
  "BP10-096": c_BP10_096,
  "BP10-097": c_BP10_097,
  "BP10-098": c_BP10_098,
  "BP10-099": c_BP10_099,
  "BP10-100": c_BP10_100,
  "BP10-101": c_BP10_101,
  "BP10-102": c_BP10_102,
  "BP10-103": c_BP10_103,
  "BP10-104": c_BP10_104,
  "BP10-105": c_BP10_105,
  "BP10-106": c_BP10_106,
  "BP10-107": c_BP10_107,
  "BP10-108": c_BP10_108,
  "BP10-109": c_BP10_109,
  "BP10-110": c_BP10_110,
  "BP10-111": c_BP10_111,
  "BP10-112": c_BP10_112,
  "BP10-113": c_BP10_113,
  "BP10-114": c_BP10_114,
  "BP10-115": c_BP10_115,
  "BP10-116": c_BP10_116,
  "BP10-117": c_BP10_117,
  "BP10-118": c_BP10_118,
  "BP10-119": c_BP10_119,
  "BP10-120": c_BP10_120,
  "BP10-121": c_BP10_121,
  "BP10-122": c_BP10_122,
  "BP10-T01": c_BP10_T01,
  "BP10-T02": c_BP10_T02,
};
