// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP20_001 from "./BP20-001";
import c_BP20_002 from "./BP20-002";
import c_BP20_003 from "./BP20-003";
import c_BP20_004 from "./BP20-004";
import c_BP20_005 from "./BP20-005";
import c_BP20_006 from "./BP20-006";
import c_BP20_007 from "./BP20-007";
import c_BP20_008 from "./BP20-008";
import c_BP20_009 from "./BP20-009";
import c_BP20_010 from "./BP20-010";
import c_BP20_011 from "./BP20-011";
import c_BP20_012 from "./BP20-012";
import c_BP20_013 from "./BP20-013";
import c_BP20_014 from "./BP20-014";
import c_BP20_015 from "./BP20-015";
import c_BP20_016 from "./BP20-016";
import c_BP20_017 from "./BP20-017";
import c_BP20_018 from "./BP20-018";
import c_BP20_019 from "./BP20-019";
import c_BP20_020 from "./BP20-020";
import c_BP20_021 from "./BP20-021";
import c_BP20_022 from "./BP20-022";
import c_BP20_023 from "./BP20-023";
import c_BP20_024 from "./BP20-024";
import c_BP20_025 from "./BP20-025";
import c_BP20_026 from "./BP20-026";
import c_BP20_027 from "./BP20-027";
import c_BP20_028 from "./BP20-028";
import c_BP20_029 from "./BP20-029";
import c_BP20_030 from "./BP20-030";
import c_BP20_031 from "./BP20-031";
import c_BP20_032 from "./BP20-032";
import c_BP20_033 from "./BP20-033";
import c_BP20_034 from "./BP20-034";
import c_BP20_035 from "./BP20-035";
import c_BP20_036 from "./BP20-036";
import c_BP20_037 from "./BP20-037";
import c_BP20_038 from "./BP20-038";
import c_BP20_039 from "./BP20-039";
import c_BP20_040 from "./BP20-040";
import c_BP20_041 from "./BP20-041";
import c_BP20_042 from "./BP20-042";
import c_BP20_043 from "./BP20-043";
import c_BP20_044 from "./BP20-044";
import c_BP20_045 from "./BP20-045";
import c_BP20_046 from "./BP20-046";
import c_BP20_047 from "./BP20-047";
import c_BP20_048 from "./BP20-048";
import c_BP20_049 from "./BP20-049";
import c_BP20_050 from "./BP20-050";
import c_BP20_051 from "./BP20-051";
import c_BP20_052 from "./BP20-052";
import c_BP20_053 from "./BP20-053";
import c_BP20_054 from "./BP20-054";
import c_BP20_055 from "./BP20-055";
import c_BP20_056 from "./BP20-056";
import c_BP20_057 from "./BP20-057";
import c_BP20_058 from "./BP20-058";
import c_BP20_059 from "./BP20-059";
import c_BP20_060 from "./BP20-060";
import c_BP20_061 from "./BP20-061";
import c_BP20_062 from "./BP20-062";
import c_BP20_063 from "./BP20-063";
import c_BP20_064 from "./BP20-064";
import c_BP20_065 from "./BP20-065";
import c_BP20_066 from "./BP20-066";
import c_BP20_067 from "./BP20-067";
import c_BP20_068 from "./BP20-068";
import c_BP20_069 from "./BP20-069";
import c_BP20_070 from "./BP20-070";
import c_BP20_071 from "./BP20-071";
import c_BP20_072 from "./BP20-072";
import c_BP20_073 from "./BP20-073";
import c_BP20_074 from "./BP20-074";
import c_BP20_075 from "./BP20-075";
import c_BP20_076 from "./BP20-076";
import c_BP20_077 from "./BP20-077";
import c_BP20_078 from "./BP20-078";
import c_BP20_079 from "./BP20-079";
import c_BP20_080 from "./BP20-080";
import c_BP20_081 from "./BP20-081";
import c_BP20_082 from "./BP20-082";
import c_BP20_083 from "./BP20-083";
import c_BP20_084 from "./BP20-084";
import c_BP20_085 from "./BP20-085";
import c_BP20_086 from "./BP20-086";
import c_BP20_087 from "./BP20-087";
import c_BP20_088 from "./BP20-088";
import c_BP20_089 from "./BP20-089";
import c_BP20_090 from "./BP20-090";
import c_BP20_091 from "./BP20-091";
import c_BP20_092 from "./BP20-092";
import c_BP20_093 from "./BP20-093";
import c_BP20_094 from "./BP20-094";
import c_BP20_095 from "./BP20-095";
import c_BP20_096 from "./BP20-096";
import c_BP20_097 from "./BP20-097";
import c_BP20_098 from "./BP20-098";
import c_BP20_099 from "./BP20-099";
import c_BP20_100 from "./BP20-100";
import c_BP20_101 from "./BP20-101";
import c_BP20_102 from "./BP20-102";
import c_BP20_103 from "./BP20-103";
import c_BP20_104 from "./BP20-104";
import c_BP20_105 from "./BP20-105";
import c_BP20_106 from "./BP20-106";
import c_BP20_107 from "./BP20-107";
import c_BP20_108 from "./BP20-108";
import c_BP20_109 from "./BP20-109";
import c_BP20_110 from "./BP20-110";
import c_BP20_111 from "./BP20-111";
import c_BP20_112 from "./BP20-112";
import c_BP20_113 from "./BP20-113";
import c_BP20_114 from "./BP20-114";
import c_BP20_115 from "./BP20-115";
import c_BP20_116 from "./BP20-116";
import c_BP20_117 from "./BP20-117";
import c_BP20_118 from "./BP20-118";
import c_BP20_119 from "./BP20-119";
import c_BP20_120 from "./BP20-120";
import c_BP20_T01 from "./BP20-T01";
import c_BP20_T02 from "./BP20-T02";
import c_BP20_T03 from "./BP20-T03";
import c_BP20_T04 from "./BP20-T04";
import c_BP20_T05 from "./BP20-T05";
import c_BP20_T06 from "./BP20-T06";
import c_BP20_T07 from "./BP20-T07";
import c_BP20_T08 from "./BP20-T08";
import c_BP20_T09 from "./BP20-T09";
import c_BP20_T10 from "./BP20-T10";
import c_BP20_T11 from "./BP20-T11";

/**
 * Card scripts of BP20, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP20_SCRIPTS: ScriptRegistry = {
  "BP20-001": c_BP20_001,
  "BP20-002": c_BP20_002,
  "BP20-003": c_BP20_003,
  "BP20-004": c_BP20_004,
  "BP20-005": c_BP20_005,
  "BP20-006": c_BP20_006,
  "BP20-007": c_BP20_007,
  "BP20-008": c_BP20_008,
  "BP20-009": c_BP20_009,
  "BP20-010": c_BP20_010,
  "BP20-011": c_BP20_011,
  "BP20-012": c_BP20_012,
  "BP20-013": c_BP20_013,
  "BP20-014": c_BP20_014,
  "BP20-015": c_BP20_015,
  "BP20-016": c_BP20_016,
  "BP20-017": c_BP20_017,
  "BP20-018": c_BP20_018,
  "BP20-019": c_BP20_019,
  "BP20-020": c_BP20_020,
  "BP20-021": c_BP20_021,
  "BP20-022": c_BP20_022,
  "BP20-023": c_BP20_023,
  "BP20-024": c_BP20_024,
  "BP20-025": c_BP20_025,
  "BP20-026": c_BP20_026,
  "BP20-027": c_BP20_027,
  "BP20-028": c_BP20_028,
  "BP20-029": c_BP20_029,
  "BP20-030": c_BP20_030,
  "BP20-031": c_BP20_031,
  "BP20-032": c_BP20_032,
  "BP20-033": c_BP20_033,
  "BP20-034": c_BP20_034,
  "BP20-035": c_BP20_035,
  "BP20-036": c_BP20_036,
  "BP20-037": c_BP20_037,
  "BP20-038": c_BP20_038,
  "BP20-039": c_BP20_039,
  "BP20-040": c_BP20_040,
  "BP20-041": c_BP20_041,
  "BP20-042": c_BP20_042,
  "BP20-043": c_BP20_043,
  "BP20-044": c_BP20_044,
  "BP20-045": c_BP20_045,
  "BP20-046": c_BP20_046,
  "BP20-047": c_BP20_047,
  "BP20-048": c_BP20_048,
  "BP20-049": c_BP20_049,
  "BP20-050": c_BP20_050,
  "BP20-051": c_BP20_051,
  "BP20-052": c_BP20_052,
  "BP20-053": c_BP20_053,
  "BP20-054": c_BP20_054,
  "BP20-055": c_BP20_055,
  "BP20-056": c_BP20_056,
  "BP20-057": c_BP20_057,
  "BP20-058": c_BP20_058,
  "BP20-059": c_BP20_059,
  "BP20-060": c_BP20_060,
  "BP20-061": c_BP20_061,
  "BP20-062": c_BP20_062,
  "BP20-063": c_BP20_063,
  "BP20-064": c_BP20_064,
  "BP20-065": c_BP20_065,
  "BP20-066": c_BP20_066,
  "BP20-067": c_BP20_067,
  "BP20-068": c_BP20_068,
  "BP20-069": c_BP20_069,
  "BP20-070": c_BP20_070,
  "BP20-071": c_BP20_071,
  "BP20-072": c_BP20_072,
  "BP20-073": c_BP20_073,
  "BP20-074": c_BP20_074,
  "BP20-075": c_BP20_075,
  "BP20-076": c_BP20_076,
  "BP20-077": c_BP20_077,
  "BP20-078": c_BP20_078,
  "BP20-079": c_BP20_079,
  "BP20-080": c_BP20_080,
  "BP20-081": c_BP20_081,
  "BP20-082": c_BP20_082,
  "BP20-083": c_BP20_083,
  "BP20-084": c_BP20_084,
  "BP20-085": c_BP20_085,
  "BP20-086": c_BP20_086,
  "BP20-087": c_BP20_087,
  "BP20-088": c_BP20_088,
  "BP20-089": c_BP20_089,
  "BP20-090": c_BP20_090,
  "BP20-091": c_BP20_091,
  "BP20-092": c_BP20_092,
  "BP20-093": c_BP20_093,
  "BP20-094": c_BP20_094,
  "BP20-095": c_BP20_095,
  "BP20-096": c_BP20_096,
  "BP20-097": c_BP20_097,
  "BP20-098": c_BP20_098,
  "BP20-099": c_BP20_099,
  "BP20-100": c_BP20_100,
  "BP20-101": c_BP20_101,
  "BP20-102": c_BP20_102,
  "BP20-103": c_BP20_103,
  "BP20-104": c_BP20_104,
  "BP20-105": c_BP20_105,
  "BP20-106": c_BP20_106,
  "BP20-107": c_BP20_107,
  "BP20-108": c_BP20_108,
  "BP20-109": c_BP20_109,
  "BP20-110": c_BP20_110,
  "BP20-111": c_BP20_111,
  "BP20-112": c_BP20_112,
  "BP20-113": c_BP20_113,
  "BP20-114": c_BP20_114,
  "BP20-115": c_BP20_115,
  "BP20-116": c_BP20_116,
  "BP20-117": c_BP20_117,
  "BP20-118": c_BP20_118,
  "BP20-119": c_BP20_119,
  "BP20-120": c_BP20_120,
  "BP20-T01": c_BP20_T01,
  "BP20-T02": c_BP20_T02,
  "BP20-T03": c_BP20_T03,
  "BP20-T04": c_BP20_T04,
  "BP20-T05": c_BP20_T05,
  "BP20-T06": c_BP20_T06,
  "BP20-T07": c_BP20_T07,
  "BP20-T08": c_BP20_T08,
  "BP20-T09": c_BP20_T09,
  "BP20-T10": c_BP20_T10,
  "BP20-T11": c_BP20_T11,
};
