// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP19_001 from "./BP19-001";
import c_BP19_002 from "./BP19-002";
import c_BP19_003 from "./BP19-003";
import c_BP19_004 from "./BP19-004";
import c_BP19_005 from "./BP19-005";
import c_BP19_006 from "./BP19-006";
import c_BP19_007 from "./BP19-007";
import c_BP19_008 from "./BP19-008";
import c_BP19_009 from "./BP19-009";
import c_BP19_010 from "./BP19-010";
import c_BP19_011 from "./BP19-011";
import c_BP19_012 from "./BP19-012";
import c_BP19_013 from "./BP19-013";
import c_BP19_014 from "./BP19-014";
import c_BP19_015 from "./BP19-015";
import c_BP19_016 from "./BP19-016";
import c_BP19_017 from "./BP19-017";
import c_BP19_018 from "./BP19-018";
import c_BP19_019 from "./BP19-019";
import c_BP19_020 from "./BP19-020";
import c_BP19_021 from "./BP19-021";
import c_BP19_022 from "./BP19-022";
import c_BP19_023 from "./BP19-023";
import c_BP19_024 from "./BP19-024";
import c_BP19_025 from "./BP19-025";
import c_BP19_026 from "./BP19-026";
import c_BP19_027 from "./BP19-027";
import c_BP19_028 from "./BP19-028";
import c_BP19_029 from "./BP19-029";
import c_BP19_030 from "./BP19-030";
import c_BP19_031 from "./BP19-031";
import c_BP19_032 from "./BP19-032";
import c_BP19_033 from "./BP19-033";
import c_BP19_034 from "./BP19-034";
import c_BP19_035 from "./BP19-035";
import c_BP19_036 from "./BP19-036";
import c_BP19_037 from "./BP19-037";
import c_BP19_038 from "./BP19-038";
import c_BP19_039 from "./BP19-039";
import c_BP19_040 from "./BP19-040";
import c_BP19_041 from "./BP19-041";
import c_BP19_042 from "./BP19-042";
import c_BP19_043 from "./BP19-043";
import c_BP19_044 from "./BP19-044";
import c_BP19_045 from "./BP19-045";
import c_BP19_046 from "./BP19-046";
import c_BP19_047 from "./BP19-047";
import c_BP19_048 from "./BP19-048";
import c_BP19_049 from "./BP19-049";
import c_BP19_050 from "./BP19-050";
import c_BP19_051 from "./BP19-051";
import c_BP19_052 from "./BP19-052";
import c_BP19_053 from "./BP19-053";
import c_BP19_054 from "./BP19-054";
import c_BP19_055 from "./BP19-055";
import c_BP19_056 from "./BP19-056";
import c_BP19_057 from "./BP19-057";
import c_BP19_058 from "./BP19-058";
import c_BP19_059 from "./BP19-059";
import c_BP19_060 from "./BP19-060";
import c_BP19_061 from "./BP19-061";
import c_BP19_062 from "./BP19-062";
import c_BP19_063 from "./BP19-063";
import c_BP19_064 from "./BP19-064";
import c_BP19_065 from "./BP19-065";
import c_BP19_066 from "./BP19-066";
import c_BP19_067 from "./BP19-067";
import c_BP19_068 from "./BP19-068";
import c_BP19_069 from "./BP19-069";
import c_BP19_070 from "./BP19-070";
import c_BP19_071 from "./BP19-071";
import c_BP19_072 from "./BP19-072";
import c_BP19_073 from "./BP19-073";
import c_BP19_074 from "./BP19-074";
import c_BP19_075 from "./BP19-075";
import c_BP19_076 from "./BP19-076";
import c_BP19_077 from "./BP19-077";
import c_BP19_078 from "./BP19-078";
import c_BP19_079 from "./BP19-079";
import c_BP19_080 from "./BP19-080";
import c_BP19_081 from "./BP19-081";
import c_BP19_082 from "./BP19-082";
import c_BP19_083 from "./BP19-083";
import c_BP19_084 from "./BP19-084";
import c_BP19_085 from "./BP19-085";
import c_BP19_086 from "./BP19-086";
import c_BP19_087 from "./BP19-087";
import c_BP19_088 from "./BP19-088";
import c_BP19_089 from "./BP19-089";
import c_BP19_090 from "./BP19-090";
import c_BP19_091 from "./BP19-091";
import c_BP19_092 from "./BP19-092";
import c_BP19_093 from "./BP19-093";
import c_BP19_094 from "./BP19-094";
import c_BP19_095 from "./BP19-095";
import c_BP19_096 from "./BP19-096";
import c_BP19_097 from "./BP19-097";
import c_BP19_098 from "./BP19-098";
import c_BP19_099 from "./BP19-099";
import c_BP19_100 from "./BP19-100";
import c_BP19_101 from "./BP19-101";
import c_BP19_102 from "./BP19-102";
import c_BP19_103 from "./BP19-103";
import c_BP19_104 from "./BP19-104";
import c_BP19_105 from "./BP19-105";
import c_BP19_106 from "./BP19-106";
import c_BP19_107 from "./BP19-107";
import c_BP19_108 from "./BP19-108";
import c_BP19_109 from "./BP19-109";
import c_BP19_110 from "./BP19-110";
import c_BP19_111 from "./BP19-111";
import c_BP19_112 from "./BP19-112";
import c_BP19_113 from "./BP19-113";
import c_BP19_114 from "./BP19-114";
import c_BP19_115 from "./BP19-115";
import c_BP19_116 from "./BP19-116";
import c_BP19_117 from "./BP19-117";
import c_BP19_118 from "./BP19-118";
import c_BP19_119 from "./BP19-119";
import c_BP19_120 from "./BP19-120";
import c_BP19_T01 from "./BP19-T01";
import c_BP19_T02 from "./BP19-T02";

/**
 * Card scripts of BP19, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP19_SCRIPTS: ScriptRegistry = {
  "BP19-001": c_BP19_001,
  "BP19-002": c_BP19_002,
  "BP19-003": c_BP19_003,
  "BP19-004": c_BP19_004,
  "BP19-005": c_BP19_005,
  "BP19-006": c_BP19_006,
  "BP19-007": c_BP19_007,
  "BP19-008": c_BP19_008,
  "BP19-009": c_BP19_009,
  "BP19-010": c_BP19_010,
  "BP19-011": c_BP19_011,
  "BP19-012": c_BP19_012,
  "BP19-013": c_BP19_013,
  "BP19-014": c_BP19_014,
  "BP19-015": c_BP19_015,
  "BP19-016": c_BP19_016,
  "BP19-017": c_BP19_017,
  "BP19-018": c_BP19_018,
  "BP19-019": c_BP19_019,
  "BP19-020": c_BP19_020,
  "BP19-021": c_BP19_021,
  "BP19-022": c_BP19_022,
  "BP19-023": c_BP19_023,
  "BP19-024": c_BP19_024,
  "BP19-025": c_BP19_025,
  "BP19-026": c_BP19_026,
  "BP19-027": c_BP19_027,
  "BP19-028": c_BP19_028,
  "BP19-029": c_BP19_029,
  "BP19-030": c_BP19_030,
  "BP19-031": c_BP19_031,
  "BP19-032": c_BP19_032,
  "BP19-033": c_BP19_033,
  "BP19-034": c_BP19_034,
  "BP19-035": c_BP19_035,
  "BP19-036": c_BP19_036,
  "BP19-037": c_BP19_037,
  "BP19-038": c_BP19_038,
  "BP19-039": c_BP19_039,
  "BP19-040": c_BP19_040,
  "BP19-041": c_BP19_041,
  "BP19-042": c_BP19_042,
  "BP19-043": c_BP19_043,
  "BP19-044": c_BP19_044,
  "BP19-045": c_BP19_045,
  "BP19-046": c_BP19_046,
  "BP19-047": c_BP19_047,
  "BP19-048": c_BP19_048,
  "BP19-049": c_BP19_049,
  "BP19-050": c_BP19_050,
  "BP19-051": c_BP19_051,
  "BP19-052": c_BP19_052,
  "BP19-053": c_BP19_053,
  "BP19-054": c_BP19_054,
  "BP19-055": c_BP19_055,
  "BP19-056": c_BP19_056,
  "BP19-057": c_BP19_057,
  "BP19-058": c_BP19_058,
  "BP19-059": c_BP19_059,
  "BP19-060": c_BP19_060,
  "BP19-061": c_BP19_061,
  "BP19-062": c_BP19_062,
  "BP19-063": c_BP19_063,
  "BP19-064": c_BP19_064,
  "BP19-065": c_BP19_065,
  "BP19-066": c_BP19_066,
  "BP19-067": c_BP19_067,
  "BP19-068": c_BP19_068,
  "BP19-069": c_BP19_069,
  "BP19-070": c_BP19_070,
  "BP19-071": c_BP19_071,
  "BP19-072": c_BP19_072,
  "BP19-073": c_BP19_073,
  "BP19-074": c_BP19_074,
  "BP19-075": c_BP19_075,
  "BP19-076": c_BP19_076,
  "BP19-077": c_BP19_077,
  "BP19-078": c_BP19_078,
  "BP19-079": c_BP19_079,
  "BP19-080": c_BP19_080,
  "BP19-081": c_BP19_081,
  "BP19-082": c_BP19_082,
  "BP19-083": c_BP19_083,
  "BP19-084": c_BP19_084,
  "BP19-085": c_BP19_085,
  "BP19-086": c_BP19_086,
  "BP19-087": c_BP19_087,
  "BP19-088": c_BP19_088,
  "BP19-089": c_BP19_089,
  "BP19-090": c_BP19_090,
  "BP19-091": c_BP19_091,
  "BP19-092": c_BP19_092,
  "BP19-093": c_BP19_093,
  "BP19-094": c_BP19_094,
  "BP19-095": c_BP19_095,
  "BP19-096": c_BP19_096,
  "BP19-097": c_BP19_097,
  "BP19-098": c_BP19_098,
  "BP19-099": c_BP19_099,
  "BP19-100": c_BP19_100,
  "BP19-101": c_BP19_101,
  "BP19-102": c_BP19_102,
  "BP19-103": c_BP19_103,
  "BP19-104": c_BP19_104,
  "BP19-105": c_BP19_105,
  "BP19-106": c_BP19_106,
  "BP19-107": c_BP19_107,
  "BP19-108": c_BP19_108,
  "BP19-109": c_BP19_109,
  "BP19-110": c_BP19_110,
  "BP19-111": c_BP19_111,
  "BP19-112": c_BP19_112,
  "BP19-113": c_BP19_113,
  "BP19-114": c_BP19_114,
  "BP19-115": c_BP19_115,
  "BP19-116": c_BP19_116,
  "BP19-117": c_BP19_117,
  "BP19-118": c_BP19_118,
  "BP19-119": c_BP19_119,
  "BP19-120": c_BP19_120,
  "BP19-T01": c_BP19_T01,
  "BP19-T02": c_BP19_T02,
};
