// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP17_001 from "./BP17-001";
import c_BP17_002 from "./BP17-002";
import c_BP17_003 from "./BP17-003";
import c_BP17_004 from "./BP17-004";
import c_BP17_005 from "./BP17-005";
import c_BP17_006 from "./BP17-006";
import c_BP17_007 from "./BP17-007";
import c_BP17_008 from "./BP17-008";
import c_BP17_009 from "./BP17-009";
import c_BP17_010 from "./BP17-010";
import c_BP17_011 from "./BP17-011";
import c_BP17_012 from "./BP17-012";
import c_BP17_013 from "./BP17-013";
import c_BP17_014 from "./BP17-014";
import c_BP17_015 from "./BP17-015";
import c_BP17_016 from "./BP17-016";
import c_BP17_017 from "./BP17-017";
import c_BP17_018 from "./BP17-018";
import c_BP17_019 from "./BP17-019";
import c_BP17_020 from "./BP17-020";
import c_BP17_021 from "./BP17-021";
import c_BP17_022 from "./BP17-022";
import c_BP17_023 from "./BP17-023";
import c_BP17_024 from "./BP17-024";
import c_BP17_025 from "./BP17-025";
import c_BP17_026 from "./BP17-026";
import c_BP17_027 from "./BP17-027";
import c_BP17_028 from "./BP17-028";
import c_BP17_029 from "./BP17-029";
import c_BP17_030 from "./BP17-030";
import c_BP17_031 from "./BP17-031";
import c_BP17_032 from "./BP17-032";
import c_BP17_033 from "./BP17-033";
import c_BP17_034 from "./BP17-034";
import c_BP17_035 from "./BP17-035";
import c_BP17_036 from "./BP17-036";
import c_BP17_037 from "./BP17-037";
import c_BP17_038 from "./BP17-038";
import c_BP17_039 from "./BP17-039";
import c_BP17_040 from "./BP17-040";
import c_BP17_041 from "./BP17-041";
import c_BP17_042 from "./BP17-042";
import c_BP17_043 from "./BP17-043";
import c_BP17_044 from "./BP17-044";
import c_BP17_045 from "./BP17-045";
import c_BP17_046 from "./BP17-046";
import c_BP17_047 from "./BP17-047";
import c_BP17_048 from "./BP17-048";
import c_BP17_049 from "./BP17-049";
import c_BP17_050 from "./BP17-050";
import c_BP17_051 from "./BP17-051";
import c_BP17_052 from "./BP17-052";
import c_BP17_053 from "./BP17-053";
import c_BP17_054 from "./BP17-054";
import c_BP17_055 from "./BP17-055";
import c_BP17_056 from "./BP17-056";
import c_BP17_057 from "./BP17-057";
import c_BP17_058 from "./BP17-058";
import c_BP17_059 from "./BP17-059";
import c_BP17_060 from "./BP17-060";
import c_BP17_061 from "./BP17-061";
import c_BP17_062 from "./BP17-062";
import c_BP17_063 from "./BP17-063";
import c_BP17_064 from "./BP17-064";
import c_BP17_065 from "./BP17-065";
import c_BP17_066 from "./BP17-066";
import c_BP17_067 from "./BP17-067";
import c_BP17_068 from "./BP17-068";
import c_BP17_069 from "./BP17-069";
import c_BP17_070 from "./BP17-070";
import c_BP17_071 from "./BP17-071";
import c_BP17_072 from "./BP17-072";
import c_BP17_073 from "./BP17-073";
import c_BP17_074 from "./BP17-074";
import c_BP17_075 from "./BP17-075";
import c_BP17_076 from "./BP17-076";
import c_BP17_077 from "./BP17-077";
import c_BP17_078 from "./BP17-078";
import c_BP17_079 from "./BP17-079";
import c_BP17_080 from "./BP17-080";
import c_BP17_081 from "./BP17-081";
import c_BP17_082 from "./BP17-082";
import c_BP17_083 from "./BP17-083";
import c_BP17_084 from "./BP17-084";
import c_BP17_085 from "./BP17-085";
import c_BP17_086 from "./BP17-086";
import c_BP17_087 from "./BP17-087";
import c_BP17_088 from "./BP17-088";
import c_BP17_089 from "./BP17-089";
import c_BP17_090 from "./BP17-090";
import c_BP17_091 from "./BP17-091";
import c_BP17_092 from "./BP17-092";
import c_BP17_093 from "./BP17-093";
import c_BP17_094 from "./BP17-094";
import c_BP17_095 from "./BP17-095";
import c_BP17_096 from "./BP17-096";
import c_BP17_097 from "./BP17-097";
import c_BP17_098 from "./BP17-098";
import c_BP17_099 from "./BP17-099";
import c_BP17_100 from "./BP17-100";
import c_BP17_101 from "./BP17-101";
import c_BP17_102 from "./BP17-102";
import c_BP17_103 from "./BP17-103";
import c_BP17_104 from "./BP17-104";
import c_BP17_105 from "./BP17-105";
import c_BP17_106 from "./BP17-106";
import c_BP17_107 from "./BP17-107";
import c_BP17_108 from "./BP17-108";
import c_BP17_109 from "./BP17-109";
import c_BP17_110 from "./BP17-110";
import c_BP17_111 from "./BP17-111";
import c_BP17_112 from "./BP17-112";
import c_BP17_113 from "./BP17-113";
import c_BP17_114 from "./BP17-114";
import c_BP17_115 from "./BP17-115";
import c_BP17_116 from "./BP17-116";
import c_BP17_117 from "./BP17-117";
import c_BP17_118 from "./BP17-118";
import c_BP17_119 from "./BP17-119";
import c_BP17_T01 from "./BP17-T01";
import c_BP17_T02 from "./BP17-T02";
import c_BP17_T03 from "./BP17-T03";
import c_BP17_T04 from "./BP17-T04";
import c_BP17_T05 from "./BP17-T05";
import c_BP17_T06 from "./BP17-T06";
import c_BP17_T07 from "./BP17-T07";
import c_BP17_T08 from "./BP17-T08";
import c_BP17_T09 from "./BP17-T09";
import c_BP17_T10 from "./BP17-T10";

/**
 * Card scripts of BP17, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP17_SCRIPTS: ScriptRegistry = {
  "BP17-001": c_BP17_001,
  "BP17-002": c_BP17_002,
  "BP17-003": c_BP17_003,
  "BP17-004": c_BP17_004,
  "BP17-005": c_BP17_005,
  "BP17-006": c_BP17_006,
  "BP17-007": c_BP17_007,
  "BP17-008": c_BP17_008,
  "BP17-009": c_BP17_009,
  "BP17-010": c_BP17_010,
  "BP17-011": c_BP17_011,
  "BP17-012": c_BP17_012,
  "BP17-013": c_BP17_013,
  "BP17-014": c_BP17_014,
  "BP17-015": c_BP17_015,
  "BP17-016": c_BP17_016,
  "BP17-017": c_BP17_017,
  "BP17-018": c_BP17_018,
  "BP17-019": c_BP17_019,
  "BP17-020": c_BP17_020,
  "BP17-021": c_BP17_021,
  "BP17-022": c_BP17_022,
  "BP17-023": c_BP17_023,
  "BP17-024": c_BP17_024,
  "BP17-025": c_BP17_025,
  "BP17-026": c_BP17_026,
  "BP17-027": c_BP17_027,
  "BP17-028": c_BP17_028,
  "BP17-029": c_BP17_029,
  "BP17-030": c_BP17_030,
  "BP17-031": c_BP17_031,
  "BP17-032": c_BP17_032,
  "BP17-033": c_BP17_033,
  "BP17-034": c_BP17_034,
  "BP17-035": c_BP17_035,
  "BP17-036": c_BP17_036,
  "BP17-037": c_BP17_037,
  "BP17-038": c_BP17_038,
  "BP17-039": c_BP17_039,
  "BP17-040": c_BP17_040,
  "BP17-041": c_BP17_041,
  "BP17-042": c_BP17_042,
  "BP17-043": c_BP17_043,
  "BP17-044": c_BP17_044,
  "BP17-045": c_BP17_045,
  "BP17-046": c_BP17_046,
  "BP17-047": c_BP17_047,
  "BP17-048": c_BP17_048,
  "BP17-049": c_BP17_049,
  "BP17-050": c_BP17_050,
  "BP17-051": c_BP17_051,
  "BP17-052": c_BP17_052,
  "BP17-053": c_BP17_053,
  "BP17-054": c_BP17_054,
  "BP17-055": c_BP17_055,
  "BP17-056": c_BP17_056,
  "BP17-057": c_BP17_057,
  "BP17-058": c_BP17_058,
  "BP17-059": c_BP17_059,
  "BP17-060": c_BP17_060,
  "BP17-061": c_BP17_061,
  "BP17-062": c_BP17_062,
  "BP17-063": c_BP17_063,
  "BP17-064": c_BP17_064,
  "BP17-065": c_BP17_065,
  "BP17-066": c_BP17_066,
  "BP17-067": c_BP17_067,
  "BP17-068": c_BP17_068,
  "BP17-069": c_BP17_069,
  "BP17-070": c_BP17_070,
  "BP17-071": c_BP17_071,
  "BP17-072": c_BP17_072,
  "BP17-073": c_BP17_073,
  "BP17-074": c_BP17_074,
  "BP17-075": c_BP17_075,
  "BP17-076": c_BP17_076,
  "BP17-077": c_BP17_077,
  "BP17-078": c_BP17_078,
  "BP17-079": c_BP17_079,
  "BP17-080": c_BP17_080,
  "BP17-081": c_BP17_081,
  "BP17-082": c_BP17_082,
  "BP17-083": c_BP17_083,
  "BP17-084": c_BP17_084,
  "BP17-085": c_BP17_085,
  "BP17-086": c_BP17_086,
  "BP17-087": c_BP17_087,
  "BP17-088": c_BP17_088,
  "BP17-089": c_BP17_089,
  "BP17-090": c_BP17_090,
  "BP17-091": c_BP17_091,
  "BP17-092": c_BP17_092,
  "BP17-093": c_BP17_093,
  "BP17-094": c_BP17_094,
  "BP17-095": c_BP17_095,
  "BP17-096": c_BP17_096,
  "BP17-097": c_BP17_097,
  "BP17-098": c_BP17_098,
  "BP17-099": c_BP17_099,
  "BP17-100": c_BP17_100,
  "BP17-101": c_BP17_101,
  "BP17-102": c_BP17_102,
  "BP17-103": c_BP17_103,
  "BP17-104": c_BP17_104,
  "BP17-105": c_BP17_105,
  "BP17-106": c_BP17_106,
  "BP17-107": c_BP17_107,
  "BP17-108": c_BP17_108,
  "BP17-109": c_BP17_109,
  "BP17-110": c_BP17_110,
  "BP17-111": c_BP17_111,
  "BP17-112": c_BP17_112,
  "BP17-113": c_BP17_113,
  "BP17-114": c_BP17_114,
  "BP17-115": c_BP17_115,
  "BP17-116": c_BP17_116,
  "BP17-117": c_BP17_117,
  "BP17-118": c_BP17_118,
  "BP17-119": c_BP17_119,
  "BP17-T01": c_BP17_T01,
  "BP17-T02": c_BP17_T02,
  "BP17-T03": c_BP17_T03,
  "BP17-T04": c_BP17_T04,
  "BP17-T05": c_BP17_T05,
  "BP17-T06": c_BP17_T06,
  "BP17-T07": c_BP17_T07,
  "BP17-T08": c_BP17_T08,
  "BP17-T09": c_BP17_T09,
  "BP17-T10": c_BP17_T10,
};
