// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CSD03a_001 from "./CSD03a-001";
import c_CSD03a_002 from "./CSD03a-002";
import c_CSD03a_003 from "./CSD03a-003";
import c_CSD03a_004 from "./CSD03a-004";
import c_CSD03a_005 from "./CSD03a-005";
import c_CSD03a_006 from "./CSD03a-006";
import c_CSD03a_007 from "./CSD03a-007";
import c_CSD03a_008 from "./CSD03a-008";
import c_CSD03a_009 from "./CSD03a-009";
import c_CSD03a_010 from "./CSD03a-010";
import c_CSD03a_011 from "./CSD03a-011";
import c_CSD03a_016 from "./CSD03a-016";

/**
 * Card scripts of CSD03a, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CSD03a_SCRIPTS: ScriptRegistry = {
  "CSD03a-001": c_CSD03a_001,
  "CSD03a-002": c_CSD03a_002,
  "CSD03a-003": c_CSD03a_003,
  "CSD03a-004": c_CSD03a_004,
  "CSD03a-005": c_CSD03a_005,
  "CSD03a-006": c_CSD03a_006,
  "CSD03a-007": c_CSD03a_007,
  "CSD03a-008": c_CSD03a_008,
  "CSD03a-009": c_CSD03a_009,
  "CSD03a-010": c_CSD03a_010,
  "CSD03a-011": c_CSD03a_011,
  "CSD03a-016": c_CSD03a_016,
};
