// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CSD02c_001 from "./CSD02c-001";
import c_CSD02c_002 from "./CSD02c-002";
import c_CSD02c_003 from "./CSD02c-003";
import c_CSD02c_004 from "./CSD02c-004";
import c_CSD02c_005 from "./CSD02c-005";
import c_CSD02c_006 from "./CSD02c-006";
import c_CSD02c_007 from "./CSD02c-007";
import c_CSD02c_008 from "./CSD02c-008";
import c_CSD02c_009 from "./CSD02c-009";
import c_CSD02c_010 from "./CSD02c-010";
import c_CSD02c_011 from "./CSD02c-011";

/**
 * Card scripts of CSD02c, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CSD02c_SCRIPTS: ScriptRegistry = {
  "CSD02c-001": c_CSD02c_001,
  "CSD02c-002": c_CSD02c_002,
  "CSD02c-003": c_CSD02c_003,
  "CSD02c-004": c_CSD02c_004,
  "CSD02c-005": c_CSD02c_005,
  "CSD02c-006": c_CSD02c_006,
  "CSD02c-007": c_CSD02c_007,
  "CSD02c-008": c_CSD02c_008,
  "CSD02c-009": c_CSD02c_009,
  "CSD02c-010": c_CSD02c_010,
  "CSD02c-011": c_CSD02c_011,
};
