// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP01_001 from "./BP01-001";
import c_BP01_002 from "./BP01-002";
import c_BP01_003 from "./BP01-003";
import c_BP01_004 from "./BP01-004";
import c_BP01_005 from "./BP01-005";
import c_BP01_006 from "./BP01-006";
import c_BP01_007 from "./BP01-007";
import c_BP01_008 from "./BP01-008";
import c_BP01_009 from "./BP01-009";
import c_BP01_010 from "./BP01-010";
import c_BP01_011 from "./BP01-011";
import c_BP01_012 from "./BP01-012";
import c_BP01_013 from "./BP01-013";
import c_BP01_014 from "./BP01-014";
import c_BP01_015 from "./BP01-015";
import c_BP01_016 from "./BP01-016";
import c_BP01_017 from "./BP01-017";
import c_BP01_018 from "./BP01-018";
import c_BP01_019 from "./BP01-019";
import c_BP01_020 from "./BP01-020";
import c_BP01_021 from "./BP01-021";
import c_BP01_022 from "./BP01-022";
import c_BP01_023 from "./BP01-023";
import c_BP01_024 from "./BP01-024";
import c_BP01_025 from "./BP01-025";
import c_BP01_026 from "./BP01-026";
import c_BP01_027 from "./BP01-027";
import c_BP01_028 from "./BP01-028";
import c_BP01_029 from "./BP01-029";
import c_BP01_030 from "./BP01-030";
import c_BP01_031 from "./BP01-031";
import c_BP01_032 from "./BP01-032";
import c_BP01_033 from "./BP01-033";
import c_BP01_034 from "./BP01-034";
import c_BP01_035 from "./BP01-035";
import c_BP01_036 from "./BP01-036";
import c_BP01_037 from "./BP01-037";
import c_BP01_038 from "./BP01-038";
import c_BP01_039 from "./BP01-039";
import c_BP01_040 from "./BP01-040";
import c_BP01_041 from "./BP01-041";
import c_BP01_043 from "./BP01-043";
import c_BP01_044 from "./BP01-044";
import c_BP01_045 from "./BP01-045";
import c_BP01_046 from "./BP01-046";
import c_BP01_047 from "./BP01-047";
import c_BP01_048 from "./BP01-048";
import c_BP01_049 from "./BP01-049";
import c_BP01_050 from "./BP01-050";
import c_BP01_051 from "./BP01-051";
import c_BP01_052 from "./BP01-052";
import c_BP01_053 from "./BP01-053";
import c_BP01_054 from "./BP01-054";
import c_BP01_055 from "./BP01-055";
import c_BP01_056 from "./BP01-056";
import c_BP01_057 from "./BP01-057";
import c_BP01_058 from "./BP01-058";
import c_BP01_059 from "./BP01-059";
import c_BP01_060 from "./BP01-060";
import c_BP01_061 from "./BP01-061";
import c_BP01_062 from "./BP01-062";
import c_BP01_063 from "./BP01-063";
import c_BP01_064 from "./BP01-064";
import c_BP01_065 from "./BP01-065";
import c_BP01_066 from "./BP01-066";
import c_BP01_067 from "./BP01-067";
import c_BP01_068 from "./BP01-068";
import c_BP01_069 from "./BP01-069";
import c_BP01_070 from "./BP01-070";
import c_BP01_071 from "./BP01-071";
import c_BP01_072 from "./BP01-072";
import c_BP01_073 from "./BP01-073";
import c_BP01_074 from "./BP01-074";
import c_BP01_075 from "./BP01-075";
import c_BP01_076 from "./BP01-076";
import c_BP01_077 from "./BP01-077";
import c_BP01_078 from "./BP01-078";
import c_BP01_079 from "./BP01-079";
import c_BP01_080 from "./BP01-080";
import c_BP01_081 from "./BP01-081";
import c_BP01_082 from "./BP01-082";
import c_BP01_083 from "./BP01-083";
import c_BP01_084 from "./BP01-084";
import c_BP01_085 from "./BP01-085";
import c_BP01_086 from "./BP01-086";
import c_BP01_087 from "./BP01-087";
import c_BP01_088 from "./BP01-088";
import c_BP01_089 from "./BP01-089";
import c_BP01_090 from "./BP01-090";
import c_BP01_091 from "./BP01-091";
import c_BP01_092 from "./BP01-092";
import c_BP01_093 from "./BP01-093";
import c_BP01_094 from "./BP01-094";
import c_BP01_095 from "./BP01-095";
import c_BP01_096 from "./BP01-096";
import c_BP01_097 from "./BP01-097";
import c_BP01_098 from "./BP01-098";
import c_BP01_099 from "./BP01-099";
import c_BP01_100 from "./BP01-100";
import c_BP01_101 from "./BP01-101";
import c_BP01_102 from "./BP01-102";
import c_BP01_103 from "./BP01-103";
import c_BP01_104 from "./BP01-104";
import c_BP01_105 from "./BP01-105";
import c_BP01_106 from "./BP01-106";
import c_BP01_107 from "./BP01-107";
import c_BP01_108 from "./BP01-108";
import c_BP01_109 from "./BP01-109";
import c_BP01_110 from "./BP01-110";
import c_BP01_111 from "./BP01-111";
import c_BP01_112 from "./BP01-112";
import c_BP01_113 from "./BP01-113";
import c_BP01_114 from "./BP01-114";
import c_BP01_115 from "./BP01-115";
import c_BP01_116 from "./BP01-116";
import c_BP01_117 from "./BP01-117";
import c_BP01_118 from "./BP01-118";
import c_BP01_119 from "./BP01-119";
import c_BP01_120 from "./BP01-120";
import c_BP01_121 from "./BP01-121";
import c_BP01_122 from "./BP01-122";
import c_BP01_123 from "./BP01-123";
import c_BP01_124 from "./BP01-124";
import c_BP01_125 from "./BP01-125";
import c_BP01_126 from "./BP01-126";
import c_BP01_127 from "./BP01-127";
import c_BP01_128 from "./BP01-128";
import c_BP01_129 from "./BP01-129";
import c_BP01_130 from "./BP01-130";
import c_BP01_131 from "./BP01-131";
import c_BP01_132 from "./BP01-132";
import c_BP01_133 from "./BP01-133";
import c_BP01_134 from "./BP01-134";
import c_BP01_135 from "./BP01-135";
import c_BP01_136 from "./BP01-136";
import c_BP01_137 from "./BP01-137";
import c_BP01_138 from "./BP01-138";
import c_BP01_139 from "./BP01-139";
import c_BP01_140 from "./BP01-140";
import c_BP01_141 from "./BP01-141";
import c_BP01_142 from "./BP01-142";
import c_BP01_143 from "./BP01-143";
import c_BP01_144 from "./BP01-144";
import c_BP01_145 from "./BP01-145";
import c_BP01_146 from "./BP01-146";
import c_BP01_147 from "./BP01-147";
import c_BP01_148 from "./BP01-148";
import c_BP01_149 from "./BP01-149";
import c_BP01_150 from "./BP01-150";
import c_BP01_151 from "./BP01-151";
import c_BP01_152 from "./BP01-152";
import c_BP01_153 from "./BP01-153";
import c_BP01_154 from "./BP01-154";
import c_BP01_155 from "./BP01-155";
import c_BP01_156 from "./BP01-156";
import c_BP01_157 from "./BP01-157";
import c_BP01_158 from "./BP01-158";
import c_BP01_159 from "./BP01-159";
import c_BP01_160 from "./BP01-160";
import c_BP01_161 from "./BP01-161";
import c_BP01_162 from "./BP01-162";
import c_BP01_163 from "./BP01-163";
import c_BP01_164 from "./BP01-164";
import c_BP01_165 from "./BP01-165";
import c_BP01_166 from "./BP01-166";
import c_BP01_167 from "./BP01-167";
import c_BP01_168 from "./BP01-168";
import c_BP01_169 from "./BP01-169";
import c_BP01_170 from "./BP01-170";
import c_BP01_171 from "./BP01-171";
import c_BP01_174 from "./BP01-174";
import c_BP01_176 from "./BP01-176";
import c_BP01_177 from "./BP01-177";
import c_BP01_178 from "./BP01-178";
import c_BP01_179 from "./BP01-179";
import c_BP01_180 from "./BP01-180";
import c_BP01_T01 from "./BP01-T01";
import c_BP01_T04 from "./BP01-T04";
import c_BP01_T06 from "./BP01-T06";
import c_BP01_T08 from "./BP01-T08";
import c_BP01_T09 from "./BP01-T09";
import c_BP01_T10 from "./BP01-T10";
import c_BP01_T12 from "./BP01-T12";
import c_BP01_T13 from "./BP01-T13";
import c_BP01_T14 from "./BP01-T14";
import c_BP01_T16 from "./BP01-T16";
import c_BP01_T17 from "./BP01-T17";

/**
 * Card scripts of BP01, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP01_SCRIPTS: ScriptRegistry = {
  "BP01-001": c_BP01_001,
  "BP01-002": c_BP01_002,
  "BP01-003": c_BP01_003,
  "BP01-004": c_BP01_004,
  "BP01-005": c_BP01_005,
  "BP01-006": c_BP01_006,
  "BP01-007": c_BP01_007,
  "BP01-008": c_BP01_008,
  "BP01-009": c_BP01_009,
  "BP01-010": c_BP01_010,
  "BP01-011": c_BP01_011,
  "BP01-012": c_BP01_012,
  "BP01-013": c_BP01_013,
  "BP01-014": c_BP01_014,
  "BP01-015": c_BP01_015,
  "BP01-016": c_BP01_016,
  "BP01-017": c_BP01_017,
  "BP01-018": c_BP01_018,
  "BP01-019": c_BP01_019,
  "BP01-020": c_BP01_020,
  "BP01-021": c_BP01_021,
  "BP01-022": c_BP01_022,
  "BP01-023": c_BP01_023,
  "BP01-024": c_BP01_024,
  "BP01-025": c_BP01_025,
  "BP01-026": c_BP01_026,
  "BP01-027": c_BP01_027,
  "BP01-028": c_BP01_028,
  "BP01-029": c_BP01_029,
  "BP01-030": c_BP01_030,
  "BP01-031": c_BP01_031,
  "BP01-032": c_BP01_032,
  "BP01-033": c_BP01_033,
  "BP01-034": c_BP01_034,
  "BP01-035": c_BP01_035,
  "BP01-036": c_BP01_036,
  "BP01-037": c_BP01_037,
  "BP01-038": c_BP01_038,
  "BP01-039": c_BP01_039,
  "BP01-040": c_BP01_040,
  "BP01-041": c_BP01_041,
  "BP01-043": c_BP01_043,
  "BP01-044": c_BP01_044,
  "BP01-045": c_BP01_045,
  "BP01-046": c_BP01_046,
  "BP01-047": c_BP01_047,
  "BP01-048": c_BP01_048,
  "BP01-049": c_BP01_049,
  "BP01-050": c_BP01_050,
  "BP01-051": c_BP01_051,
  "BP01-052": c_BP01_052,
  "BP01-053": c_BP01_053,
  "BP01-054": c_BP01_054,
  "BP01-055": c_BP01_055,
  "BP01-056": c_BP01_056,
  "BP01-057": c_BP01_057,
  "BP01-058": c_BP01_058,
  "BP01-059": c_BP01_059,
  "BP01-060": c_BP01_060,
  "BP01-061": c_BP01_061,
  "BP01-062": c_BP01_062,
  "BP01-063": c_BP01_063,
  "BP01-064": c_BP01_064,
  "BP01-065": c_BP01_065,
  "BP01-066": c_BP01_066,
  "BP01-067": c_BP01_067,
  "BP01-068": c_BP01_068,
  "BP01-069": c_BP01_069,
  "BP01-070": c_BP01_070,
  "BP01-071": c_BP01_071,
  "BP01-072": c_BP01_072,
  "BP01-073": c_BP01_073,
  "BP01-074": c_BP01_074,
  "BP01-075": c_BP01_075,
  "BP01-076": c_BP01_076,
  "BP01-077": c_BP01_077,
  "BP01-078": c_BP01_078,
  "BP01-079": c_BP01_079,
  "BP01-080": c_BP01_080,
  "BP01-081": c_BP01_081,
  "BP01-082": c_BP01_082,
  "BP01-083": c_BP01_083,
  "BP01-084": c_BP01_084,
  "BP01-085": c_BP01_085,
  "BP01-086": c_BP01_086,
  "BP01-087": c_BP01_087,
  "BP01-088": c_BP01_088,
  "BP01-089": c_BP01_089,
  "BP01-090": c_BP01_090,
  "BP01-091": c_BP01_091,
  "BP01-092": c_BP01_092,
  "BP01-093": c_BP01_093,
  "BP01-094": c_BP01_094,
  "BP01-095": c_BP01_095,
  "BP01-096": c_BP01_096,
  "BP01-097": c_BP01_097,
  "BP01-098": c_BP01_098,
  "BP01-099": c_BP01_099,
  "BP01-100": c_BP01_100,
  "BP01-101": c_BP01_101,
  "BP01-102": c_BP01_102,
  "BP01-103": c_BP01_103,
  "BP01-104": c_BP01_104,
  "BP01-105": c_BP01_105,
  "BP01-106": c_BP01_106,
  "BP01-107": c_BP01_107,
  "BP01-108": c_BP01_108,
  "BP01-109": c_BP01_109,
  "BP01-110": c_BP01_110,
  "BP01-111": c_BP01_111,
  "BP01-112": c_BP01_112,
  "BP01-113": c_BP01_113,
  "BP01-114": c_BP01_114,
  "BP01-115": c_BP01_115,
  "BP01-116": c_BP01_116,
  "BP01-117": c_BP01_117,
  "BP01-118": c_BP01_118,
  "BP01-119": c_BP01_119,
  "BP01-120": c_BP01_120,
  "BP01-121": c_BP01_121,
  "BP01-122": c_BP01_122,
  "BP01-123": c_BP01_123,
  "BP01-124": c_BP01_124,
  "BP01-125": c_BP01_125,
  "BP01-126": c_BP01_126,
  "BP01-127": c_BP01_127,
  "BP01-128": c_BP01_128,
  "BP01-129": c_BP01_129,
  "BP01-130": c_BP01_130,
  "BP01-131": c_BP01_131,
  "BP01-132": c_BP01_132,
  "BP01-133": c_BP01_133,
  "BP01-134": c_BP01_134,
  "BP01-135": c_BP01_135,
  "BP01-136": c_BP01_136,
  "BP01-137": c_BP01_137,
  "BP01-138": c_BP01_138,
  "BP01-139": c_BP01_139,
  "BP01-140": c_BP01_140,
  "BP01-141": c_BP01_141,
  "BP01-142": c_BP01_142,
  "BP01-143": c_BP01_143,
  "BP01-144": c_BP01_144,
  "BP01-145": c_BP01_145,
  "BP01-146": c_BP01_146,
  "BP01-147": c_BP01_147,
  "BP01-148": c_BP01_148,
  "BP01-149": c_BP01_149,
  "BP01-150": c_BP01_150,
  "BP01-151": c_BP01_151,
  "BP01-152": c_BP01_152,
  "BP01-153": c_BP01_153,
  "BP01-154": c_BP01_154,
  "BP01-155": c_BP01_155,
  "BP01-156": c_BP01_156,
  "BP01-157": c_BP01_157,
  "BP01-158": c_BP01_158,
  "BP01-159": c_BP01_159,
  "BP01-160": c_BP01_160,
  "BP01-161": c_BP01_161,
  "BP01-162": c_BP01_162,
  "BP01-163": c_BP01_163,
  "BP01-164": c_BP01_164,
  "BP01-165": c_BP01_165,
  "BP01-166": c_BP01_166,
  "BP01-167": c_BP01_167,
  "BP01-168": c_BP01_168,
  "BP01-169": c_BP01_169,
  "BP01-170": c_BP01_170,
  "BP01-171": c_BP01_171,
  "BP01-174": c_BP01_174,
  "BP01-176": c_BP01_176,
  "BP01-177": c_BP01_177,
  "BP01-178": c_BP01_178,
  "BP01-179": c_BP01_179,
  "BP01-180": c_BP01_180,
  "BP01-T01": c_BP01_T01,
  "BP01-T04": c_BP01_T04,
  "BP01-T06": c_BP01_T06,
  "BP01-T08": c_BP01_T08,
  "BP01-T09": c_BP01_T09,
  "BP01-T10": c_BP01_T10,
  "BP01-T12": c_BP01_T12,
  "BP01-T13": c_BP01_T13,
  "BP01-T14": c_BP01_T14,
  "BP01-T16": c_BP01_T16,
  "BP01-T17": c_BP01_T17,
};
