// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP13_001 from "./BP13-001";
import c_BP13_002 from "./BP13-002";
import c_BP13_003 from "./BP13-003";
import c_BP13_004 from "./BP13-004";
import c_BP13_005 from "./BP13-005";
import c_BP13_006 from "./BP13-006";
import c_BP13_007 from "./BP13-007";
import c_BP13_008 from "./BP13-008";
import c_BP13_009 from "./BP13-009";
import c_BP13_010 from "./BP13-010";
import c_BP13_011 from "./BP13-011";
import c_BP13_012 from "./BP13-012";
import c_BP13_013 from "./BP13-013";
import c_BP13_014 from "./BP13-014";
import c_BP13_015 from "./BP13-015";
import c_BP13_016 from "./BP13-016";
import c_BP13_017 from "./BP13-017";
import c_BP13_018 from "./BP13-018";
import c_BP13_019 from "./BP13-019";
import c_BP13_020 from "./BP13-020";
import c_BP13_021 from "./BP13-021";
import c_BP13_022 from "./BP13-022";
import c_BP13_023 from "./BP13-023";
import c_BP13_024 from "./BP13-024";
import c_BP13_025 from "./BP13-025";
import c_BP13_026 from "./BP13-026";
import c_BP13_027 from "./BP13-027";
import c_BP13_028 from "./BP13-028";
import c_BP13_029 from "./BP13-029";
import c_BP13_030 from "./BP13-030";
import c_BP13_031 from "./BP13-031";
import c_BP13_032 from "./BP13-032";
import c_BP13_033 from "./BP13-033";
import c_BP13_034 from "./BP13-034";
import c_BP13_035 from "./BP13-035";
import c_BP13_036 from "./BP13-036";
import c_BP13_037 from "./BP13-037";
import c_BP13_038 from "./BP13-038";
import c_BP13_039 from "./BP13-039";
import c_BP13_040 from "./BP13-040";
import c_BP13_041 from "./BP13-041";
import c_BP13_042 from "./BP13-042";
import c_BP13_043 from "./BP13-043";
import c_BP13_044 from "./BP13-044";
import c_BP13_045 from "./BP13-045";
import c_BP13_046 from "./BP13-046";
import c_BP13_047 from "./BP13-047";
import c_BP13_048 from "./BP13-048";
import c_BP13_049 from "./BP13-049";
import c_BP13_050 from "./BP13-050";
import c_BP13_051 from "./BP13-051";
import c_BP13_052 from "./BP13-052";
import c_BP13_053 from "./BP13-053";
import c_BP13_054 from "./BP13-054";
import c_BP13_055 from "./BP13-055";
import c_BP13_056 from "./BP13-056";
import c_BP13_057 from "./BP13-057";
import c_BP13_058 from "./BP13-058";
import c_BP13_059 from "./BP13-059";
import c_BP13_060 from "./BP13-060";
import c_BP13_061 from "./BP13-061";
import c_BP13_062 from "./BP13-062";
import c_BP13_063 from "./BP13-063";
import c_BP13_064 from "./BP13-064";
import c_BP13_065 from "./BP13-065";
import c_BP13_066 from "./BP13-066";
import c_BP13_067 from "./BP13-067";
import c_BP13_068 from "./BP13-068";
import c_BP13_069 from "./BP13-069";
import c_BP13_070 from "./BP13-070";
import c_BP13_071 from "./BP13-071";
import c_BP13_072 from "./BP13-072";
import c_BP13_073 from "./BP13-073";
import c_BP13_074 from "./BP13-074";
import c_BP13_075 from "./BP13-075";
import c_BP13_076 from "./BP13-076";
import c_BP13_077 from "./BP13-077";
import c_BP13_078 from "./BP13-078";
import c_BP13_079 from "./BP13-079";
import c_BP13_080 from "./BP13-080";
import c_BP13_081 from "./BP13-081";
import c_BP13_082 from "./BP13-082";
import c_BP13_083 from "./BP13-083";
import c_BP13_084 from "./BP13-084";
import c_BP13_085 from "./BP13-085";
import c_BP13_086 from "./BP13-086";
import c_BP13_087 from "./BP13-087";
import c_BP13_088 from "./BP13-088";
import c_BP13_089 from "./BP13-089";
import c_BP13_090 from "./BP13-090";
import c_BP13_091 from "./BP13-091";
import c_BP13_092 from "./BP13-092";
import c_BP13_093 from "./BP13-093";
import c_BP13_094 from "./BP13-094";
import c_BP13_095 from "./BP13-095";
import c_BP13_096 from "./BP13-096";
import c_BP13_097 from "./BP13-097";
import c_BP13_098 from "./BP13-098";
import c_BP13_099 from "./BP13-099";
import c_BP13_100 from "./BP13-100";
import c_BP13_101 from "./BP13-101";
import c_BP13_102 from "./BP13-102";
import c_BP13_103 from "./BP13-103";
import c_BP13_104 from "./BP13-104";
import c_BP13_105 from "./BP13-105";
import c_BP13_106 from "./BP13-106";
import c_BP13_107 from "./BP13-107";
import c_BP13_108 from "./BP13-108";
import c_BP13_109 from "./BP13-109";
import c_BP13_110 from "./BP13-110";
import c_BP13_111 from "./BP13-111";
import c_BP13_112 from "./BP13-112";
import c_BP13_113 from "./BP13-113";
import c_BP13_114 from "./BP13-114";
import c_BP13_115 from "./BP13-115";
import c_BP13_116 from "./BP13-116";
import c_BP13_117 from "./BP13-117";
import c_BP13_118 from "./BP13-118";
import c_BP13_119 from "./BP13-119";
import c_BP13_T01 from "./BP13-T01";
import c_BP13_T02 from "./BP13-T02";
import c_BP13_T03 from "./BP13-T03";
import c_BP13_T04 from "./BP13-T04";
import c_BP13_T05 from "./BP13-T05";

/**
 * Card scripts of BP13, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP13_SCRIPTS: ScriptRegistry = {
  "BP13-001": c_BP13_001,
  "BP13-002": c_BP13_002,
  "BP13-003": c_BP13_003,
  "BP13-004": c_BP13_004,
  "BP13-005": c_BP13_005,
  "BP13-006": c_BP13_006,
  "BP13-007": c_BP13_007,
  "BP13-008": c_BP13_008,
  "BP13-009": c_BP13_009,
  "BP13-010": c_BP13_010,
  "BP13-011": c_BP13_011,
  "BP13-012": c_BP13_012,
  "BP13-013": c_BP13_013,
  "BP13-014": c_BP13_014,
  "BP13-015": c_BP13_015,
  "BP13-016": c_BP13_016,
  "BP13-017": c_BP13_017,
  "BP13-018": c_BP13_018,
  "BP13-019": c_BP13_019,
  "BP13-020": c_BP13_020,
  "BP13-021": c_BP13_021,
  "BP13-022": c_BP13_022,
  "BP13-023": c_BP13_023,
  "BP13-024": c_BP13_024,
  "BP13-025": c_BP13_025,
  "BP13-026": c_BP13_026,
  "BP13-027": c_BP13_027,
  "BP13-028": c_BP13_028,
  "BP13-029": c_BP13_029,
  "BP13-030": c_BP13_030,
  "BP13-031": c_BP13_031,
  "BP13-032": c_BP13_032,
  "BP13-033": c_BP13_033,
  "BP13-034": c_BP13_034,
  "BP13-035": c_BP13_035,
  "BP13-036": c_BP13_036,
  "BP13-037": c_BP13_037,
  "BP13-038": c_BP13_038,
  "BP13-039": c_BP13_039,
  "BP13-040": c_BP13_040,
  "BP13-041": c_BP13_041,
  "BP13-042": c_BP13_042,
  "BP13-043": c_BP13_043,
  "BP13-044": c_BP13_044,
  "BP13-045": c_BP13_045,
  "BP13-046": c_BP13_046,
  "BP13-047": c_BP13_047,
  "BP13-048": c_BP13_048,
  "BP13-049": c_BP13_049,
  "BP13-050": c_BP13_050,
  "BP13-051": c_BP13_051,
  "BP13-052": c_BP13_052,
  "BP13-053": c_BP13_053,
  "BP13-054": c_BP13_054,
  "BP13-055": c_BP13_055,
  "BP13-056": c_BP13_056,
  "BP13-057": c_BP13_057,
  "BP13-058": c_BP13_058,
  "BP13-059": c_BP13_059,
  "BP13-060": c_BP13_060,
  "BP13-061": c_BP13_061,
  "BP13-062": c_BP13_062,
  "BP13-063": c_BP13_063,
  "BP13-064": c_BP13_064,
  "BP13-065": c_BP13_065,
  "BP13-066": c_BP13_066,
  "BP13-067": c_BP13_067,
  "BP13-068": c_BP13_068,
  "BP13-069": c_BP13_069,
  "BP13-070": c_BP13_070,
  "BP13-071": c_BP13_071,
  "BP13-072": c_BP13_072,
  "BP13-073": c_BP13_073,
  "BP13-074": c_BP13_074,
  "BP13-075": c_BP13_075,
  "BP13-076": c_BP13_076,
  "BP13-077": c_BP13_077,
  "BP13-078": c_BP13_078,
  "BP13-079": c_BP13_079,
  "BP13-080": c_BP13_080,
  "BP13-081": c_BP13_081,
  "BP13-082": c_BP13_082,
  "BP13-083": c_BP13_083,
  "BP13-084": c_BP13_084,
  "BP13-085": c_BP13_085,
  "BP13-086": c_BP13_086,
  "BP13-087": c_BP13_087,
  "BP13-088": c_BP13_088,
  "BP13-089": c_BP13_089,
  "BP13-090": c_BP13_090,
  "BP13-091": c_BP13_091,
  "BP13-092": c_BP13_092,
  "BP13-093": c_BP13_093,
  "BP13-094": c_BP13_094,
  "BP13-095": c_BP13_095,
  "BP13-096": c_BP13_096,
  "BP13-097": c_BP13_097,
  "BP13-098": c_BP13_098,
  "BP13-099": c_BP13_099,
  "BP13-100": c_BP13_100,
  "BP13-101": c_BP13_101,
  "BP13-102": c_BP13_102,
  "BP13-103": c_BP13_103,
  "BP13-104": c_BP13_104,
  "BP13-105": c_BP13_105,
  "BP13-106": c_BP13_106,
  "BP13-107": c_BP13_107,
  "BP13-108": c_BP13_108,
  "BP13-109": c_BP13_109,
  "BP13-110": c_BP13_110,
  "BP13-111": c_BP13_111,
  "BP13-112": c_BP13_112,
  "BP13-113": c_BP13_113,
  "BP13-114": c_BP13_114,
  "BP13-115": c_BP13_115,
  "BP13-116": c_BP13_116,
  "BP13-117": c_BP13_117,
  "BP13-118": c_BP13_118,
  "BP13-119": c_BP13_119,
  "BP13-T01": c_BP13_T01,
  "BP13-T02": c_BP13_T02,
  "BP13-T03": c_BP13_T03,
  "BP13-T04": c_BP13_T04,
  "BP13-T05": c_BP13_T05,
};
