// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_CP02_001 from "./CP02-001";
import c_CP02_002 from "./CP02-002";
import c_CP02_003 from "./CP02-003";
import c_CP02_004 from "./CP02-004";
import c_CP02_005 from "./CP02-005";
import c_CP02_006 from "./CP02-006";
import c_CP02_007 from "./CP02-007";
import c_CP02_008 from "./CP02-008";
import c_CP02_009 from "./CP02-009";
import c_CP02_010 from "./CP02-010";
import c_CP02_011 from "./CP02-011";
import c_CP02_012 from "./CP02-012";
import c_CP02_013 from "./CP02-013";
import c_CP02_014 from "./CP02-014";
import c_CP02_015 from "./CP02-015";
import c_CP02_016 from "./CP02-016";
import c_CP02_017 from "./CP02-017";
import c_CP02_018 from "./CP02-018";
import c_CP02_019 from "./CP02-019";
import c_CP02_020 from "./CP02-020";
import c_CP02_021 from "./CP02-021";
import c_CP02_022 from "./CP02-022";
import c_CP02_023 from "./CP02-023";
import c_CP02_024 from "./CP02-024";
import c_CP02_025 from "./CP02-025";
import c_CP02_026 from "./CP02-026";
import c_CP02_027 from "./CP02-027";
import c_CP02_028 from "./CP02-028";
import c_CP02_029 from "./CP02-029";
import c_CP02_030 from "./CP02-030";
import c_CP02_031 from "./CP02-031";
import c_CP02_032 from "./CP02-032";
import c_CP02_033 from "./CP02-033";
import c_CP02_034 from "./CP02-034";
import c_CP02_035 from "./CP02-035";
import c_CP02_036 from "./CP02-036";
import c_CP02_037 from "./CP02-037";
import c_CP02_038 from "./CP02-038";
import c_CP02_039 from "./CP02-039";
import c_CP02_040 from "./CP02-040";
import c_CP02_041 from "./CP02-041";
import c_CP02_042 from "./CP02-042";
import c_CP02_043 from "./CP02-043";
import c_CP02_044 from "./CP02-044";
import c_CP02_045 from "./CP02-045";
import c_CP02_046 from "./CP02-046";
import c_CP02_047 from "./CP02-047";
import c_CP02_048 from "./CP02-048";
import c_CP02_049 from "./CP02-049";
import c_CP02_050 from "./CP02-050";
import c_CP02_051 from "./CP02-051";
import c_CP02_052 from "./CP02-052";
import c_CP02_053 from "./CP02-053";
import c_CP02_054 from "./CP02-054";
import c_CP02_055 from "./CP02-055";
import c_CP02_056 from "./CP02-056";
import c_CP02_057 from "./CP02-057";
import c_CP02_058 from "./CP02-058";
import c_CP02_059 from "./CP02-059";
import c_CP02_060 from "./CP02-060";
import c_CP02_061 from "./CP02-061";
import c_CP02_062 from "./CP02-062";
import c_CP02_063 from "./CP02-063";
import c_CP02_064 from "./CP02-064";
import c_CP02_065 from "./CP02-065";
import c_CP02_066 from "./CP02-066";
import c_CP02_067 from "./CP02-067";
import c_CP02_068 from "./CP02-068";
import c_CP02_069 from "./CP02-069";
import c_CP02_070 from "./CP02-070";
import c_CP02_071 from "./CP02-071";
import c_CP02_072 from "./CP02-072";
import c_CP02_073 from "./CP02-073";
import c_CP02_074 from "./CP02-074";
import c_CP02_075 from "./CP02-075";
import c_CP02_076 from "./CP02-076";
import c_CP02_077 from "./CP02-077";
import c_CP02_078 from "./CP02-078";
import c_CP02_079 from "./CP02-079";
import c_CP02_080 from "./CP02-080";
import c_CP02_081 from "./CP02-081";
import c_CP02_082 from "./CP02-082";
import c_CP02_083 from "./CP02-083";
import c_CP02_084 from "./CP02-084";
import c_CP02_085 from "./CP02-085";
import c_CP02_086 from "./CP02-086";
import c_CP02_087 from "./CP02-087";
import c_CP02_088 from "./CP02-088";
import c_CP02_089 from "./CP02-089";
import c_CP02_090 from "./CP02-090";
import c_CP02_091 from "./CP02-091";
import c_CP02_092 from "./CP02-092";
import c_CP02_093 from "./CP02-093";
import c_CP02_094 from "./CP02-094";
import c_CP02_095 from "./CP02-095";
import c_CP02_096 from "./CP02-096";
import c_CP02_097 from "./CP02-097";
import c_CP02_098 from "./CP02-098";
import c_CP02_099 from "./CP02-099";
import c_CP02_100 from "./CP02-100";
import c_CP02_101 from "./CP02-101";
import c_CP02_102 from "./CP02-102";
import c_CP02_103 from "./CP02-103";
import c_CP02_104 from "./CP02-104";
import c_CP02_105 from "./CP02-105";
import c_CP02_106 from "./CP02-106";
import c_CP02_107 from "./CP02-107";
import c_CP02_108 from "./CP02-108";
import c_CP02_T01 from "./CP02-T01";

/**
 * Card scripts of CP02, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const CP02_SCRIPTS: ScriptRegistry = {
  "CP02-001": c_CP02_001,
  "CP02-002": c_CP02_002,
  "CP02-003": c_CP02_003,
  "CP02-004": c_CP02_004,
  "CP02-005": c_CP02_005,
  "CP02-006": c_CP02_006,
  "CP02-007": c_CP02_007,
  "CP02-008": c_CP02_008,
  "CP02-009": c_CP02_009,
  "CP02-010": c_CP02_010,
  "CP02-011": c_CP02_011,
  "CP02-012": c_CP02_012,
  "CP02-013": c_CP02_013,
  "CP02-014": c_CP02_014,
  "CP02-015": c_CP02_015,
  "CP02-016": c_CP02_016,
  "CP02-017": c_CP02_017,
  "CP02-018": c_CP02_018,
  "CP02-019": c_CP02_019,
  "CP02-020": c_CP02_020,
  "CP02-021": c_CP02_021,
  "CP02-022": c_CP02_022,
  "CP02-023": c_CP02_023,
  "CP02-024": c_CP02_024,
  "CP02-025": c_CP02_025,
  "CP02-026": c_CP02_026,
  "CP02-027": c_CP02_027,
  "CP02-028": c_CP02_028,
  "CP02-029": c_CP02_029,
  "CP02-030": c_CP02_030,
  "CP02-031": c_CP02_031,
  "CP02-032": c_CP02_032,
  "CP02-033": c_CP02_033,
  "CP02-034": c_CP02_034,
  "CP02-035": c_CP02_035,
  "CP02-036": c_CP02_036,
  "CP02-037": c_CP02_037,
  "CP02-038": c_CP02_038,
  "CP02-039": c_CP02_039,
  "CP02-040": c_CP02_040,
  "CP02-041": c_CP02_041,
  "CP02-042": c_CP02_042,
  "CP02-043": c_CP02_043,
  "CP02-044": c_CP02_044,
  "CP02-045": c_CP02_045,
  "CP02-046": c_CP02_046,
  "CP02-047": c_CP02_047,
  "CP02-048": c_CP02_048,
  "CP02-049": c_CP02_049,
  "CP02-050": c_CP02_050,
  "CP02-051": c_CP02_051,
  "CP02-052": c_CP02_052,
  "CP02-053": c_CP02_053,
  "CP02-054": c_CP02_054,
  "CP02-055": c_CP02_055,
  "CP02-056": c_CP02_056,
  "CP02-057": c_CP02_057,
  "CP02-058": c_CP02_058,
  "CP02-059": c_CP02_059,
  "CP02-060": c_CP02_060,
  "CP02-061": c_CP02_061,
  "CP02-062": c_CP02_062,
  "CP02-063": c_CP02_063,
  "CP02-064": c_CP02_064,
  "CP02-065": c_CP02_065,
  "CP02-066": c_CP02_066,
  "CP02-067": c_CP02_067,
  "CP02-068": c_CP02_068,
  "CP02-069": c_CP02_069,
  "CP02-070": c_CP02_070,
  "CP02-071": c_CP02_071,
  "CP02-072": c_CP02_072,
  "CP02-073": c_CP02_073,
  "CP02-074": c_CP02_074,
  "CP02-075": c_CP02_075,
  "CP02-076": c_CP02_076,
  "CP02-077": c_CP02_077,
  "CP02-078": c_CP02_078,
  "CP02-079": c_CP02_079,
  "CP02-080": c_CP02_080,
  "CP02-081": c_CP02_081,
  "CP02-082": c_CP02_082,
  "CP02-083": c_CP02_083,
  "CP02-084": c_CP02_084,
  "CP02-085": c_CP02_085,
  "CP02-086": c_CP02_086,
  "CP02-087": c_CP02_087,
  "CP02-088": c_CP02_088,
  "CP02-089": c_CP02_089,
  "CP02-090": c_CP02_090,
  "CP02-091": c_CP02_091,
  "CP02-092": c_CP02_092,
  "CP02-093": c_CP02_093,
  "CP02-094": c_CP02_094,
  "CP02-095": c_CP02_095,
  "CP02-096": c_CP02_096,
  "CP02-097": c_CP02_097,
  "CP02-098": c_CP02_098,
  "CP02-099": c_CP02_099,
  "CP02-100": c_CP02_100,
  "CP02-101": c_CP02_101,
  "CP02-102": c_CP02_102,
  "CP02-103": c_CP02_103,
  "CP02-104": c_CP02_104,
  "CP02-105": c_CP02_105,
  "CP02-106": c_CP02_106,
  "CP02-107": c_CP02_107,
  "CP02-108": c_CP02_108,
  "CP02-T01": c_CP02_T01,
};
