// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP02_001 from "./BP02-001";
import c_BP02_002 from "./BP02-002";
import c_BP02_003 from "./BP02-003";
import c_BP02_004 from "./BP02-004";
import c_BP02_005 from "./BP02-005";
import c_BP02_006 from "./BP02-006";
import c_BP02_007 from "./BP02-007";
import c_BP02_008 from "./BP02-008";
import c_BP02_009 from "./BP02-009";
import c_BP02_010 from "./BP02-010";
import c_BP02_011 from "./BP02-011";
import c_BP02_012 from "./BP02-012";
import c_BP02_013 from "./BP02-013";
import c_BP02_014 from "./BP02-014";
import c_BP02_015 from "./BP02-015";
import c_BP02_016 from "./BP02-016";
import c_BP02_017 from "./BP02-017";
import c_BP02_018 from "./BP02-018";
import c_BP02_019 from "./BP02-019";
import c_BP02_020 from "./BP02-020";
import c_BP02_021 from "./BP02-021";
import c_BP02_022 from "./BP02-022";
import c_BP02_023 from "./BP02-023";
import c_BP02_024 from "./BP02-024";
import c_BP02_025 from "./BP02-025";
import c_BP02_026 from "./BP02-026";
import c_BP02_027 from "./BP02-027";
import c_BP02_028 from "./BP02-028";
import c_BP02_029 from "./BP02-029";
import c_BP02_030 from "./BP02-030";
import c_BP02_031 from "./BP02-031";
import c_BP02_032 from "./BP02-032";
import c_BP02_033 from "./BP02-033";
import c_BP02_034 from "./BP02-034";
import c_BP02_035 from "./BP02-035";
import c_BP02_036 from "./BP02-036";
import c_BP02_037 from "./BP02-037";
import c_BP02_038 from "./BP02-038";
import c_BP02_039 from "./BP02-039";
import c_BP02_040 from "./BP02-040";
import c_BP02_041 from "./BP02-041";
import c_BP02_042 from "./BP02-042";
import c_BP02_043 from "./BP02-043";
import c_BP02_044 from "./BP02-044";
import c_BP02_045 from "./BP02-045";
import c_BP02_046 from "./BP02-046";
import c_BP02_047 from "./BP02-047";
import c_BP02_048 from "./BP02-048";
import c_BP02_049 from "./BP02-049";
import c_BP02_050 from "./BP02-050";
import c_BP02_051 from "./BP02-051";
import c_BP02_T02 from "./BP02-T02";
import c_BP02_T03 from "./BP02-T03";

/**
 * Card scripts of BP02, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP02_SCRIPTS: ScriptRegistry = {
  "BP02-001": c_BP02_001,
  "BP02-002": c_BP02_002,
  "BP02-003": c_BP02_003,
  "BP02-004": c_BP02_004,
  "BP02-005": c_BP02_005,
  "BP02-006": c_BP02_006,
  "BP02-007": c_BP02_007,
  "BP02-008": c_BP02_008,
  "BP02-009": c_BP02_009,
  "BP02-010": c_BP02_010,
  "BP02-011": c_BP02_011,
  "BP02-012": c_BP02_012,
  "BP02-013": c_BP02_013,
  "BP02-014": c_BP02_014,
  "BP02-015": c_BP02_015,
  "BP02-016": c_BP02_016,
  "BP02-017": c_BP02_017,
  "BP02-018": c_BP02_018,
  "BP02-019": c_BP02_019,
  "BP02-020": c_BP02_020,
  "BP02-021": c_BP02_021,
  "BP02-022": c_BP02_022,
  "BP02-023": c_BP02_023,
  "BP02-024": c_BP02_024,
  "BP02-025": c_BP02_025,
  "BP02-026": c_BP02_026,
  "BP02-027": c_BP02_027,
  "BP02-028": c_BP02_028,
  "BP02-029": c_BP02_029,
  "BP02-030": c_BP02_030,
  "BP02-031": c_BP02_031,
  "BP02-032": c_BP02_032,
  "BP02-033": c_BP02_033,
  "BP02-034": c_BP02_034,
  "BP02-035": c_BP02_035,
  "BP02-036": c_BP02_036,
  "BP02-037": c_BP02_037,
  "BP02-038": c_BP02_038,
  "BP02-039": c_BP02_039,
  "BP02-040": c_BP02_040,
  "BP02-041": c_BP02_041,
  "BP02-042": c_BP02_042,
  "BP02-043": c_BP02_043,
  "BP02-044": c_BP02_044,
  "BP02-045": c_BP02_045,
  "BP02-046": c_BP02_046,
  "BP02-047": c_BP02_047,
  "BP02-048": c_BP02_048,
  "BP02-049": c_BP02_049,
  "BP02-050": c_BP02_050,
  "BP02-051": c_BP02_051,
  "BP02-T02": c_BP02_T02,
  "BP02-T03": c_BP02_T03,
};
