/**
 * Regenerate `packages/core/src/script/<SET>/index.ts` from the script files in that folder.
 * Each file is named after the canonical card definition it implements (e.g. BP01-006.ts).
 *
 *   npm run scripts:index
 */
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const scriptRoot = join(repoRoot, "packages", "core", "src", "script");

for (const set of ["BP01"]) {
  const dir = join(scriptRoot, set);
  const ids = readdirSync(dir)
    .filter((f) => /^[A-Za-z0-9]+-[A-Za-z0-9]+\.ts$/.test(f))
    .map((f) => f.slice(0, -3))
    .sort();
  const ident = (id: string) => `c_${id.replace(/-/g, "_")}`;
  const lines = [
    "// Generated by `npm run scripts:index` — do not edit.",
    'import type { ScriptRegistry } from "../types";',
    ...ids.map((id) => `import ${ident(id)} from "./${id}";`),
    "",
    "/**",
    ` * Card scripts of ${set}, keyed by canonical definition id (alternate printings resolve to the`,
    " * canonical id through the card database). Cards without card text need no script.",
    " */",
    `export const ${set}_SCRIPTS: ScriptRegistry = {`,
    ...ids.map((id) => `  "${id}": ${ident(id)},`),
    "};",
    "",
  ];
  writeFileSync(join(dir, "index.ts"), lines.join("\n"), "utf8");
  console.log(`${set}: ${ids.length} scripts -> script/${set}/index.ts`);
}
