// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_DSD01b_001 from "./DSD01b-001";
import c_DSD01b_002 from "./DSD01b-002";
import c_DSD01b_003 from "./DSD01b-003";
import c_DSD01b_006 from "./DSD01b-006";
import c_DSD01b_007 from "./DSD01b-007";
import c_DSD01b_010 from "./DSD01b-010";
import c_DSD01b_011 from "./DSD01b-011";
import c_DSD01b_012 from "./DSD01b-012";
import c_DSD01b_013 from "./DSD01b-013";
import c_DSD01b_016 from "./DSD01b-016";
import c_DSD01b_T01 from "./DSD01b-T01";

/**
 * Card scripts of DSD01b, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const DSD01b_SCRIPTS: ScriptRegistry = {
  "DSD01b-001": c_DSD01b_001,
  "DSD01b-002": c_DSD01b_002,
  "DSD01b-003": c_DSD01b_003,
  "DSD01b-006": c_DSD01b_006,
  "DSD01b-007": c_DSD01b_007,
  "DSD01b-010": c_DSD01b_010,
  "DSD01b-011": c_DSD01b_011,
  "DSD01b-012": c_DSD01b_012,
  "DSD01b-013": c_DSD01b_013,
  "DSD01b-016": c_DSD01b_016,
  "DSD01b-T01": c_DSD01b_T01,
};
