// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP04_001 from "./BP04-001";
import c_BP04_003 from "./BP04-003";
import c_BP04_004 from "./BP04-004";
import c_BP04_005 from "./BP04-005";
import c_BP04_006 from "./BP04-006";
import c_BP04_007 from "./BP04-007";
import c_BP04_008 from "./BP04-008";
import c_BP04_010 from "./BP04-010";
import c_BP04_011 from "./BP04-011";
import c_BP04_012 from "./BP04-012";
import c_BP04_013 from "./BP04-013";
import c_BP04_014 from "./BP04-014";
import c_BP04_015 from "./BP04-015";
import c_BP04_016 from "./BP04-016";
import c_BP04_017 from "./BP04-017";
import c_BP04_018 from "./BP04-018";
import c_BP04_019 from "./BP04-019";
import c_BP04_020 from "./BP04-020";
import c_BP04_021 from "./BP04-021";
import c_BP04_022 from "./BP04-022";
import c_BP04_023 from "./BP04-023";
import c_BP04_024 from "./BP04-024";
import c_BP04_025 from "./BP04-025";
import c_BP04_026 from "./BP04-026";
import c_BP04_028 from "./BP04-028";
import c_BP04_029 from "./BP04-029";
import c_BP04_030 from "./BP04-030";
import c_BP04_031 from "./BP04-031";
import c_BP04_032 from "./BP04-032";
import c_BP04_033 from "./BP04-033";
import c_BP04_034 from "./BP04-034";
import c_BP04_035 from "./BP04-035";
import c_BP04_036 from "./BP04-036";
import c_BP04_037 from "./BP04-037";
import c_BP04_038 from "./BP04-038";
import c_BP04_039 from "./BP04-039";
import c_BP04_040 from "./BP04-040";
import c_BP04_041 from "./BP04-041";
import c_BP04_042 from "./BP04-042";
import c_BP04_043 from "./BP04-043";
import c_BP04_044 from "./BP04-044";
import c_BP04_046 from "./BP04-046";
import c_BP04_047 from "./BP04-047";
import c_BP04_048 from "./BP04-048";
import c_BP04_049 from "./BP04-049";
import c_BP04_051 from "./BP04-051";
import c_BP04_052 from "./BP04-052";
import c_BP04_053 from "./BP04-053";
import c_BP04_054 from "./BP04-054";
import c_BP04_055 from "./BP04-055";
import c_BP04_056 from "./BP04-056";
import c_BP04_057 from "./BP04-057";
import c_BP04_059 from "./BP04-059";
import c_BP04_060 from "./BP04-060";
import c_BP04_061 from "./BP04-061";
import c_BP04_062 from "./BP04-062";
import c_BP04_063 from "./BP04-063";
import c_BP04_064 from "./BP04-064";
import c_BP04_065 from "./BP04-065";
import c_BP04_066 from "./BP04-066";
import c_BP04_068 from "./BP04-068";
import c_BP04_069 from "./BP04-069";
import c_BP04_070 from "./BP04-070";
import c_BP04_071 from "./BP04-071";
import c_BP04_073 from "./BP04-073";
import c_BP04_074 from "./BP04-074";
import c_BP04_075 from "./BP04-075";
import c_BP04_077 from "./BP04-077";
import c_BP04_078 from "./BP04-078";
import c_BP04_079 from "./BP04-079";
import c_BP04_080 from "./BP04-080";
import c_BP04_081 from "./BP04-081";
import c_BP04_082 from "./BP04-082";
import c_BP04_084 from "./BP04-084";
import c_BP04_085 from "./BP04-085";
import c_BP04_086 from "./BP04-086";
import c_BP04_087 from "./BP04-087";
import c_BP04_088 from "./BP04-088";
import c_BP04_089 from "./BP04-089";
import c_BP04_090 from "./BP04-090";
import c_BP04_092 from "./BP04-092";
import c_BP04_093 from "./BP04-093";
import c_BP04_094 from "./BP04-094";
import c_BP04_095 from "./BP04-095";
import c_BP04_096 from "./BP04-096";
import c_BP04_097 from "./BP04-097";
import c_BP04_098 from "./BP04-098";
import c_BP04_099 from "./BP04-099";
import c_BP04_100 from "./BP04-100";
import c_BP04_101 from "./BP04-101";
import c_BP04_102 from "./BP04-102";
import c_BP04_103 from "./BP04-103";
import c_BP04_104 from "./BP04-104";
import c_BP04_106 from "./BP04-106";
import c_BP04_107 from "./BP04-107";
import c_BP04_108 from "./BP04-108";
import c_BP04_109 from "./BP04-109";
import c_BP04_110 from "./BP04-110";
import c_BP04_111 from "./BP04-111";
import c_BP04_112 from "./BP04-112";
import c_BP04_113 from "./BP04-113";
import c_BP04_114 from "./BP04-114";
import c_BP04_115 from "./BP04-115";
import c_BP04_116 from "./BP04-116";
import c_BP04_117 from "./BP04-117";
import c_BP04_118 from "./BP04-118";
import c_BP04_119 from "./BP04-119";
import c_BP04_120 from "./BP04-120";
import c_BP04_121 from "./BP04-121";
import c_BP04_122 from "./BP04-122";
import c_BP04_123 from "./BP04-123";
import c_BP04_124 from "./BP04-124";
import c_BP04_125 from "./BP04-125";
import c_BP04_126 from "./BP04-126";
import c_BP04_127 from "./BP04-127";
import c_BP04_128 from "./BP04-128";
import c_BP04_129 from "./BP04-129";
import c_BP04_130 from "./BP04-130";
import c_BP04_T01 from "./BP04-T01";
import c_BP04_T02 from "./BP04-T02";

/**
 * Card scripts of BP04, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP04_SCRIPTS: ScriptRegistry = {
  "BP04-001": c_BP04_001,
  "BP04-003": c_BP04_003,
  "BP04-004": c_BP04_004,
  "BP04-005": c_BP04_005,
  "BP04-006": c_BP04_006,
  "BP04-007": c_BP04_007,
  "BP04-008": c_BP04_008,
  "BP04-010": c_BP04_010,
  "BP04-011": c_BP04_011,
  "BP04-012": c_BP04_012,
  "BP04-013": c_BP04_013,
  "BP04-014": c_BP04_014,
  "BP04-015": c_BP04_015,
  "BP04-016": c_BP04_016,
  "BP04-017": c_BP04_017,
  "BP04-018": c_BP04_018,
  "BP04-019": c_BP04_019,
  "BP04-020": c_BP04_020,
  "BP04-021": c_BP04_021,
  "BP04-022": c_BP04_022,
  "BP04-023": c_BP04_023,
  "BP04-024": c_BP04_024,
  "BP04-025": c_BP04_025,
  "BP04-026": c_BP04_026,
  "BP04-028": c_BP04_028,
  "BP04-029": c_BP04_029,
  "BP04-030": c_BP04_030,
  "BP04-031": c_BP04_031,
  "BP04-032": c_BP04_032,
  "BP04-033": c_BP04_033,
  "BP04-034": c_BP04_034,
  "BP04-035": c_BP04_035,
  "BP04-036": c_BP04_036,
  "BP04-037": c_BP04_037,
  "BP04-038": c_BP04_038,
  "BP04-039": c_BP04_039,
  "BP04-040": c_BP04_040,
  "BP04-041": c_BP04_041,
  "BP04-042": c_BP04_042,
  "BP04-043": c_BP04_043,
  "BP04-044": c_BP04_044,
  "BP04-046": c_BP04_046,
  "BP04-047": c_BP04_047,
  "BP04-048": c_BP04_048,
  "BP04-049": c_BP04_049,
  "BP04-051": c_BP04_051,
  "BP04-052": c_BP04_052,
  "BP04-053": c_BP04_053,
  "BP04-054": c_BP04_054,
  "BP04-055": c_BP04_055,
  "BP04-056": c_BP04_056,
  "BP04-057": c_BP04_057,
  "BP04-059": c_BP04_059,
  "BP04-060": c_BP04_060,
  "BP04-061": c_BP04_061,
  "BP04-062": c_BP04_062,
  "BP04-063": c_BP04_063,
  "BP04-064": c_BP04_064,
  "BP04-065": c_BP04_065,
  "BP04-066": c_BP04_066,
  "BP04-068": c_BP04_068,
  "BP04-069": c_BP04_069,
  "BP04-070": c_BP04_070,
  "BP04-071": c_BP04_071,
  "BP04-073": c_BP04_073,
  "BP04-074": c_BP04_074,
  "BP04-075": c_BP04_075,
  "BP04-077": c_BP04_077,
  "BP04-078": c_BP04_078,
  "BP04-079": c_BP04_079,
  "BP04-080": c_BP04_080,
  "BP04-081": c_BP04_081,
  "BP04-082": c_BP04_082,
  "BP04-084": c_BP04_084,
  "BP04-085": c_BP04_085,
  "BP04-086": c_BP04_086,
  "BP04-087": c_BP04_087,
  "BP04-088": c_BP04_088,
  "BP04-089": c_BP04_089,
  "BP04-090": c_BP04_090,
  "BP04-092": c_BP04_092,
  "BP04-093": c_BP04_093,
  "BP04-094": c_BP04_094,
  "BP04-095": c_BP04_095,
  "BP04-096": c_BP04_096,
  "BP04-097": c_BP04_097,
  "BP04-098": c_BP04_098,
  "BP04-099": c_BP04_099,
  "BP04-100": c_BP04_100,
  "BP04-101": c_BP04_101,
  "BP04-102": c_BP04_102,
  "BP04-103": c_BP04_103,
  "BP04-104": c_BP04_104,
  "BP04-106": c_BP04_106,
  "BP04-107": c_BP04_107,
  "BP04-108": c_BP04_108,
  "BP04-109": c_BP04_109,
  "BP04-110": c_BP04_110,
  "BP04-111": c_BP04_111,
  "BP04-112": c_BP04_112,
  "BP04-113": c_BP04_113,
  "BP04-114": c_BP04_114,
  "BP04-115": c_BP04_115,
  "BP04-116": c_BP04_116,
  "BP04-117": c_BP04_117,
  "BP04-118": c_BP04_118,
  "BP04-119": c_BP04_119,
  "BP04-120": c_BP04_120,
  "BP04-121": c_BP04_121,
  "BP04-122": c_BP04_122,
  "BP04-123": c_BP04_123,
  "BP04-124": c_BP04_124,
  "BP04-125": c_BP04_125,
  "BP04-126": c_BP04_126,
  "BP04-127": c_BP04_127,
  "BP04-128": c_BP04_128,
  "BP04-129": c_BP04_129,
  "BP04-130": c_BP04_130,
  "BP04-T01": c_BP04_T01,
  "BP04-T02": c_BP04_T02,
};
