// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP12_001 from "./BP12-001";
import c_BP12_002 from "./BP12-002";
import c_BP12_003 from "./BP12-003";
import c_BP12_004 from "./BP12-004";
import c_BP12_005 from "./BP12-005";
import c_BP12_006 from "./BP12-006";
import c_BP12_007 from "./BP12-007";
import c_BP12_008 from "./BP12-008";
import c_BP12_009 from "./BP12-009";
import c_BP12_010 from "./BP12-010";
import c_BP12_011 from "./BP12-011";
import c_BP12_012 from "./BP12-012";
import c_BP12_013 from "./BP12-013";
import c_BP12_014 from "./BP12-014";
import c_BP12_015 from "./BP12-015";
import c_BP12_016 from "./BP12-016";
import c_BP12_017 from "./BP12-017";
import c_BP12_018 from "./BP12-018";
import c_BP12_019 from "./BP12-019";
import c_BP12_020 from "./BP12-020";
import c_BP12_021 from "./BP12-021";
import c_BP12_022 from "./BP12-022";
import c_BP12_023 from "./BP12-023";
import c_BP12_024 from "./BP12-024";
import c_BP12_025 from "./BP12-025";
import c_BP12_026 from "./BP12-026";
import c_BP12_027 from "./BP12-027";
import c_BP12_028 from "./BP12-028";
import c_BP12_029 from "./BP12-029";
import c_BP12_030 from "./BP12-030";
import c_BP12_031 from "./BP12-031";
import c_BP12_032 from "./BP12-032";
import c_BP12_033 from "./BP12-033";
import c_BP12_034 from "./BP12-034";
import c_BP12_035 from "./BP12-035";
import c_BP12_036 from "./BP12-036";
import c_BP12_037 from "./BP12-037";
import c_BP12_038 from "./BP12-038";
import c_BP12_039 from "./BP12-039";
import c_BP12_040 from "./BP12-040";
import c_BP12_041 from "./BP12-041";
import c_BP12_042 from "./BP12-042";
import c_BP12_043 from "./BP12-043";
import c_BP12_044 from "./BP12-044";
import c_BP12_045 from "./BP12-045";
import c_BP12_046 from "./BP12-046";
import c_BP12_047 from "./BP12-047";
import c_BP12_048 from "./BP12-048";
import c_BP12_049 from "./BP12-049";
import c_BP12_050 from "./BP12-050";
import c_BP12_051 from "./BP12-051";
import c_BP12_052 from "./BP12-052";
import c_BP12_053 from "./BP12-053";
import c_BP12_054 from "./BP12-054";
import c_BP12_055 from "./BP12-055";
import c_BP12_056 from "./BP12-056";
import c_BP12_057 from "./BP12-057";
import c_BP12_058 from "./BP12-058";
import c_BP12_059 from "./BP12-059";
import c_BP12_060 from "./BP12-060";
import c_BP12_061 from "./BP12-061";
import c_BP12_062 from "./BP12-062";
import c_BP12_063 from "./BP12-063";
import c_BP12_064 from "./BP12-064";
import c_BP12_065 from "./BP12-065";
import c_BP12_066 from "./BP12-066";
import c_BP12_067 from "./BP12-067";
import c_BP12_068 from "./BP12-068";
import c_BP12_069 from "./BP12-069";
import c_BP12_070 from "./BP12-070";
import c_BP12_071 from "./BP12-071";
import c_BP12_072 from "./BP12-072";
import c_BP12_073 from "./BP12-073";
import c_BP12_074 from "./BP12-074";
import c_BP12_075 from "./BP12-075";
import c_BP12_076 from "./BP12-076";
import c_BP12_077 from "./BP12-077";
import c_BP12_078 from "./BP12-078";
import c_BP12_079 from "./BP12-079";
import c_BP12_080 from "./BP12-080";
import c_BP12_081 from "./BP12-081";
import c_BP12_082 from "./BP12-082";
import c_BP12_083 from "./BP12-083";
import c_BP12_084 from "./BP12-084";
import c_BP12_085 from "./BP12-085";
import c_BP12_086 from "./BP12-086";
import c_BP12_087 from "./BP12-087";
import c_BP12_088 from "./BP12-088";
import c_BP12_089 from "./BP12-089";
import c_BP12_090 from "./BP12-090";
import c_BP12_091 from "./BP12-091";
import c_BP12_092 from "./BP12-092";
import c_BP12_093 from "./BP12-093";
import c_BP12_094 from "./BP12-094";
import c_BP12_095 from "./BP12-095";
import c_BP12_096 from "./BP12-096";
import c_BP12_097 from "./BP12-097";
import c_BP12_098 from "./BP12-098";
import c_BP12_099 from "./BP12-099";
import c_BP12_100 from "./BP12-100";
import c_BP12_101 from "./BP12-101";
import c_BP12_102 from "./BP12-102";
import c_BP12_103 from "./BP12-103";
import c_BP12_104 from "./BP12-104";
import c_BP12_105 from "./BP12-105";
import c_BP12_106 from "./BP12-106";
import c_BP12_107 from "./BP12-107";
import c_BP12_108 from "./BP12-108";
import c_BP12_109 from "./BP12-109";
import c_BP12_110 from "./BP12-110";
import c_BP12_111 from "./BP12-111";
import c_BP12_112 from "./BP12-112";
import c_BP12_113 from "./BP12-113";
import c_BP12_114 from "./BP12-114";
import c_BP12_115 from "./BP12-115";
import c_BP12_T01 from "./BP12-T01";
import c_BP12_T02 from "./BP12-T02";
import c_BP12_T03 from "./BP12-T03";
import c_BP12_T04 from "./BP12-T04";
import c_BP12_T05 from "./BP12-T05";

/**
 * Card scripts of BP12, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP12_SCRIPTS: ScriptRegistry = {
  "BP12-001": c_BP12_001,
  "BP12-002": c_BP12_002,
  "BP12-003": c_BP12_003,
  "BP12-004": c_BP12_004,
  "BP12-005": c_BP12_005,
  "BP12-006": c_BP12_006,
  "BP12-007": c_BP12_007,
  "BP12-008": c_BP12_008,
  "BP12-009": c_BP12_009,
  "BP12-010": c_BP12_010,
  "BP12-011": c_BP12_011,
  "BP12-012": c_BP12_012,
  "BP12-013": c_BP12_013,
  "BP12-014": c_BP12_014,
  "BP12-015": c_BP12_015,
  "BP12-016": c_BP12_016,
  "BP12-017": c_BP12_017,
  "BP12-018": c_BP12_018,
  "BP12-019": c_BP12_019,
  "BP12-020": c_BP12_020,
  "BP12-021": c_BP12_021,
  "BP12-022": c_BP12_022,
  "BP12-023": c_BP12_023,
  "BP12-024": c_BP12_024,
  "BP12-025": c_BP12_025,
  "BP12-026": c_BP12_026,
  "BP12-027": c_BP12_027,
  "BP12-028": c_BP12_028,
  "BP12-029": c_BP12_029,
  "BP12-030": c_BP12_030,
  "BP12-031": c_BP12_031,
  "BP12-032": c_BP12_032,
  "BP12-033": c_BP12_033,
  "BP12-034": c_BP12_034,
  "BP12-035": c_BP12_035,
  "BP12-036": c_BP12_036,
  "BP12-037": c_BP12_037,
  "BP12-038": c_BP12_038,
  "BP12-039": c_BP12_039,
  "BP12-040": c_BP12_040,
  "BP12-041": c_BP12_041,
  "BP12-042": c_BP12_042,
  "BP12-043": c_BP12_043,
  "BP12-044": c_BP12_044,
  "BP12-045": c_BP12_045,
  "BP12-046": c_BP12_046,
  "BP12-047": c_BP12_047,
  "BP12-048": c_BP12_048,
  "BP12-049": c_BP12_049,
  "BP12-050": c_BP12_050,
  "BP12-051": c_BP12_051,
  "BP12-052": c_BP12_052,
  "BP12-053": c_BP12_053,
  "BP12-054": c_BP12_054,
  "BP12-055": c_BP12_055,
  "BP12-056": c_BP12_056,
  "BP12-057": c_BP12_057,
  "BP12-058": c_BP12_058,
  "BP12-059": c_BP12_059,
  "BP12-060": c_BP12_060,
  "BP12-061": c_BP12_061,
  "BP12-062": c_BP12_062,
  "BP12-063": c_BP12_063,
  "BP12-064": c_BP12_064,
  "BP12-065": c_BP12_065,
  "BP12-066": c_BP12_066,
  "BP12-067": c_BP12_067,
  "BP12-068": c_BP12_068,
  "BP12-069": c_BP12_069,
  "BP12-070": c_BP12_070,
  "BP12-071": c_BP12_071,
  "BP12-072": c_BP12_072,
  "BP12-073": c_BP12_073,
  "BP12-074": c_BP12_074,
  "BP12-075": c_BP12_075,
  "BP12-076": c_BP12_076,
  "BP12-077": c_BP12_077,
  "BP12-078": c_BP12_078,
  "BP12-079": c_BP12_079,
  "BP12-080": c_BP12_080,
  "BP12-081": c_BP12_081,
  "BP12-082": c_BP12_082,
  "BP12-083": c_BP12_083,
  "BP12-084": c_BP12_084,
  "BP12-085": c_BP12_085,
  "BP12-086": c_BP12_086,
  "BP12-087": c_BP12_087,
  "BP12-088": c_BP12_088,
  "BP12-089": c_BP12_089,
  "BP12-090": c_BP12_090,
  "BP12-091": c_BP12_091,
  "BP12-092": c_BP12_092,
  "BP12-093": c_BP12_093,
  "BP12-094": c_BP12_094,
  "BP12-095": c_BP12_095,
  "BP12-096": c_BP12_096,
  "BP12-097": c_BP12_097,
  "BP12-098": c_BP12_098,
  "BP12-099": c_BP12_099,
  "BP12-100": c_BP12_100,
  "BP12-101": c_BP12_101,
  "BP12-102": c_BP12_102,
  "BP12-103": c_BP12_103,
  "BP12-104": c_BP12_104,
  "BP12-105": c_BP12_105,
  "BP12-106": c_BP12_106,
  "BP12-107": c_BP12_107,
  "BP12-108": c_BP12_108,
  "BP12-109": c_BP12_109,
  "BP12-110": c_BP12_110,
  "BP12-111": c_BP12_111,
  "BP12-112": c_BP12_112,
  "BP12-113": c_BP12_113,
  "BP12-114": c_BP12_114,
  "BP12-115": c_BP12_115,
  "BP12-T01": c_BP12_T01,
  "BP12-T02": c_BP12_T02,
  "BP12-T03": c_BP12_T03,
  "BP12-T04": c_BP12_T04,
  "BP12-T05": c_BP12_T05,
};
