// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_BP15_001 from "./BP15-001";
import c_BP15_002 from "./BP15-002";
import c_BP15_003 from "./BP15-003";
import c_BP15_004 from "./BP15-004";
import c_BP15_005 from "./BP15-005";
import c_BP15_006 from "./BP15-006";
import c_BP15_007 from "./BP15-007";
import c_BP15_008 from "./BP15-008";
import c_BP15_009 from "./BP15-009";
import c_BP15_010 from "./BP15-010";
import c_BP15_011 from "./BP15-011";
import c_BP15_012 from "./BP15-012";
import c_BP15_013 from "./BP15-013";
import c_BP15_014 from "./BP15-014";
import c_BP15_015 from "./BP15-015";
import c_BP15_016 from "./BP15-016";
import c_BP15_017 from "./BP15-017";
import c_BP15_018 from "./BP15-018";
import c_BP15_019 from "./BP15-019";
import c_BP15_020 from "./BP15-020";
import c_BP15_021 from "./BP15-021";
import c_BP15_022 from "./BP15-022";
import c_BP15_023 from "./BP15-023";
import c_BP15_024 from "./BP15-024";
import c_BP15_025 from "./BP15-025";
import c_BP15_026 from "./BP15-026";
import c_BP15_027 from "./BP15-027";
import c_BP15_028 from "./BP15-028";
import c_BP15_029 from "./BP15-029";
import c_BP15_030 from "./BP15-030";
import c_BP15_031 from "./BP15-031";
import c_BP15_032 from "./BP15-032";
import c_BP15_033 from "./BP15-033";
import c_BP15_034 from "./BP15-034";
import c_BP15_035 from "./BP15-035";
import c_BP15_036 from "./BP15-036";
import c_BP15_037 from "./BP15-037";
import c_BP15_038 from "./BP15-038";
import c_BP15_039 from "./BP15-039";
import c_BP15_040 from "./BP15-040";
import c_BP15_041 from "./BP15-041";
import c_BP15_042 from "./BP15-042";
import c_BP15_043 from "./BP15-043";
import c_BP15_044 from "./BP15-044";
import c_BP15_045 from "./BP15-045";
import c_BP15_046 from "./BP15-046";
import c_BP15_047 from "./BP15-047";
import c_BP15_048 from "./BP15-048";
import c_BP15_049 from "./BP15-049";
import c_BP15_050 from "./BP15-050";
import c_BP15_051 from "./BP15-051";
import c_BP15_052 from "./BP15-052";
import c_BP15_053 from "./BP15-053";
import c_BP15_054 from "./BP15-054";
import c_BP15_055 from "./BP15-055";
import c_BP15_056 from "./BP15-056";
import c_BP15_057 from "./BP15-057";
import c_BP15_058 from "./BP15-058";
import c_BP15_059 from "./BP15-059";
import c_BP15_060 from "./BP15-060";
import c_BP15_061 from "./BP15-061";
import c_BP15_062 from "./BP15-062";
import c_BP15_063 from "./BP15-063";
import c_BP15_064 from "./BP15-064";
import c_BP15_065 from "./BP15-065";
import c_BP15_066 from "./BP15-066";
import c_BP15_067 from "./BP15-067";
import c_BP15_068 from "./BP15-068";
import c_BP15_069 from "./BP15-069";
import c_BP15_070 from "./BP15-070";
import c_BP15_071 from "./BP15-071";
import c_BP15_072 from "./BP15-072";
import c_BP15_073 from "./BP15-073";
import c_BP15_074 from "./BP15-074";
import c_BP15_075 from "./BP15-075";
import c_BP15_076 from "./BP15-076";
import c_BP15_077 from "./BP15-077";
import c_BP15_078 from "./BP15-078";
import c_BP15_079 from "./BP15-079";
import c_BP15_080 from "./BP15-080";
import c_BP15_081 from "./BP15-081";
import c_BP15_082 from "./BP15-082";
import c_BP15_083 from "./BP15-083";
import c_BP15_084 from "./BP15-084";
import c_BP15_085 from "./BP15-085";
import c_BP15_086 from "./BP15-086";
import c_BP15_087 from "./BP15-087";
import c_BP15_088 from "./BP15-088";
import c_BP15_089 from "./BP15-089";
import c_BP15_090 from "./BP15-090";
import c_BP15_091 from "./BP15-091";
import c_BP15_092 from "./BP15-092";
import c_BP15_093 from "./BP15-093";
import c_BP15_094 from "./BP15-094";
import c_BP15_095 from "./BP15-095";
import c_BP15_096 from "./BP15-096";
import c_BP15_097 from "./BP15-097";
import c_BP15_098 from "./BP15-098";
import c_BP15_099 from "./BP15-099";
import c_BP15_100 from "./BP15-100";
import c_BP15_101 from "./BP15-101";
import c_BP15_102 from "./BP15-102";
import c_BP15_103 from "./BP15-103";
import c_BP15_104 from "./BP15-104";
import c_BP15_105 from "./BP15-105";
import c_BP15_106 from "./BP15-106";
import c_BP15_107 from "./BP15-107";
import c_BP15_108 from "./BP15-108";
import c_BP15_109 from "./BP15-109";
import c_BP15_110 from "./BP15-110";
import c_BP15_111 from "./BP15-111";
import c_BP15_112 from "./BP15-112";
import c_BP15_113 from "./BP15-113";
import c_BP15_114 from "./BP15-114";
import c_BP15_115 from "./BP15-115";
import c_BP15_116 from "./BP15-116";
import c_BP15_117 from "./BP15-117";
import c_BP15_118 from "./BP15-118";
import c_BP15_119 from "./BP15-119";
import c_BP15_120 from "./BP15-120";
import c_BP15_121 from "./BP15-121";
import c_BP15_122 from "./BP15-122";
import c_BP15_123 from "./BP15-123";
import c_BP15_124 from "./BP15-124";
import c_BP15_125 from "./BP15-125";
import c_BP15_126 from "./BP15-126";
import c_BP15_PR09 from "./BP15-PR09";
import c_BP15_PR10 from "./BP15-PR10";
import c_BP15_PR11 from "./BP15-PR11";
import c_BP15_PR12 from "./BP15-PR12";
import c_BP15_PR13 from "./BP15-PR13";
import c_BP15_PR14 from "./BP15-PR14";
import c_BP15_PR15 from "./BP15-PR15";
import c_BP15_PR16 from "./BP15-PR16";
import c_BP15_PR17 from "./BP15-PR17";
import c_BP15_PR18 from "./BP15-PR18";
import c_BP15_T01 from "./BP15-T01";
import c_BP15_T02 from "./BP15-T02";
import c_BP15_T03 from "./BP15-T03";
import c_BP15_T04 from "./BP15-T04";

/**
 * Card scripts of BP15, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const BP15_SCRIPTS: ScriptRegistry = {
  "BP15-001": c_BP15_001,
  "BP15-002": c_BP15_002,
  "BP15-003": c_BP15_003,
  "BP15-004": c_BP15_004,
  "BP15-005": c_BP15_005,
  "BP15-006": c_BP15_006,
  "BP15-007": c_BP15_007,
  "BP15-008": c_BP15_008,
  "BP15-009": c_BP15_009,
  "BP15-010": c_BP15_010,
  "BP15-011": c_BP15_011,
  "BP15-012": c_BP15_012,
  "BP15-013": c_BP15_013,
  "BP15-014": c_BP15_014,
  "BP15-015": c_BP15_015,
  "BP15-016": c_BP15_016,
  "BP15-017": c_BP15_017,
  "BP15-018": c_BP15_018,
  "BP15-019": c_BP15_019,
  "BP15-020": c_BP15_020,
  "BP15-021": c_BP15_021,
  "BP15-022": c_BP15_022,
  "BP15-023": c_BP15_023,
  "BP15-024": c_BP15_024,
  "BP15-025": c_BP15_025,
  "BP15-026": c_BP15_026,
  "BP15-027": c_BP15_027,
  "BP15-028": c_BP15_028,
  "BP15-029": c_BP15_029,
  "BP15-030": c_BP15_030,
  "BP15-031": c_BP15_031,
  "BP15-032": c_BP15_032,
  "BP15-033": c_BP15_033,
  "BP15-034": c_BP15_034,
  "BP15-035": c_BP15_035,
  "BP15-036": c_BP15_036,
  "BP15-037": c_BP15_037,
  "BP15-038": c_BP15_038,
  "BP15-039": c_BP15_039,
  "BP15-040": c_BP15_040,
  "BP15-041": c_BP15_041,
  "BP15-042": c_BP15_042,
  "BP15-043": c_BP15_043,
  "BP15-044": c_BP15_044,
  "BP15-045": c_BP15_045,
  "BP15-046": c_BP15_046,
  "BP15-047": c_BP15_047,
  "BP15-048": c_BP15_048,
  "BP15-049": c_BP15_049,
  "BP15-050": c_BP15_050,
  "BP15-051": c_BP15_051,
  "BP15-052": c_BP15_052,
  "BP15-053": c_BP15_053,
  "BP15-054": c_BP15_054,
  "BP15-055": c_BP15_055,
  "BP15-056": c_BP15_056,
  "BP15-057": c_BP15_057,
  "BP15-058": c_BP15_058,
  "BP15-059": c_BP15_059,
  "BP15-060": c_BP15_060,
  "BP15-061": c_BP15_061,
  "BP15-062": c_BP15_062,
  "BP15-063": c_BP15_063,
  "BP15-064": c_BP15_064,
  "BP15-065": c_BP15_065,
  "BP15-066": c_BP15_066,
  "BP15-067": c_BP15_067,
  "BP15-068": c_BP15_068,
  "BP15-069": c_BP15_069,
  "BP15-070": c_BP15_070,
  "BP15-071": c_BP15_071,
  "BP15-072": c_BP15_072,
  "BP15-073": c_BP15_073,
  "BP15-074": c_BP15_074,
  "BP15-075": c_BP15_075,
  "BP15-076": c_BP15_076,
  "BP15-077": c_BP15_077,
  "BP15-078": c_BP15_078,
  "BP15-079": c_BP15_079,
  "BP15-080": c_BP15_080,
  "BP15-081": c_BP15_081,
  "BP15-082": c_BP15_082,
  "BP15-083": c_BP15_083,
  "BP15-084": c_BP15_084,
  "BP15-085": c_BP15_085,
  "BP15-086": c_BP15_086,
  "BP15-087": c_BP15_087,
  "BP15-088": c_BP15_088,
  "BP15-089": c_BP15_089,
  "BP15-090": c_BP15_090,
  "BP15-091": c_BP15_091,
  "BP15-092": c_BP15_092,
  "BP15-093": c_BP15_093,
  "BP15-094": c_BP15_094,
  "BP15-095": c_BP15_095,
  "BP15-096": c_BP15_096,
  "BP15-097": c_BP15_097,
  "BP15-098": c_BP15_098,
  "BP15-099": c_BP15_099,
  "BP15-100": c_BP15_100,
  "BP15-101": c_BP15_101,
  "BP15-102": c_BP15_102,
  "BP15-103": c_BP15_103,
  "BP15-104": c_BP15_104,
  "BP15-105": c_BP15_105,
  "BP15-106": c_BP15_106,
  "BP15-107": c_BP15_107,
  "BP15-108": c_BP15_108,
  "BP15-109": c_BP15_109,
  "BP15-110": c_BP15_110,
  "BP15-111": c_BP15_111,
  "BP15-112": c_BP15_112,
  "BP15-113": c_BP15_113,
  "BP15-114": c_BP15_114,
  "BP15-115": c_BP15_115,
  "BP15-116": c_BP15_116,
  "BP15-117": c_BP15_117,
  "BP15-118": c_BP15_118,
  "BP15-119": c_BP15_119,
  "BP15-120": c_BP15_120,
  "BP15-121": c_BP15_121,
  "BP15-122": c_BP15_122,
  "BP15-123": c_BP15_123,
  "BP15-124": c_BP15_124,
  "BP15-125": c_BP15_125,
  "BP15-126": c_BP15_126,
  "BP15-PR09": c_BP15_PR09,
  "BP15-PR10": c_BP15_PR10,
  "BP15-PR11": c_BP15_PR11,
  "BP15-PR12": c_BP15_PR12,
  "BP15-PR13": c_BP15_PR13,
  "BP15-PR14": c_BP15_PR14,
  "BP15-PR15": c_BP15_PR15,
  "BP15-PR16": c_BP15_PR16,
  "BP15-PR17": c_BP15_PR17,
  "BP15-PR18": c_BP15_PR18,
  "BP15-T01": c_BP15_T01,
  "BP15-T02": c_BP15_T02,
  "BP15-T03": c_BP15_T03,
  "BP15-T04": c_BP15_T04,
};
