// Generated by `npm run scripts:index` — do not edit.
import type { ScriptRegistry } from "../types";
import c_SD04_001 from "./SD04-001";
import c_SD04_002 from "./SD04-002";
import c_SD04_003 from "./SD04-003";
import c_SD04_004 from "./SD04-004";
import c_SD04_005 from "./SD04-005";
import c_SD04_006 from "./SD04-006";
import c_SD04_009 from "./SD04-009";
import c_SD04_010 from "./SD04-010";
import c_SD04_011 from "./SD04-011";
import c_SD04_012 from "./SD04-012";
import c_SD04_013 from "./SD04-013";
import c_SD04_014 from "./SD04-014";

/**
 * Card scripts of SD04, keyed by canonical definition id (alternate printings resolve to the
 * canonical id through the card database). Cards without card text need no script.
 */
export const SD04_SCRIPTS: ScriptRegistry = {
  "SD04-001": c_SD04_001,
  "SD04-002": c_SD04_002,
  "SD04-003": c_SD04_003,
  "SD04-004": c_SD04_004,
  "SD04-005": c_SD04_005,
  "SD04-006": c_SD04_006,
  "SD04-009": c_SD04_009,
  "SD04-010": c_SD04_010,
  "SD04-011": c_SD04_011,
  "SD04-012": c_SD04_012,
  "SD04-013": c_SD04_013,
  "SD04-014": c_SD04_014,
};
